{include file="cplugin/layout_up.phtml"}
<div class="dashboard ui-widget-content ui-corner-all">
<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>{$pluginName}</div>
	<div class="column">
		<div class="dashboard ui-widget-content ui-corner-all">
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Nettoyer les caches</div>
			<div class="dashboard-content">
				<div style="margin-left:10px;padding:5px;">
				<table style="width:100%;">
					<tr>
						<td style="width:60%;"><p>Permet d'effacer les fichiers temporaires de votre site internet</p></td>
						<td style="width:40%;"><div id="clear-tpl-cache" class="clear-cache">Vider le cache template</div></td>
					</tr>
					<tr>
						<td style="width:60%;">
						<p>Permet d'effacer les fichiers du caches de minify</p>
							<div class="ui-widget-header ui-corner-all" style="margin-top:5px;padding:3px;min-height:32px;width:300px;">
								<span style="float:left;" class="notify-32-icon notify-32-icon-light-bulb"></span>
								<div style="margin-top:5px;">La regénération du cache de minify est assez longue</div>
							</div>
						</td>
						<td style="width:40%;"><div id="clear-minify-cache" class="clear-cache">Vider le cache de minify</div></td>
					</tr>
				</table>
				</div>
			</div>
		</div>
	</div>
	<div class="column">
		<div class="dashboard ui-widget-content ui-corner-all">
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span>About</div>
			<div class="dashboard-content">
				<div style="margin-left:10px;padding:5px;">
				<ul>
					<li>Version 0.1</li>
					<li>Author: Gerits Aurelien</li>
					<li>Website: <a style="text-decoration:underline;" class="targetblank" href="http://magix-cjquery.com">magix cjquery</a></li>
					<li>Support du plugin: <a style="text-decoration:underline;" class="targetblank" href="http://forum.logiciel-referencement-professionnel.com/plugins-f5.html">Forum plugins</a></li>
				</ul>
				</div>
			</div>
		</div>
	</div>	
</div>
{include file="cplugin/layout_down.phtml"}