{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    <h1>Traduction statique</h1>
                    <h2>Edition du fichier : {$smarty.get.tab} {if $smarty.get.plugin}{$smarty.get.plugin}{/if}</h2>
                    <div class="mc-message clearfix"></div>
                    {include file="forms/edit.phtml"}
                </div>
            </div>
        </div>
    </div>
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="js.phtml"}
</body>
</html>