{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    <h1>Traduction statique</h1>
                    <p>
                        Les fichiers de traductions sont enregistrés avec l'extension .conf suivant la langue.
                    </p>
                    <p>
                        Le dossier locali18 contient les fichiers de traductions pour l’ensemble des modules intégré,
                        mais les plugins utilisent leur propre fichier de traduction.
                    </p>
                    <div class="row-fluid">
                    {foreach $array_lang as $key => $value nocache}
                    <div class="span3">
                        <div class="well">
                            <h2><span class="icon-flag"></span> {$value|upper}</h2>
                            <p>
                                <a class="btn btn-primary" href="/{baseadmin}/plugins.php?name=translation&amp;getlang={$key}&amp;action=list">
                                    <span class="icon-folder-open"></span> Administrer
                                </a>
                            </p>
                        </div>
                    </div>
                    {/foreach}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="js.phtml"}
</body>
</html>