<form id="forms_user_add" method="post" class="form-horizontal" action="">
    <div class="control-group">
        <label class="control-label" for="pseudo">Pseudo *</label>
        <p class="controls">
            <input type="text" placeholder="Nom d'utilisateur" class="input-large" id="pseudo" name="pseudo" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <label class="control-label" for="email">Email *</label>
        <p class="controls">
            <input type="text" placeholder="Email" class="input-large" id="email" name="email" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <label class="control-label" for="cryptpass">Mot de passe *</label>
        <p class="controls">
            <input type="password" placeholder="Mot de passe" class="input-large" id="cryptpass" name="cryptpass" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <label class="control-label" for="cryptpass_confirm">Confirmer le mot de passe *</label>
        <p class="controls">
            <input type="password" placeholder="Confirmer le mot de passe" class="input-large" id="cryptpass_confirm" name="cryptpass_confirm" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <p class="controls">
            <input type="submit" class="btn btn-primary" value="Envoyer" />
        </p>
    </div>
</form>