<form id="forms_user_add" method="post" class="form-horizontal" action="">
    <div class="control-group">
        <label class="control-label" for="pseudo">{#label_username#} *</label>
        <p class="controls">
            <input type="text" placeholder="{#label_username#}" class="input-large" id="pseudo" name="pseudo" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <label class="control-label" for="email">Email *</label>
        <p class="controls">
            <input type="text" placeholder="Email" class="input-large" id="email" name="email" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <label class="control-label" for="cryptpass">{#label_password#} *</label>
        <p class="controls">
            <input type="password" placeholder="{#label_password#}" class="input-large" id="cryptpass" name="cryptpass" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <label class="control-label" for="cryptpass_confirm">{#label_confirm_password#} *</label>
        <p class="controls">
            <input type="password" placeholder="{#label_confirm_password#}" class="input-large" id="cryptpass_confirm" name="cryptpass_confirm" value="" size="50" />
        </p>
    </div>
    <div class="control-group">
        <p class="controls">
            <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
        </p>
    </div>
</form>