{if $smarty.get.tab eq "image"}
    <form id="forms_catalog_subcategory_image" method="post" action="" enctype="multipart/form-data">
        <p>
            <label for="img_s">Image :</label>
            <input type="hidden" name="MAX_FILE_SIZE" value="2048576" />
            <input type="file" id="img_s" name="img_s" value="" />
            <input type="submit" class="btn btn-primary" value="Envoyer" />
        </p>
    </form>
    <div id="load_catalog_subcategory_img">
        <div id="contener_image"></div>
    </div>
{elseif $smarty.get.tab eq "product"}
    <div id="list_subcategory_product"></div>
{else}
    <form id="forms_catalog_subcategory_edit" method="post" action="">
        <p>
            <label for="subcategorylink">URL</label>
            <input type="text" class="input-xxlarge" id="subcategorylink" readonly="readonly" size="50" value="" />
        </p>
        <p class="pull-left">
            <label for="iso">ISO</label>
            <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
        </p>
        <p class="controls-row offset1 input-append">
            <label for="pathslibelle">URL Simplifié</label>
            <input type="text" class="input-xlarge" id="pathslibelle" name="pathslibelle" readonly="readonly" size="30" value="{$pathslibelle}" />
            <a class="unlocked" href="#">
                <span class="add-on icon-lock"></span>
            </a>
        </p>
        <p>
            <label for="slibelle">Titre :</label>
            <input type="text" class="input-xlarge" id="slibelle" name="slibelle" value="{$slibelle}" size="50" />
        </p>
        <p>
            <label for="s_content" class="inlinelabel">Contenu :</label>
            <textarea name="s_content" id="s_content" class="mceEditor">{$s_content}</textarea>
        </p>
        <p>
            <input type="submit" class="btn btn-primary" value="Envoyer" />
        </p>
    </form>
{/if}