{include file="cplugin/layout_up.phtml"}
<div class="dashboard ui-widget-content ui-corner-all">
<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>{$pluginName}</div>
	<div class="dashboard-content">
		<form method="post" action="{geturl}/admin/dashboard/plugin/{$pluginName}/edit/{$smarty.get.edit}" style="margin-left:10px;">
		{$msg}
		<fieldset>
		<table>
			<tr>
				<td class="label"><label for="gpcatname" class="inlinelabel">Nom de la catégorie :</label></td>
			</tr>
			<tr>
				<td><input type="text" id="gpcatname" name="gpcatname" class="inputtext ui-corner-all" value="{$gpcatname}" size="50" /></td>
				<td style="width:150px;" class="errorInput"></td>
			</tr>
			<tr>
				<td class="status"></td>
			</tr>
			<tr>
				<td class="label"><label for="gpgenerictxt" class="inlinelabel">Contenu :</label></td>
			</tr>
			<tr>
				<td><textarea name="gpgenerictxt" class="fulltext mceEditor ui-corner-all" cols="" rows="">{$gpgenerictxt}</textarea></td>
				<td style="width:150px;" class="errorInput"></td>
			</tr>
			<tr>
				<td class="status"></td>
			</tr>
		</table>			
	</fieldset>
	<div id="showmetas" class="fg-button ui-state-default fg-button-icon-left ui-corner-all"><span style="float:left;"></span> Voir les métas</div>
		<div id="metas">
		<table>
			<tr>
				<td class="label"><label for="gptitle" class="inlinelabel">Title :</label></td>
			</tr>
			<tr>
				<td><textarea id="gptitle" name="gptitle" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2">{$gptitle}</textarea></td>
				<td style="width:150px;" class="errorInput"></td>
			</tr>
			<tr>
				<td class="status"></td>
			</tr>
			<tr>
				<td class="label"><label for="gpdescription" class="inlinelabel">Description :</label></td>
			</tr>
			<tr>
				<td><textarea name="gpdescription" id="gpdescription" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2">{$gpdescription}</textarea></td>
				<td style="width:150px;" class="errorInput"></td>
			</tr>
			<tr>
				<td class="status"></td>
			</tr>
		</table>
		</div>
	<div style="margin:5px;"><input type="submit" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
</form>
	</div>
</div>
{include file="cplugin/layout_down.phtml"}