{include file="cplugin/layout_up.phtml"}
<div class="dashboard ui-widget-content ui-corner-all">
<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>{$pluginName}</div>
	<div class="dashboard-content">
		<form id="forms-upload-csv" method="post" enctype="multipart/form-data" action="" style="margin-left:10px;">
			<div class="request"></div>
			<fieldset>
			<table>
			<tr>
				<td>
					<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
				</td>
			</tr>
			<tr>
				<td class="label"><label for="import" class="inlinelabel">import :</label></td>
			</tr>
			<tr>
				<td>
					<input type="file" id="import" name="import" value="" />
				</td>
				<td style="width:150px;" class="errorInput"></td>
			</tr>
			<tr>
				<td class="status"></td>
			</tr>
			</table>			
			</fieldset>
			<div style="margin:5px;">
				<input type="submit" class="fg-button ui-state-default ui-corner-all" value="Envoyer" />
			</div>
		</form>
	</div>
</div>
{include file="cplugin/layout_down.phtml"}