{include file="cplugin/layout_up.phtml"}
<div class="dashboard ui-widget-content ui-corner-all">
<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>{$pluginName}</div>
	<div class="dashboard-content">
		<div class="column">
			<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Les catégories</div>
				<div class="dashboard-content">
				{$category}
				<div class="fg-button ui-state-default ui-corner-all" style="margin:5px;width:135px;"><a href="{geturl}/admin/dashboard/plugin/{$pluginName}/ajouter/">Ajouter une catégorie</a></div>
				</div>
			</div>
		</div>
		<div class="column">
			<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Nombre total de régions</div>
				<div class="dashboard-content">
				{$stats}
				<div class="fg-button ui-state-default ui-corner-all" style="margin:5px;width:135px;"><a href="{geturl}/admin/dashboard/plugin/{$pluginName}/import/">Importation villes</a></div>
				</div>
			</div>
		</div>
	</div>		
</div>
{include file="cplugin/layout_down.phtml"}