{magixmin}
{literal}
<script type="text/javascript">
var valimport = $("#forms-upload-csv").validate({
	onsubmit: true,
	event: 'submit',
	rules: {
		import: {
			required: true,
			minlength: 1,
			accept: "(csv|txt)"
		}
	},
	messages: {
		import: {
			required: "Uniquement des .csv et .txt",
			accept: "(csv|txt)"
		}
	},
	submitHandler: function(form) {
		$(form).ajaxSubmit({url:"/admin/dashboard/plugin/gpageRegional/import/post",
			type:"post",
			//beforeSubmit:;
			success: function(e) {
				$(".request").html(e);
			},
			resetForm: true
		});
	}
});
$("#forms-upload-csv").valimport;
</script>
{/literal}
{/magixmin}