{include file="section/head.phtml"}
<title>Test</title>
</head>
<body class="module-dashboard">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
        {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span6">
                    <h2>Version</h2>
                    <div class="alert alert-block">
                        <span class="icon-info-sign"></span> Version courante de magix cms
                        <span id="version"></span>
                    </div>
                </div>
                <div class="span6">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
            </div>
            <div class="row-fluid">
                <div class="span6">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
                <div class="span6">
                    <h2>Heading</h2>
                    <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
                    <p><a class="btn" href="#">View details &raquo;</a></p>
                </div>
            </div>
        </div>
    </div>
    {include file="section/footer.phtml"}
</div>
{include file="section/js.phtml"}
{include file="dashboard/section/js.phtml"}
</body>
</html>