{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Editer une page d'accueil</a></div>
						<div class="dashboard-widget-content">
						{include file="home/forms/edit.phtml"}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Page d'accueil</div>
						<div class="dashboard-widget-content">
							{widget_home}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
<div id="dialog_delete" style="display:none;">
	<p>Etes-vous sur de vouloir supprimer cet élément ?</p>
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jhome.0.2.js',function(){
		if (typeof ns_jhome == "undefined") {
		  console.log("ns_jhome is not defined");
		}else{
			ns_jhome.runEdit();
		}
	});
});
</script>
{include file="common/editor.phtml"}
</body>
</html>