{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter</div>
						<div class="dashboard-content">
						<form id="forms-home" method="post" action="" style="margin-left:10px;">
						{$msg}
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="subject" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="subject" name="subject" class="inputtext ui-corner-all" value="" size="50" /></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									{$selectlang}
									<tr>
										<td class="label"><label for="content" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="content" class="fulltext mceEditor ui-corner-all" cols="" rows=""></textarea></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
								</table>			
							</fieldset>
							<div id="showmetas" class="fg-button ui-state-default fg-button-icon-left ui-corner-all"><span style="float:left;"></span> Voir les métas</div>
								<div id="metas">
								<table>
									<tr>
										<td class="label"><label for="metatitle" class="inlinelabel">Title :</label></td>
									</tr>
									<tr>
										<td>
											<textarea id="metatitle" name="metatitle" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
											<div id="charactersLeftT" class="wrap">120</div>
										</td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									<tr>
										<td class="label"><label for="metadescription" class="inlinelabel">Description :</label></td>
									</tr>
									<tr>
										<td>
										<textarea name="metadescription" id="metadescription" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
										<div id="charactersLeftD" class="wrap">180</div>
										</td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
								</table>
								</div>
							<div style="margin:5px;"><input type="submit" /></div>
						</form>
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Page d'accueil</div>
						<div class="dashboard-content">
							{widget_home}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function() {
	$("#meta").click(function(){
		var visible = $("#forms-metas").toggle().is(":visible");
		 $(this).html(visible ? "-" : "+");
	});
});
</script>
{include file="common/editor.phtml"}
</body>
</html>