{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Ajouter une page d'accueil</a></div>
						<div class="dashboard-widget-content">
						<form id="forms-home" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="subject" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="subject" name="subject" class="inputtext ui-corner-all" value="" size="50" /></td>
									</tr>
									{$selectlang}
									<tr>
										<td class="label"><label for="content" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="content" class="fulltext mceEditor ui-corner-all" cols="" rows=""></textarea></td>
									</tr>
								</table>			
							</fieldset>
							<div id="showmetas"><span style="float:left;"></span> Voir les métas</div>
								<div id="metascontener">
								<table>
									<tr>
										<td class="label"><label for="metatitle" class="inlinelabel">Title :</label></td>
									</tr>
									<tr>
										<td>
											<textarea id="metatitle" name="metatitle" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
											<div id="charactersLeftT" class="wrap">120</div>
										</td>
									</tr>
									<tr>
										<td class="label"><label for="metadescription" class="inlinelabel">Description :</label></td>
									</tr>
									<tr>
										<td>
										<textarea name="metadescription" id="metadescription" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
										<div id="charactersLeftD" class="wrap">180</div>
										</td>
									</tr>
								</table>
								</div>
							<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
						</form>
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Page d'accueil</div>
						<div class="dashboard-content">
							{widget_home}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/jhome.1.0.js');
});
</script>
{include file="common/editor.phtml"}
</body>
</html>