<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <a class="brand" href="#">CMS</a>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Gestion des pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Ajouter une page parente</a></li>
                            <li><a href="/{baseadmin}/cms.php?getlang={$smarty.get.getlang}">Liste des pages parente</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li class="nav-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <form action="" class="navbar-search pull-right">
                    <input type="text" placeholder="Search" class="search-query">
                </form>
            </div>
        </div>
    </div>
</div>