<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <a class="brand" href="#">CMS</a>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Gestion des pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/{baseadmin}/cms.php?getlang={$smarty.get.getlang}">Liste des pages parente</a></li>
                            {if $idcat_p > 0 OR $smarty.get.get_page_p}
                                {if $idcat_p}
                                    {assign var="parent_id" value=$idcat_p}
                                {else}
                                    {assign var="parent_id" value=$smarty.get.get_page_p}
                                {/if}
                            <li class="divider"></li>
                            <li class="nav-header">{$parent_title}</li>
                            <li><a href="/{baseadmin}/cms.php?getlang={$smarty.get.getlang}&get_page_p={$parent_id}">Liste des pages enfants</a></li>
                            {/if}
                        </ul>
                    </li>
                </ul>
                <form action="" class="navbar-search pull-right">
                    <input type="text" placeholder="Search" class="search-query">
                </form>
            </div>
        </div>
    </div>
</div>