<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">CMS</a></li>
                    <li><a href="/{baseadmin}/cms.php">{#statistics#|ucfirst}</a></li>
                    {if $smarty.get.getlang}
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            {#pages_management#|ucfirst} <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/{baseadmin}/cms.php?getlang={$smarty.get.getlang}&amp;action=list">
                                    {#list_of_parent_pages#|ucfirst}
                                </a>
                            </li>
                            {if $idcat_p > 0 OR $smarty.get.get_page_p}
                                {if $idcat_p}
                                    {assign var="parent_id" value=$idcat_p}
                                {else}
                                    {assign var="parent_id" value=$smarty.get.get_page_p}
                                {/if}
                            <li class="divider"></li>
                            <li class="nav-header">{$parent_title}</li>
                            <li>
                                <a href="/{baseadmin}/cms.php?getlang={$smarty.get.getlang}&amp;action=list&amp;get_page_p={$parent_id}">
                                    {#list_of_child_pages#|ucfirst}
                                </a>
                            </li>
                            {/if}
                        </ul>
                    </li>
                    {else}
                        <li class="dropdown">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                {#pages_management#|ucfirst} <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="/{baseadmin}/cms.php?getlang=1&amp;action=list">
                                        <img src="/{baseadmin}/template/img/flags/fr.png" />
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {/if}
                </ul>
                <form action="" class="navbar-search pull-right">
                    <input type="text" id="title_search" name="title_search" placeholder="Search" class="search-query">
                </form>
            </div>
        </div>
    </div>
</div>