{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'0','idmetas'=>'2','default'=>#seo_t_static_news#]}}
    <title>{seo_rewrite config_param=['level'=>'0','idmetas'=>'1','default'=>#seo_t_static_news#]}</title>
{include file="common/css.phtml"}
</head>
<body>
<div id="page">
{include file="common/top.phtml"}
<div id="content">
{*{include file="common/sidebar.phtml"}*}
	<div id="principal" class="principal">
		{$listnews}
		{$npagination}
	</div>
	<hr class="clear" />
</div>
{include file="common/footer.phtml"}
</body>
</html>