{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content="{static_metas param=#seo_d_static_news# dynamic=false}"}
    <title>{static_metas param=#seo_t_static_news# dynamic=false}</title>
{include file="common/css.phtml"}
</head>
<body>
<div id="page">
{include file="common/top.phtml"}
<div id="content">
{include file="common/sidebar.phtml"}
	<div id="principal" class="principal">
		{$listnews}
		{$npagination}
	</div>
</div>
{include file="common/footer.phtml"}
</body>
</html>