{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content="{rewrite_metas_news type='description' param=#seo_d_static_news# level='0'}"}
    <title>{rewrite_metas_news type='title' param=#seo_t_static_news# level='0'}</title>
{include file="common/css.phtml"}
</head>
<body>
<div id="page">
{include file="common/top.phtml"}
<div id="content">
{include file="common/sidebar.phtml"}
	<div id="principal" class="principal">
		{$listnews}
		{$npagination}
	</div>
	<hr class="clear" />
</div>
{include file="common/footer.phtml"}
</body>
</html>