{include file="section/head.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'3','idmetas'=>'2','default'=>$n_title] record=$n_title}}
<title>{seo_rewrite config_param=['level'=>'3','idmetas'=>'1','default'=>$n_title] record=$n_title}</title>
{include file="section/css.phtml"}
</head>
<body id="news-record">
<div id="page" class="container">
{include file="section/header.phtml"}
    <div id="content" class="row">
    {include file="section/sidebar.phtml"}
        <div id="article" class="span9">
            <div id="article-inner" class="span8">
                <h1>{$n_title}</h1>
                <div class="span2 pull-right">
                    {$date_publish|date_format:"%d-%m-%Y"}
                    <img src="{$n_image}" alt="{$n_title}" class="rfloat" />
                </div>
                {$n_content}
            </div>
        </div>
        <div class="clear">&nbsp;</div>
    </div>
{include file="section/footer.phtml"}
</div>
{include file="section/foot.phtml"}
</body>
</html>