{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'3','idmetas'=>'2','default'=>$n_title] record=$n_title}}
    <title>{seo_rewrite config_param=['level'=>'3','idmetas'=>'1','default'=>$n_title] record=$n_title}</title>
{include file="common/css.phtml"}
</head>
<body>
<div id="page">
{include file="common/top.phtml"}
<div id="content">
{*{include file="common/sidebar.phtml"}*}
	<div id="principal" class="principal">
		<div class="sdate">
			<table>
				<tr>
					<td><span style="float:left;" class="ui-icon ui-icon-calendar"></span></td>
					<td>{$date_publish|date_format:"%d-%m-%y"}</td>
				</tr>
			</table>
		</div>
		<h1>{$n_title}</h1>
		{$n_content}
	</div>
	<hr class="clear" />
</div>
{include file="common/footer.phtml"}
</body>
</html>