{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Install processing</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-content">
					
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>