{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'0','idmetas'=>'2','default'=>#seo_d_static_plugin_contact#]}}
    <title>{seo_rewrite config_param=['level'=>'0','idmetas'=>'1','default'=>#seo_t_static_plugin_contact#]}</title>
{include file="common/css.phtml"}
</head>
<body>
<div id="page">
{include file="common/top.phtml"}
<div id="content">
{include file="common/sidebar.phtml"}
	<div id="principal" class="principal">
	<h1>{#pn_contact_forms#|firststring}</h1>
		<form id="forms-plugin-contact" method="post" action="">
		{$msg}
		<fieldset class="ui-widget ui-widget-content ui-corner-all">
		<legend class="ui-widget ui-state-highlight ui-corner-all">{#pn_contact_fields_request#|firststring}</legend>
			<table>
				<tr>
					<td class="label"><label for="nom">{#pn_contact_lastname#|firststring}* :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="nom" name="nom" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
				</tr>
				<tr>
					<td class="label"><label for="prenom">{#pn_contact_firstname#|firststring}* :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="prenom" name="prenom" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
				</tr>
				<tr>
					<td class="label"><label for="email">{#pn_contact_mail#|firststring}* :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="email" name="email" class="inputtext ui-widget-content ui-corner-all" value="" size="40" /></td>
				</tr>
				<tr>
					<td class="label"><label for="tel">{#pn_contact_phone#|firststring} :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="tel" name="tel" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
				</tr>
				<tr>
					<td class="label"><label for="adresse">{#pn_contact_address#|firststring} :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="adresse" name="adresse" class="inputtext ui-widget-content ui-corner-all" value="" size="40" /></td>
				</tr>
				<tr>
					<td class="label"><label for="programme">{#pn_contact_programme#|firststring} :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="programme" name="programme" class="inputtext ui-widget-content ui-corner-all" value="{$smarty.post.moreinfo}" size="40" /></td>
				</tr>
				<tr>
					<td class="label"><label for="message">{#pn_contact_message#|firststring} :</label></td>
				</tr>
				<tr>
					<td><textarea id="message" name="message" class="fulltext ui-widget-content ui-corner-all" rows="10" cols="50"></textarea></td>
				</tr>
				<tr>
					<td><input type="submit" class="subcontact" value="{#pn_contact_send#|firststring}" /></td>
				</tr>
			</table>
		</fieldset>
		</form>
	</div>
</div>
{include file="common/footer.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/plugins/contact/js/public.0.1.js');
});
</script>
</body>
</html>