{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'0','idmetas'=>'2','default'=>#seo_d_static_plugin_contact#]}}
    <title>{seo_rewrite config_param=['level'=>'0','idmetas'=>'1','default'=>#seo_t_static_plugin_contact#]}</title>
{include file="common/css.phtml"}
</head>
<body class="contact">
	<div id="header" class="full">
		<div class="container">
			{include file="common/top.phtml"}
		</div>
	</div>
	<div id="content" class="full">
		<div class="full-top"></div>
		<div class="full-repeat">
			<div class="container">
				<div id="contentCol" class="block w10-16 lfloat text-content">
						<ul class="ariane">
					   		<li class="first"><a href="{geturl}/{getlang}/" title="{#topmenu_home_t#|firststring}">{#topmenu_home_t#|firststring}</a></li>
							<li>></li>
							<li>{#topmenu_contact_t#|firststring}</li>
						</ul>
						<h1>{#pn_contact_forms#|firststring}</h1>
						<form id="forms-plugin-contact" method="post" action="">
						<fieldset class="ui-widget ui-widget-content ui-corner-all">
						<legend class="ui-widget ui-state-highlight ui-corner-all">{#pn_contact_fields_request#|firststring}</legend>
							<table>
								<tr>
									<td class="label"><label for="nom">{#pn_contact_lastname#|firststring}* :</label></td>
								</tr>
								<tr>
									<td>
										<input type="hidden" id="getLanguage" name="getLanguage" value="{getlang}" />
										<input type="text" id="nom" name="nom" class="inputtext ui-widget-content ui-corner-all" value="" size="20" />
									</td>
								</tr>
								<tr>
									<td class="label"><label for="prenom">{#pn_contact_firstname#|firststring}* :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="prenom" name="prenom" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
								</tr>
								<tr>
									<td class="label"><label for="email">{#pn_contact_mail#|firststring}* :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="email" name="email" class="inputtext ui-widget-content ui-corner-all" value="" size="40" /></td>
								</tr>
								<tr>
									<td class="label"><label for="tel">{#pn_contact_phone#|firststring} :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="tel" name="tel" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
								</tr>
								<tr>
									<td class="label"><label for="adresse">{#pn_contact_address#|firststring} :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="adresse" name="adresse" class="inputtext ui-widget-content ui-corner-all" value="" size="40" /></td>
								</tr>
								<tr>
									<td class="label"><label for="programme">{#pn_contact_programme#|firststring} :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="programme" name="programme" class="inputtext ui-widget-content ui-corner-all" value="{$smarty.post.moreinfo}" size="40" /></td>
								</tr>
								<tr>
									<td class="label"><label for="message">{#pn_contact_message#|firststring} :</label></td>
								</tr>
								<tr>
									<td><textarea id="message" name="message" class="fulltext ui-widget-content ui-corner-all" rows="10" cols="50"></textarea></td>
								</tr>
								<tr>
									<td><input type="submit" class="subcontact" value="{#pn_contact_send#|firststring}" /></td>
								</tr>
							</table>
						</fieldset>
						</form>
					</div>
				<div id="rightCol" class="block w6-16 lfloat last">
					{include file="common/colright.phtml"}	
				</div>
				<div class="clear">&nbsp;</div>
			</div>
		</div>
		<div class="full-bottom"></div>
	</div>
{include file="common/footer.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/plugins/contact/js/public.0.2.js',function(){
		if (typeof plugins_contact == "undefined") 
		{
		  console.log("plugins_contact is not defined");
		}else{
			plugins_contact.run(iso);
		}
	});
});
</script>
</body>
</html>