{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'1','idmetas'=>'2','default'=>$clibelle] category=$clibelle}}
    <title>{seo_rewrite config_param=['level'=>'1','idmetas'=>'1','default'=>$clibelle]  category=$clibelle}</title>
{include file="common/css.phtml"}
</head>
<body class="catalog cat">
	<div id="header" class="full">
		<div class="container">
			{include file="common/top.phtml"}
		</div>
	</div>
	<div id="content" class="full">
		<div id="contentContener" class="container">
			<div class="bg-top w16-16"></div>
				<div class="bg-repeat w16-16">	
					<div id="contentCol" class="text-content block w11-16 lfloat">
					    <ul class="ariane">
					   		<li class="first"><a href="{geturl}/{getlang}/{#topmenu_catalog_uri#}/" title="{#topmenu_catalog_t#}">{#topmenu_catalog_t#}</a></li>
							<li>></li>
							<li>{$clibelle}</li>
						</ul>          						
						<h1>{$clibelle}</h1>
						{$c_content}
						{widget_catalog_cat_load_products tposition="bottom" ui=false price=false description=true size="medium" col="2"}
						{widget_catalog_subcategory_display tposition="bottom" col="2"}
					</div>
					<div id="rightCol" class="block w5-16 lfloat last">
						{include file="common/colright.phtml"}
					</div>
				</div>
				<div class="bg-bottom w16-16"></div>
		</div>
	</div>
	{include file="common/footer.phtml"}
</body>
</html>