{include file="section/head.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'1','idmetas'=>'2','default'=>$clibelle] category=$clibelle}}
    <title>{seo_rewrite config_param=['level'=>'1','idmetas'=>'1','default'=>$clibelle]  category=$clibelle}</title>
{include file="section/css.phtml"}
</head>
<body id="catalog-cat">
<div id="page" class="container">
{include file="section/header.phtml"}
    <div id="content" class="row">
    {include file="section/sidebar.phtml"}
        <div id="article" class="span9">
            <div id="article-inner" class="span8">
                <h1>{$clibelle}</h1>
                {$c_content}
                {widget_catalog_display}
                {widget_catalog_display
                    dataSelect=[
                    'level' =>  'product'
                    ]
                    structureHTML = [
                        'item' => [
                            'htmlBefore' => '<li class="span8"><div class="thumbnail">',
                            'htmlAfter' => '</div></div></li>'
                            ]
                    ]
                }
            </div>
        </div>
        <div class="clear">&nbsp;</div>
    </div>
{include file="section/footer.phtml"}
</div>
{include file="section/foot.phtml"}
</body>
</html>