{include file="common/header.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'3','idmetas'=>'2','default'=>''] category=$category subcategory=$subcategory record=$titlecatalog}}
    <title>{seo_rewrite config_param=['level'=>'3','idmetas'=>'1','default'=>''] category=$category subcategory=$subcategory record=$titlecatalog}</title>
{include file="common/css.phtml"}
</head>
<body>
	<div id="header" class="full">
		<div class="container">
			{include file="common/top.phtml"}
		</div>
	</div>
	<div id="content" class="full">
		<div id="contentContener" class="container">
			<div class="bg-top w16-16"></div>
				<div class="bg-repeat w16-16">	
					<div id="contentCol" class="text-content block w11-16 lfloat">			
				    	<ul class="ariane">
				   			<li class="first"><a href="{geturl}/{getlang}/{#topmenu_catalog_uri#}/" title="{#topmenu_catalog_t#}">Catalogue</a></li>
					    	<li>></li>
					    	<li><a href="{$uri_cat}" title="{#catalog_nav_cat#} {$category}">{$category}</a></li>
					    	<li>></li>
					    	{if $subcategory eq !null}
					    		<li><a href="{$uri_subcat}" title="{#catalog_nav_cat#} {$subcategory}">{$subcategory}</a></li>
					    		<li>></li>
					    	{/if}
					    	<li>{$titlecatalog}</li>
					    </ul>    	
				    	<span class="date rfloat">Ajouté le {$date_catalog|date_format:"%d-%m-%y"}</span>		

						<h1>{$titlecatalog}</h1>
						{$smarty.get.idproduct}
						<div id="product-img" class="block w4-16 rfloat last bg dark">
							{$imgcatalog}
							<p class="title">Intéressé par {$titlecatalog} ?</p>
							<form action="{geturl}/{getlang}/magixmod/contact/" method="post">
							<p>
								<input type="hidden" name="moreinfo" value="{$titlecatalog}"/>
								<input id="more-info" type="image" src="{geturl}/skin/{template}/img/catalog/more-product.png" />
							</p>
							</form>						
						</div>
						<span class="price">{$price} €</span>
						{$desccatalog}
						<div class="clear"></div>
						<div id="galery" class="block w11-32 lfloat">
							<p class="title">Photos</p>
							{widget_catalog_microgalery type="imagebox" ui=true col="3"}
						</div>
						<div id="rel-product" class="block w11-32 lfloat last">
							<p class="title">Voir aussi</p>
							{widget_catalog_rel_product idcatalog=$idcatalog ui=false description=true contentlength="124" size="medium" tposition="bottom"}
						</div>
						<div class="clear"></div>					
					</div>
					<div id="rightCol" class="block w5-16 lfloat last">
						{include file="common/colright.phtml"}
					</div>
				</div>
				<div class="bg-bottom w16-16"></div>
		</div>
	</div>
	{include file="common/footer.phtml"}
</body>
</html>