{include file="section/head.phtml" section="prepend"}
{headmeta meta="description" content={seo_rewrite config_param=['level'=>'2','idmetas'=>'2','default'=>$slibelle] category=$clibelle subcategory=$slibelle}}
    <title>{seo_rewrite config_param=['level'=>'2','idmetas'=>'1','default'=>$slibelle] category=$clibelle subcategory=$slibelle}</title>
{include file="section/css.phtml"}
</head>
<body id="catalog-subcat">
<div id="page" class="container">
{include file="section/header.phtml"}
    <div id="content" class="row">
    {include file="section/sidebar.phtml"}
        <div id="article" class="span9">
            <div id="article-inner" class="span8">
            <h1>{$slibelle}</h1>
            {$s_content}
            {widget_catalog_display
                structureHTML = [
                    'container' => [
                        'htmlBefore' => '<h2>Produits</h2><ul class="thumbnails">',
                        'htmlAfter' => '</ul>'
                    ],
                    'item' => [
                        'htmlBefore' => '<li class="span9"><div class="thumbnail">',
                        'htmlAfter' => '</div></div></li>'
                    ],
                    'img' => [
                        'classLink' => 'none'
                    ],
                    'name' => [
                        'htmlBefore' => '<div class="caption"> <h3>',
                        'classLink' => 'name',
                        'htmlAfter' => '</h3>'
                    ],
                    'descr' => [
                        'htmlBefore' => '<p>',
                        'htmlAfter' => '</p>'
                    ],
                    'price' => [
                        'htmlBefore' => '<a class="btn" href="|#url#|" title="Voir le produit"> Voir le produit: ',
                        'htmlAfter' => '</a>'
                    ]
                ]
            }
            </div>
        </div>
        <div class="clear">&nbsp;</div>
    </div>
{include file="section/footer.phtml"}
</div>
{include file="section/foot.phtml"}
</body>
</html>