<form id="forms_home_add" method="post" action="">
    <p class="control-group">
        <label for="subject">{#label_title#|ucfirst} *</label>
        <input type="text" placeholder="{#label_title#|ucfirst}" class="input-large" id="subject" name="subject" value="" size="50" />
    </p>
    <p class="control-group">
        <label for="idlang">{#label_language#|ucfirst} *</label>
        {$select_lang}
    </p>
</form>