<form id="forms_home_edit" method="post" action="">
    <p class="controls">
        <label for="subject">{#label_title#|ucfirst} *:</label>
        <input type="text" placeholder="Nom de la page" class="input-xlarge" id="subject" name="subject" value="{$subject}" size="50" />
    </p>
    <p class="controls">
        <label for="iso">ISO:</label>
        <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
    </p>
    <p class="controls">
        <label for="content" class="inlinelabel">{#label_content#|ucfirst} :</label>
        <textarea name="content" id="content" class="mceEditor">{$content}</textarea>
    </p>
    <p>
        <a href="#metas" class="btn showit">
            <span class="icon-plus"></span> {#display_metas#|ucfirst}
        </a>
    </p>
    <div class="collapse-item" id="metas">
        <p class="controls">
            <label for="metatitle">{#label_title#|ucfirst} :</label>
            <textarea class="span6" id="metatitle" name="metatitle" cols="70" rows="3">{$metatitle}</textarea>
        </p>
        <p class="controls">
            <label for="metadescription">Description :</label>
            <textarea class="span6" id="metadescription" name="metadescription" cols="70" rows="3">{$metadescription}</textarea>
        </p>
    </div>
    <p>
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>