<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">Langues</a></li>
                    <li><a href="/{baseadmin}/lang.php">Statistiques</a></li>
                    <li><a href="/{baseadmin}/lang.php?action=list">Liste des langues</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>