<form id="forms-add-lang" method="post" action="" style="margin-left:10px;">
	<fieldset>
		<table>
			<tr>
				<td class="label"><label for="iso" class="inlinelabel">ISO *:</label></td>
			</tr>
			<tr>
				<td><input type="text" id="iso" name="iso" class="inputtext ui-corner-all" value="" size="3" /></td>
			</tr>
			<tr>
				<td class="label"><label for="language" class="inlinelabel">Nom *:</label></td>
			</tr>
			<tr>
				<td><input type="text" id="language" name="language" class="inputtext ui-corner-all" value="" size="20" /></td>
			</tr>
			<tr>
				<td>
					Langue par défaut&nbsp;<input type="checkbox" id="default_lang" name="default_lang" value="1" />
				</td>
			</tr>
		</table>			
	</fieldset>
	<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
</form>