<form id="forms-update-lang" method="post" action="" style="margin-left:10px;">
	<fieldset>
		<table>
			<tr>
				<td class="label"><label for="iso" class="inlinelabel">ISO *:</label></td>
			</tr>
			<tr>
				<td>
				<input type="hidden" id="idlang" name="idlang" value="{$idlang}" />
				{$iso}
				</td>
			</tr>
			<tr>
				<td class="label"><label for="language" class="inlinelabel">Nom *:</label></td>
			</tr>
			<tr>
				<td><input type="text" id="language" name="language" class="inputtext ui-corner-all" value="{$language}" size="20" /></td>
			</tr>
			<tr>
				<td class="label"><label for="default_lang" class="inlinelabel">Langue par défaut :</label></td>
			</tr>
			<tr>
				<td>
				{if $default_lang eq '1'}
					Non <input type="radio" id="default_lang_off" name="default_lang" value="0" />
					Oui <input type="radio" id="default_lang_on" name="default_lang" value="1" checked="checked" />
				{else}
					Non <input type="radio" id="default_lang_off" name="default_lang" value="0" checked="checked" />
					Oui <input type="radio" id="default_lang_on" name="default_lang" value="1" />
				{/if}
				</td>
			</tr>
		</table>			
	</fieldset>
	<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
</form>