<form action="" method="post" id="form-assign-tagnews" class="ui-corner-all" style="padding:5px;margin:5px 10px;"> 
	<table>
		<tr>
			<td>
				<label for="name_tag">Ajouter un tag:</label>
			</td>
		</tr>
		<tr>
			<td>
				<input type="text" id="name_tag" name="name_tag" class="inputtext ui-corner-all" size="35" value="" />
				<input type="submit" value="Envoyer" />
			</td>
		</tr>
	</table>
</form>
<div id="list_assign_tagnews" class="ui-widget-content ui-corner-all"></div>
