<form id="forms_googletools_webmaster_edit" class="forms-googletools form-horizontal form-inline" method="post" action="">
    <p>
        <label for="webmaster">Webmaster</label>
    </p>
    <p>
        <input type="text" class="input-xlarge" id="webmaster" name="webmaster" size="30" value="{$webmaster}" />
        <input type="submit" class="btn btn-primary" value="Envoyer" />
    </p>
</form>
<form id="forms_googletools_analytics_edit" class="forms-googletools form-horizontal form-inline" method="post" action="">
    <p>
        <label for="webmaster">Analytics</label>
    </p>
    <p>
        <input type="text" class="input-xlarge" id="analytics" name="analytics" size="30" value="{$analytics}" />
        <input type="submit" class="btn btn-primary" value="Envoyer" />
    </p>
</form>