<div class="mc-info clearfix">
    <div class="span7 alert alert-info">
        <span class="icon-info-sign"></span> {#alert_info_analytics#}
    </div>
</div>
<form id="forms_googletools_analytics_edit" class="forms-googletools form-horizontal form-inline" method="post" action="">
    <p>
        <label for="analytics">Profil Analytics:</label>
    </p>
    <p>
        <input type="text" class="input-xlarge" id="analytics" name="analytics" size="30" value="{$analytics}" />
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>
<div class="mc-info clearfix">
    <div class="span7 alert alert-info">
        <span class="icon-info-sign"></span> {#alert_info_webmaster_tools#}
    </div>
</div>
<form id="forms_googletools_webmaster_edit" class="forms-googletools form-horizontal form-inline" method="post" action="">
    <p>
        <label for="webmaster">Profil Webmaster:</label>
    </p>
    <p>
        <input type="text" class="input-xlarge" id="webmaster" name="webmaster" size="30" value="{$webmaster}" />
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>
<div class="mc-info clearfix">
    <div class="span7 alert alert-info">
        <span class="icon-info-sign"></span> {#alert_info_googleplus#}
    </div>
</div>
<form id="forms_googletools_plus_edit" class="forms-googletools form-horizontal form-inline" method="post" action="">
    <p>
        <label for="googleplus">Profil Google plus:</label>
    </p>
    <p>
        <input type="text" class="input-xxlarge" id="googleplus" name="googleplus" size="30" value="{$googleplus}" />
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>
<form id="forms_robots_edit" class="forms-googletools form-horizontal form-inline" method="post" action="">
    <p>
        <label for="googleplus">Robots:</label>
    </p>
    <p>
        {$select_robots}
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>