{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
<div class="container-narrow">
    {include file="section/top.phtml"}
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li>
                <a href="/install/index.php">{#start#}</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/analysis.php">{#analysis#}</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/config.php">{#configuration#}</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/database.php">{#database#}</a> <span class="divider">/</span>
            </li>
            <li>
                <span class="active">{#administrator#}</span>
            </li>
        </ul>
        <div class="mc-message clearfix"></div>
        {include file="user/forms/add.phtml"}
        <ul class="pager">
            <li class="previous">
                <a href="/install/database.php">&larr; Précédent</a>
            </li>
            <li class="next">
                <a href="/install/clear.php">Suivant &rarr;</a>
            </li>
        </ul>
    </div>
    {include file="section/footer.phtml"}
</div>
{include file="section/js.phtml"}
{include file="user/section/js.phtml"}
</body>
</html>