{include file="section/head.phtml"}
<title>Magix CMS | Login</title>
</head>
<body class="module-login">
<div class="container-fluid">
    <div class="box-login">
        <h2>
            <img src="/{baseadmin}/template/img/logo-magix_cms.png" />
        </h2>
        <form id="forms-log" method="post" action="{geturl}/admin/login.php">
            <p class="input-prepend">
                    <span class="add-on">
                        <span class="icon-envelope"></span>
                    </span>
                <input type="text" class="input-large" placeholder="Indiquer le login" id="acmail" name="acmail" value="" />
            </p>
            <p class="input-prepend">
                    <span class="add-on">
                        <span class="icon-key"></span>
                    </span>
                <input type="password" class="input-large" placeholder="Indiquer le password" id="acpass" name="acpass" value="" />
            </p>
            <p class="input-btn">
                <input type="hidden" id="hashtoken" name="hashtoken" value="{$hashpass}" />
                <input type="submit" class="btn btn-default btn-primary" value="Connexion" />
            </p>
        </form>
    </div>
</div>
{*{include file="login/internal/js.phtml"}*}
</body>
</html>