{include file="section/head.phtml"}
<title>Test</title>
</head>
<body class="module-login">
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span4 box-login">
            <h1>Connexion</h1>
            <form id="forms-log" method="post" action="{geturl}/admin/login.php">
                <p class="input-prepend">
                    <span class="add-on">
                        <span class="icon-envelope"></span>
                    </span>
                    <input type="text" class="input-xlarge" placeholder="Indiquer le login" id="acmail" name="acmail" value="" />
                </p>
                <p class="input-prepend">
                    <span class="add-on">
                        <span class="icon-key"></span>
                    </span>
                    <input type="password" class="input-xlarge" placeholder="Indiquer le password" id="acpass" name="acpass" value="" />
                </p>
                <p>
                    <input type="hidden" id="hashtoken" name="hashtoken" value="{$hashpass}" />
                    <input type="submit" class="btn btn-primary" value="Connexion" />
                </p>
            </form>
        </div>
    </div>
</div>
{*{include file="login/internal/js.phtml"}*}
</body>
</html>