{include file="section/head.phtml"}
<title>Magix CMS | Login</title>
</head>
<body class="module-login">
<div class="container-fluid">
    <div class="box-login">
        <h2 class="text-center">
            <img src="/{baseadmin}/template/img/logo-magix_cms.png" alt="Magix CMS" />
        </h2>
        {$login_message}
        <form id="forms-log" method="post" action="{geturl}/{baseadmin}/login.php">
            <p class="input-prepend">
                <span class="add-on">
                    <span class="icon-envelope"></span>
                </span>
                <input type="text" class="input-large" placeholder="{#placeholder_login#}" id="acmail" name="acmail" value="" />
            </p>
            <p class="input-prepend">
                <span class="add-on">
                    <span class="icon-key"></span>
                </span>
                <input type="password" class="input-large" placeholder="{#placeholder_password#}" id="acpass" name="acpass" value="" />
            </p>
            <p>
                <input type="hidden" id="hashtoken" name="hashtoken" value="{$hashpass}" />
                <input type="submit" class="btn btn-default btn-primary" value="{#login#}" />
            </p>
        </form>
    </div>
</div>
{include file="login/section/js.phtml"}
</body>
</html>