<form id="forms_cms_edit" method="post" action="">
    <p>
        <label for="cmslink">URL</label>
        <input type="text" class="input-xxlarge" id="cmslink" readonly="readonly" size="50" value="" />
    </p>
    <p class="pull-left">
        <label for="iso">ISO</label>
        <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
    </p>
    <p class="controls-row offset1 input-append">
        <label for="uri_page">{#url_rewriting#|ucfirst}</label>
        <input type="text" class="input-xlarge" id="uri_page" name="uri_page" readonly="readonly" size="30" value="{$uri_page}" />
        <a class="unlocked" href="#">
            <span class="add-on icon-lock"></span>
        </a>
    </p>
    <div class="clearfix"></div>
    <p>
        <label for="title_page">{#label_title#|ucfirst} :</label>
        <input type="text" class="input-xlarge" id="title_page" name="title_page" value="{$title_page}" size="50" />
    </p>
    <p>
        <label for="content_page" class="inlinelabel">{#label_content#|ucfirst} :</label>
        <textarea name="content_page" id="content_page" class="mceEditor">{$content_page}</textarea>
    </p>
    <p>
        <a href="#metas" class="btn view-metas">
            <span class="icon-plus"></span> {#display_metas#|ucfirst}
        </a>
    </p>
    <div class="collapse-metas" id="metas">
        <p>
            <label for="seo_title_page">{#label_title#|ucfirst} :</label>
            <textarea class="span6" id="seo_title_page" name="seo_title_page" cols="70" rows="3">{$seo_title_page}</textarea>
        </p>
        <p>
            <label for="seo_desc_page">Description :</label>
            <textarea class="span6" id="seo_desc_page" name="seo_desc_page" cols="70" rows="3">{$seo_desc_page}</textarea>
        </p>
    </div>
    <p>
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>