<form id="forms_cms_move" method="post" action="">
    <p class="pull-left">
        <label for="iso">ISO :</label>
        <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
    </p>
    <p class="offset1">
        <label for="title_page">{#label_title#|ucfirst} :</label>
        <input type="text" class="input-xlarge" id="title_page" name="title_page" disabled="disabled" readonly="readonly" value="{$title_page}" size="50" />
    </p>
    <div class="clearfix"></div>
    <p>
        <label for="uri_page">URL :</label>
        <input type="text" class="input-xlarge" id="uri_page" name="uri_page" readonly="readonly" size="30" value="{$uri_page}" />
    </p>
    <p>
        {$selectlang}
    </p>
    <p>
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>