{include file="cplugin/layout_up.phtml"}
<div class="dashboard ui-widget-content ui-corner-all">
<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>{$pluginName}</div>
	<div class="dashboard-content">
		<div class="column">
			<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span>About</div>
				<div class="dashboard-content">
					<div style="margin-left:10px;padding:5px;">
					<ul>
						<li>Version 2.0</li>
						<li>Author: Gerits Aurelien</li>
						<li>Website: <a style="text-decoration:underline;" class="targetblank" href="http://magix-cjquery.com">magix cjquery</a></li>
						<li>Support du plugin: <a style="text-decoration:underline;" class="targetblank" href="http://forum.logiciel-referencement-professionnel.com/plugins-f5.html">Forum plugins</a></li>
					</ul>
					</div>
				</div>
			</div>
			<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Ajouter un utilisateur de contact</div>
				<div class="dashboard-content">
					<form method="post" id="forms-plugins-contact" action="" style="margin-left:10px;">
					<fieldset>
						<table>
							{$selectusers}
							{$selectlang}
						</table>		
						<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
					</fieldset>
					</form>
				</div>
			</div>
		</div>
		<div class="column">
			<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Les utilisateurs</div>
				<div class="dashboard-content">
					{$list_member_admin}
				</div>
			</div>
			<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Les contacts</div>
				<div class="dashboard-content">
					{$list_member_contact}
				</div>
			</div>
		</div>
	</div>		
</div>
{include file="cplugin/layout_down.phtml"}