{magixmin}
{literal}
<script type="text/javascript">	
$(function() {
	 $("#forms-plugins-contact").submit(function(){
		$.notice({
			ntype: "ajaxsubmit",
    		delay: 2800,
    		dom: this,
    		uri: '/admin/plugins.php?name=contact&add',
    		typesend: 'post',
    		resetform:false,
    		time:2,
    		reloadhtml:true
		});
		return false; 
	});
	 /**
     * Requête ajax pour la suppression des contacts
     */
	$('.d-plugins-contact').click(function (){
		var lg = $(this).attr("title");
		$("#dialog").dialog({
			bgiframe: true,
			resizable: false,
			height:140,
			modal: true,
			title: 'Supprimé ce contact',
			overlay: {
				backgroundColor: '#000',
				opacity: 0.5
			},
			buttons: {
				'Delete item': function() {
					$(this).dialog('close');
					$.notice({
						ntype: "ajax",
			    		uri:  "/admin/plugins.php?name=contact&dcontact="+lg,
			    		typesend: 'get',
			    		time:2,
			    		reloadhtml:true
					});
				},
				Cancel: function() {
					$(this).dialog('close');
				}
			}
		});
	 });
});
</script>
{/literal}
{/magixmin}