{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="plugins-contact">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    {include file="nav.phtml"}
                    <h1>{#h1_listing_contact#}</h1>
                    {include file="section/tab.phtml"}
                    <p>
                        <a class="btn btn-primary" href="#" id="open-add">
                            <span class="icon-plus"></span> {#add_contact#}
                        </a>
                    </p>
                    <div class="mc-message clearfix"></div>
                    <div id="list_contact"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="forms-add" class="hide" title="Ajouter un contact">
{include file="forms/add.phtml"}
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="js.phtml"}
</body>
</html>