<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">Contact</a></li>
                    <li><a href="{$pluginUrl}">{#statistics#}</a></li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">{#languages#} <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        {foreach $array_lang as $key => $value nocache}
                            <li>
                                <a href="{$pluginUrl}&amp;getlang={$key}&amp;action=list">
                                    {$value|upper}
                                </a>
                            </li>
                        {/foreach}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>