{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Dashboard</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
					<div class="dashboard-content">
					{if $perms <= 2}
					{$viewmetas}
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
					<div class="dashboard-content">
					{if $rewritenews eq 1 AND $perms eq 1}
					<form id="forms-config-rewrite" method="post" action="{geturl}/admin/dashboard/configuration/metasrewrite/edit/{$smarty.get.edit}/" style="margin-left:10px;">
					{$msg}
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="phrase1" class="inlinelabel">Phrase :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="phrase1" name="phrase1" class="inputtext ui-corner-all" value="{$phrase}" size="50" /></td>
								</tr>
								<tr>
									<td class="label"><label for="phrase2" class="inlinelabel">Phrase2 :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="phrase2" name="phrase2" class="inputtext ui-corner-all" value="{$phrase2}" size="50" /></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="phrase3" class="inlinelabel">Phrase3 :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="phrase3" name="phrase3" class="inputtext ui-corner-all" value="{$phrase3}" size="50" /></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{if $idlang != 0}
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idlang" name="idlang" value="{$idlang}" />
									<input type="text" disabled="disabled" readonly="readonly" id="codelang" name="codelang" class="inputdisabled ui-corner-all" value="{$codelang}" size="5" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{/if}
								<tr>
									<td class="label"><label for="idconfig" class="inlinelabel">Module :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idconfig" name="idconfig" value="{$idconfig}" />
									<input type="text" disabled="disabled" readonly="readonly" id="module" name="module" class="inputdisabled ui-corner-all" value="{$module}" size="20" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="level" class="inlinelabel">Niveau :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="level" name="level" value="{$level}" />
									<input type="text" disabled="disabled" readonly="readonly" id="hight" name="hight" class="inputdisabled ui-corner-all" value="{$level}" size="5" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="label"><label for="idmetas" class="inlinelabel">Métas :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idmetas" name="idmetas" value="{$idmetas}" />
									{if $idmetas eq 1}
									<input type="text" disabled="disabled" readonly="readonly" id="metatype" name="metatype" class="inputdisabled ui-corner-all" value="TITLE" size="20" />
									{elseif $idmetas eq 2}
									<input type="text" disabled="disabled" readonly="readonly" id="metatype" name="metatype" class="inputdisabled ui-corner-all" value="DESCRIPTION" size="20" />
									{/if}
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" name="snom" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
					</form>
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{include file="common/javascript.phtml"}
</body>
</html>