{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all">Les éditeurs</div>
					<div class="dashboard-widget-content">
						<div id="vieweditor">
							<div class="list-editor ui-widget-content{if $editor eq 'tinymce'} ui-state-highlight{else} ui-state-disabled{/if}">
								<div class="title-editor ui-widget-header"><div class="editor-name">TinyMCE</div></div>
								<div class="img-editor">
									<a title="tinymce" href="#"><img src="/framework/img/editors/tinymce.png" alt="tinymce" /></a>
								</div>
								{if $editor eq 'tinymce'}
								<div class="editor-info">
									<form class="forms-config" method="post" action="" id="manager-editor-settings">
									<h4>Gestionnaire de fichiers</h4>
									{$list_manager_setting}
									</form>
								</div>
								{/if}
							</div>
							<div class="list-editor ui-widget-content{if $editor eq 'ckeditor'} ui-state-highlight{else} ui-state-disabled{/if}">
								<div class="title-editor ui-widget-header"><div class="editor-name">Ckeditor</div></div>
								<div class="img-editor">
									<a title="ckeditor" href="#"><img src="/framework/img/editors/ckeditor.png" alt="ckeditor" /></a>
								</div>
							</div>
							<div class="clearleft"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jsettingeditor.0.1.min.js',function(){
		if (typeof ns_jsettingeditor == "undefined") {
		  console.log("ns_jsettingeditor is not defined");
		}else{
			ns_jsettingeditor._loadingConfig();
			ns_jsettingeditor._updateEditor();
			ns_jsettingeditor._updateSubConfig();
		}
	});
});
</script>
</body>
</html>