{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
					<div class="dashboard-content">
					{if $rewritenews eq 1 AND $perms eq 1}
					<form id="forms-config-rewrite-update" method="post" action="" style="margin-left:10px;">
					{$msg}
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="strrewrite" class="inlinelabel">Phrase :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idrewrite" value="{$smarty.get.edit}" />
									<textarea id="strrewrite" name="strrewrite" class="ui-input ui-widget-content ui-corner-all" cols="48" rows="3">{$strrewrite}</textarea></td>
									<td>
									<ul class="seotags">
										<li><div id="add-category" class="addseo"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>&nbsp;Catégorie</div></li>
										<li><div id="add-subcategory" class="addseo"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>&nbsp;Sous catégorie</div></li>
										<li><div id="add-product" class="addseo"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>&nbsp;Articles</div></li>
									</ul>
									</td>
								</tr>
								{if $idlang != 0}
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idlang" name="idlang" value="{$idlang}" />
									<input type="text" disabled="disabled" readonly="readonly" id="codelang" name="codelang" class="inputdisabled ui-corner-all" value="{$codelang}" size="5" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{/if}
								<tr>
									<td class="label"><label for="idconfig" class="inlinelabel">Module :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idconfig" name="idconfig" value="{$idconfig}" />
									<input type="text" disabled="disabled" readonly="readonly" id="module" name="module" class="inputdisabled ui-corner-all" value="{$module}" size="20" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="level" class="inlinelabel">Niveau :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="level" name="level" value="{$level}" />
									<input type="text" disabled="disabled" readonly="readonly" id="hight" name="hight" class="inputdisabled ui-corner-all" value="{$level}" size="5" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="label"><label for="idmetas" class="inlinelabel">Métas :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idmetas" name="idmetas" value="{$idmetas}" />
									{if $idmetas eq 1}
									<input type="text" disabled="disabled" readonly="readonly" id="metatype" name="metatype" class="inputdisabled ui-corner-all" value="TITLE" size="20" />
									{elseif $idmetas eq 2}
									<input type="text" disabled="disabled" readonly="readonly" id="metatype" name="metatype" class="inputdisabled ui-corner-all" value="DESCRIPTION" size="20" />
									{/if}
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" /></div>
					</form>
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
				</div>
				<div class="column">
					<div class="dashboard ui-widget-content ui-corner-all">
						<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
						<div class="dashboard-content">
						{if $perms <= 2}
						{$viewmetas}
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{literal}
{magixmin}
<script type="text/javascript">
$(function(){
	/**
	 * Ajoute les éléments pour la réécriture des métas
	 */
	$.getScript('/framework/js/tools/jquery.a-tools-1.5.2.min.js', function() {
		$("#add-category").bind("click",function (){
			var myContent = $("#strrewrite").val();
			//$("#strrewrite").val(myContent + "[[category]]").focus();
			$("#strrewrite").insertAtCaretPos("[[category]]");
	        return false;
		});
		$("#add-subcategory").bind("click",function (){
			var myContent = $("#strrewrite").val();
	        //$("#strrewrite").val(myContent + "[[subcategory]]").focus();
			$("#strrewrite").insertAtCaretPos("[[subcategory]]");
	        return false;
		});
		$("#add-product").bind("click",function (){
			var myContent = $("#strrewrite").val();
	        //$("#strrewrite").val(myContent + "[[record]]").focus();
			$("#strrewrite").insertAtCaretPos("[[record]]");
	        return false;
		});
	});
});
</script>
{/magixmin}
{/literal}
</body>
</html>