{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				{if {admin_level_config config_param=['module'=>'catalog','allow_level'=>'*']} eq true}
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-cart"></span>Tailles des images catalogue</div>
						<div class="dashboard-widget-content">
							<div style="margin:5px 0;">{$img_size_forms_catalog}</div>
						</div>
					</div>
				</div>
				{/if}
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-news"></span>Tailles des images des news</div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'news','allow_level'=>'*']} eq true}
							<div style="margin:5px 0;">{$img_size_forms_news}</div>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
					{if $img_size_forms_plugins != null}
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-plugin"></span>Tailles des images des plugins</div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'plugins','allow_level'=>'*']} eq true}
							<div style="margin:5px 0;">{$img_size_forms_plugins}</div>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
					{/if}
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jsettingimage.0.1.min.js',function(){
		if (typeof ns_jsettingimage == "undefined") {
		  console.log("ns_jsettingimage is not defined");
		}else{
			ns_jsettingimage._configUpdateId();
		}
	});
});
</script>
</body>
</html>