{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-gear"></span>Configuration global</div>
					<div class="dashboard-content">
					{if $perms <= 2}
						<div id="tabsFormsConfig">
						<ul>
							<li><a href="#tabs-1">Paramètres global</a></li>
							<li><a href="#tabs-2">Réecriture métas</a></li>
							<li><a href="#tabs-3">Limitation</a></li>
						</ul>
						<div id="tabs-1">
						<form class="forms-config" method="post" action="" id="global-config-lang">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">Langue :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="configlang" {if $configlang eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="configlang" {if $configlang eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						<form class="forms-config" method="post" action="" id="global-config-news">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">News :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="confignews" {if $confignews eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="confignews" {if $confignews eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						<form class="forms-config" method="post" action="" id="global-config-cms">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">CMS :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="configcms" {if $configcms eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="configcms" {if $configcms eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						<form class="forms-config" method="post" action="" id="global-config-catalog">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">Catalogue :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="configcatalog" {if $configcatalog eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="configcatalog" {if $configcatalog eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						<form class="forms-config" method="post" action="" id="global-config-microgalery">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">Micro galery catalogue :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="configmicrogalery" {if $configmicrogalery eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="configmicrogalery" {if $configmicrogalery eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						<form class="forms-config" method="post" action="" id="global-config-forms">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">Formulaires :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="configforms" {if $configforms eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="configforms" {if $configforms eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						</div>
						<div id="tabs-2">
						<form class="forms-config" method="post" action="" id="global-rewritenews">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">News :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="rewritenews" {if $rewritenews eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="rewritenews" {if $rewritenews eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						<form class="forms-config" method="post" action="" id="global-rewritecms">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">CMS :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="rewritecms" {if $rewritecms eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="rewritecms" {if $rewritecms eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						<form class="forms-config" method="post" action="" id="global-rewritecatalog">
							<fieldset>
								<table>
									<tr>
										<td style="width:150px;">Catalogue :</td>
										<td style="width:80px;">
											Activer <input type="radio" name="rewritecatalog" {if $rewritecatalog eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="rewritecatalog" {if $rewritecatalog eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
								</table>
							</fieldset>
						</form>
						</div>
						<div id="tabs-3">
							<form class="forms-config" method="post" action="" id="limited-cms-module">
								<fieldset>
									<table>
										<tr>
											<td style="width:150px;">Nombre de page CMS :</td>
											<td style="width:80px;">
												<input type="hidden" name="idconfig" id="idconfig" value="{$idconfig}" size="4" />
												<input type="text" name="number" class="spin inputtext" id="cmsnumber" value="{$numbcmspage}" size="4" />
											</td>
											<td><input type="button" id="snumbCms" name="snumbCms" class="ud-button ui-state-default ui-corner-all" value="update" /></td>
										</tr>
									</table>
								</fieldset>
							</form>
						</div>
						</div>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{include file="common/javascript.phtml"}
</body>
</html>