{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-gear"></span>Configuration globale</div>
					<div class="dashboard-content">
					{if $perms <= 2}
						<div id="tabsFormsConfig">
						<ul>
							<li><a href="#tabs-1">Paramètres globaux</a></li>
							{*<li><a href="#tabs-2">Réecriture métas</a></li>*}
							<li><a href="#tabs-2">Limitation</a></li>
							<li><a href="#tabs-3">Editeurs wysiwyg</a></li>
						</ul>
						<div id="tabs-1">
						{include file="config/forms/tabs1.phtml"}
						</div>
						<div id="tabs-2" class="ui-tabs ui-tabs-hide">
							<form class="forms-config" method="post" action="" id="limited-cms-module">
								<fieldset>
								<p>
									<label>Nombre de page CMS :</label>
									<input type="hidden" name="idconfig" id="idconfig" value="{$idconfig}" size="4" />
									<input type="text" name="number" class="spin inputtext" id="cmsnumber" value="{$numbcmspage}" size="4" />
									<input type="button" id="snumbCms" name="snumbCms" class="btn-decoration" value="update" />
								</p>
								</fieldset>
							</form>
						</div>
						<div id="tabs-3" class="ui-tabs ui-tabs-hide">
							<div id="vieweditor">
								<div class="list-editor ui-widget-content{if $editor eq 'tinymce'} ui-state-highlight{else} ui-state-disabled{/if}">
									<div class="title-editor ui-widget-header"><div class="editor-name">TinyMCE</div></div>
									<div class="img-editor">
										<a title="tinymce" href="#"><img src="/framework/img/editors/tinymce.png" alt="tinymce" /></a>
									</div>
									{if $editor eq 'tinymce'}
									<div class="editor-info">
										<form class="forms-config" method="post" action="" id="manager-editor-settings">
										<h4>Gestionnaire de fichiers</h4>
										{$list_manager_setting}
										</form>
									</div>
									{/if}
								</div>
								<div class="list-editor ui-widget-content{if $editor eq 'ckeditor'} ui-state-highlight{else} ui-state-disabled{/if}">
									<div class="title-editor ui-widget-header"><div class="editor-name">Ckeditor</div></div>
									<div class="img-editor">
										<a title="ckeditor" href="#"><img src="/framework/img/editors/ckeditor.png" alt="ckeditor" /></a>
									</div>
								</div>
								<div class="clearleft"></div>
							</div>
						</div>
						</div>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/jsettingconfig.1.0.js');
});
</script>
</body>
</html>