{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
					<div class="dashboard-content">
					{if $perms <= 2}
					{$viewmetas}
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
					<div class="dashboard-content">
					{if $rewritenews eq 1 AND $perms eq 1}
					<form id="forms-config-rewrite" method="post" action="{geturl}/admin/index.php?dashboard&amp;config&amp;metasrewrite" style="margin-left:10px;">
					{$msg}
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="strrewrite" class="inlinelabel">Phrase :</label></td>
								</tr>
								<tr>
									<td><textarea id="strrewrite" name="strrewrite" class="ui-input ui-widget-content ui-corner-all" cols="80" rows="2"></textarea></td>
									<td>
									<ul>
										<li><a id="add-category" href="#">Catégorie</a></li>
										<li><a id="add-subcategory" href="#">Sous catégorie</a></li>
										<li><a id="add-product" href="#">Produit</a></li>
									</ul>
									</td>
								</tr>
								{$selectlang}
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Module :</label></td>
								</tr>
								<tr>
									<td>
									{$selectseoconfig}
									</td>
								</tr>
								<tr>
									<td class="label"><label for="level" class="inlinelabel">Niveau :</label></td>
								</tr>
								<tr>
									<td>
									<select name="level" id="level" class="select">
										<option value="0">Niveau 0 ou Root</option>
										<option value="1">Niveau 1</option>
										<option value="2">Niveau 2</option>
										<option value="3">Niveau 3</option>
									</select>
									</td>
								</tr>
								<tr>
									<td class="label"><label for="idmetas" class="inlinelabel">Métas :</label></td>
								</tr>
								<tr>
									<td>
									<select id="idmetas" name="idmetas" class="select">
										<option value="1">TITLE</option>
										<option value="2">DESCRIPTION</option>
									</select>
									</td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" name="snom" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
					</form>
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{include file="common/javascript.phtml"}
</body>
</html>