{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
<div class="container-narrow">
    {include file="section/top.phtml"}
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li>
                <a href="/install/">Démarrer</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/analysis.php">Analyse</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/config.php">Configuration</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/database.php">Base de données</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/user.php">Administrateur</a> <span class="divider">/</span>
            </li>
            <li>
                <span class="active">Finalisation</span>
            </li>
        </ul>
        <div class="mc-message clearfix"></div>
        <div class="mc-info clearfix">
            <div class="span6 alert alert-info">
                <span class="icon-info-sign"></span> Dernière étape pour finaliser l'installation,
                vous serez redirigé à la fin de l'installation
            </div>
        </div>
        <a href="#" class="btn btn-large btn-block btn-primary" id="process_cache">
            <span class="icon-cog"></span> Finaliser l'installation
        </a>
        <ul class="pager">
            <li class="previous">
                <a href="/install/user.php">&larr; Précédent</a>
            </li>
        </ul>
    </div>
    {include file="section/footer.phtml"}
</div>
{include file="section/js.phtml"}
{include file="clear/section/js.phtml"}
</body>
</html>