{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open"><span class="lfloat magix-icon magix-icon-sitemap-grey"></span>Sitemap</a></div>
						<div class="dashboard-widget-content">
						<div id="reponse">{$msg}</div>
						<table class="table-widget-content">
							<thead>
							<tr>
							<th><span style="float:left;" class="magix-icon magix-icon-script"></span></th>
							<th><span style="float:left;" class="magix-icon magix-icon-document"></span></th>
							<th><div class="ui-state-highlight" style="border:none;"><span style="float:left;" class="ui-icon ui-icon-info"></span></div></th>
							</tr>
						</thead>
						<tbody>
							{if {admin_level_config config_param=['module'=>'news']} eq true}
							<tr>
								<td>News</td>
								<td>{$statnews}</td>
								<td>
									<div class="ui-state-highlight" style="border:none;">
										<span style="float:left;" class="ui-icon ui-icon-check"></span>
									</div>
								</td>
							</tr>
							{/if}
							{if {admin_level_config config_param=['module'=>'cms']} eq true}
							<tr>
								<td>CMS</td>
								<td>{$statcms}</td>
								<td>
									<div class="ui-state-highlight" style="border:none;">
										<span style="float:left;" class="ui-icon ui-icon-check"></span>
									</div>
								</td>
							</tr>
							{/if}
							{if {admin_level_config config_param=['module'=>'catalog']} eq true}
							<tr>
								<td>Catalogue</td>
								<td>{$statcatalog}</td>
								<td>
									<div class="ui-state-highlight" style="border:none;">
										<span style="float:left;" class="ui-icon ui-icon-check"></span>
									</div>
								</td>
							</tr>
							{/if}
							</tbody>
						</table>
						<table class="table-widget-content">
							<thead>
							<tr>
							<th><span style="float:left;" class="magix-icon magix-icon-plugin"></span></th>
							<th>Index</th>
							<th>Level1</th>
							<th>Level2</th>
							<th>Records</th>
							</tr>
						</thead>
						<tbody>
							{$statplugins}
						</tbody>
						</table>
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-sitemap-blue"></span>Création de sitemap</div>
						<div class="dashboard-widget-content">
						<ul class="ul-underline">
							<li><a class="create-xml-index" href="#"><span class="lfloat ui-icon ui-icon-circle-plus"></span>Sitemap Index</a></li>
							<li><a class="create-xml-url" href="#"><span class="lfloat ui-icon ui-icon-circle-plus"></span>Sitemap URL</a></li>
							<li><a class="create-xml-images" href="#"><span class="lfloat ui-icon ui-icon-circle-plus"></span>Sitemap images</a></li>
							<li><a class="pinggoogle" href="#"><span class="lfloat ui-icon ui-icon-circle-plus"></span>Pinguer google</a></li>
							<li><a class="compressping" href="#"><span class="lfloat ui-icon ui-icon-circle-plus"></span>Pinguer GZ Google</a></li>
						</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jsitemap.0.2.min.js',function(){
		if (typeof ns_jsitemap == "undefined") {
		  console.log("ns_jsitemap is not defined");
		}else{
			ns_jsitemap._createXML();
			ns_jsitemap._execPing();
		}
	});
});
</script>
</body>
</html>