<div class="span11">
{if $smarty.get.tab eq "news"}
    <h2>{#news#|ucfirst}</h2>
    {foreach $imgsize.news as $key => $value nocache}
        {if $value@first}
            <div class="row-fluid">
                {elseif ($value@iteration - 1) is div by 3}
            </div>
            <div class="row-fluid">
        {/if}
        <form class="forms-config" method="post" action="" id="si_{$value.attr_name}_{$value.config_size_attr}_{$value.type}">
            <h3>{$value.config_size_attr}: {$value.img_size_type}</h3>
            <div class="control-group">
                <div class="span3 controls pull-left">
                    <span>{#width#|ucfirst} :</span>
                    <input type="text" class="input-small spincount" name="width" value="{$value.width}" size="50" />
                </div>
                <div class="span3 controls pull-left">
                    <span>{#height#|ucfirst} :</span>
                    <input type="text" class="input-small spincount" name="height" value="{$value.height}" size="50" />
                </div>
                <div class="span4 controls pull-left">
                    <label class="radio inline">
                        <input type="radio" name="img_resizing" value="basic" {if $value.img_resizing eq 'basic'} checked="checked"{/if} />
                        Basic
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="img_resizing" value="adaptive" {if $value.img_resizing eq 'adaptive'} checked="checked"{/if} />
                        Adaptive
                    </label>
                </div>
                <p class="input-btn">
                    <input type="hidden" name="id_size_img" value="{$value.id_size_img}" />
                    <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
                </p>
            </div>
        </form>
        {if $value@last}
            </div>
        {/if}
    {/foreach}
{elseif $smarty.get.tab eq "plugins"}
    <h2>Plugins</h2>
    {if $imgsize.plugins != NULL}
    {foreach $imgsize.plugins as $key => $value nocache}
        {if $value@first}
            <div class="row-fluid">
                {elseif ($value@iteration - 1) is div by 3}
            </div>
            <div class="row-fluid">
        {/if}
        <form class="forms-config" method="post" action="" id="si_{$value.attr_name}_{$value.config_size_attr}_{$value.type}">
            <h3>{$value.config_size_attr}: {$value.img_size_type}</h3>
            <div class="control-group">
                <div class="span3 controls pull-left">
                    <span>{#width#|ucfirst} :</span>
                    <input type="text" class="input-small spincount" name="width" value="{$value.width}" size="50" />
                </div>
                <div class="span3 controls pull-left">
                    <span>{#height#|ucfirst} :</span>
                    <input type="text" class="input-small spincount" name="height" value="{$value.height}" size="50" />
                </div>
                <div class="span4 controls pull-left">
                    <label class="radio inline">
                        <input type="radio" name="img_resizing" value="basic" {if $value.img_resizing eq 'basic'} checked="checked"{/if} />
                        Basic
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="img_resizing" value="adaptive" {if $value.img_resizing eq 'adaptive'} checked="checked"{/if} />
                        Adaptive
                    </label>
                </div>
                <p class="input-btn">
                    <input type="hidden" name="id_size_img" value="{$value.id_size_img}" />
                    <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
                </p>
            </div>
        </form>
        {if $value@last}
            </div>
        {/if}
    {/foreach}
    {/if}
{else}
    <h2>{#catalog#|ucfirst}</h2>
    {foreach $imgsize.catalog as $key => $value nocache}
        {if $value@first}
            <div class="row-fluid">
                {elseif ($value@iteration - 1) is div by 3}
            </div>
        <div class="row-fluid">
        {/if}
        <form class="forms-config" method="post" action="" id="si_{$value.attr_name}_{$value.config_size_attr}_{$value.type}">
            <h3>{#$value.config_size_attr#|ucfirst}: {$value.img_size_type|ucfirst}</h3>
            <div class="control-group">
                <div class="span3 controls pull-left">
                    <span>{#width#|ucfirst} :</span>
                    <input type="text" class="input-small spincount" name="width" value="{$value.width}" size="50" />
                </div>
                <div class="span3 controls pull-left">
                    <span>{#height#|ucfirst} :</span>
                    <input type="text" class="input-small spincount" name="height" value="{$value.height}" size="50" />
                </div>
                <div class="span4 controls pull-left">
                    <label class="radio inline">
                        <input type="radio" name="img_resizing" value="basic" {if $value.img_resizing eq 'basic'} checked="checked"{/if} />
                        Basic
                    </label>
                    <label class="radio inline">
                        <input type="radio" name="img_resizing" value="adaptive" {if $value.img_resizing eq 'adaptive'} checked="checked"{/if} />
                        Adaptive
                    </label>
                </div>
                <p class="input-btn">
                    <input type="hidden" name="id_size_img" value="{$value.id_size_img}" />
                    <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
                </p>
            </div>
        </form>
        {if $value@last}
        </div>
        {/if}
    {/foreach}
{/if}
</div>