<div class="span11">
<h2>Catalogue</h2>
{foreach $imgsize_catalog as $key => $value nocache}
    {if $value@first}
        <div class="row-fluid">
            {elseif ($value@iteration - 1) is div by 3}
        </div>
    <div class="row-fluid">
    {/if}
    <div class="span4">
    <form class="forms-config" method="post" action="" id="si_{$value.attr_name}_{$value.config_size_attr}_{$value.type}">
        <h3>{$value.config_size_attr}: {$value.img_size_type}</h3>
        <div class="control-group">
            <div class="controls">
                <span>Largeur :</span>
                <input type="text" class="input-small spincount" name="width" value="{$value.width}" size="50" />
            </div>
            <div class="controls">
                <span>Hauteur :</span>
                <input type="text" class="input-small spincount" name="height" value="{$value.height}" size="50" />
            </div>
        </div>
        <div class="controls">
            <label class="radio inline">
                <input type="radio" name="img_resizing" value="basic" {if $value.img_resizing eq 'basic'} checked="checked"{/if} />
                Basic
            </label>
            <label class="radio inline">
                <input type="radio" name="img_resizing" value="adaptive" {if $value.img_resizing eq 'adaptive'} checked="checked"{/if} />
                Adaptive
            </label>
        </div>
        <p class="input-btn">
            <input type="hidden" name="id_size_img" value="{$value.id_size_img}" />
            <input type="submit" class="btn btn-primary" value="Envoyer" />
        </p>
    </form>
    </div>
    {if $value@last}
    </div>
    {/if}
{/foreach}
</div>