<h2>Manager de fichier pour tinyMCE</h2>
<form id="forms_editor_edit" method="post" action="">
    {$select_manager}
    <p class="input-btn">
        <input type="submit" class="btn btn-primary" value="Envoyer" />
    </p>
</form>
<h2>CSS à charger dans tinyMCE</h2>
<form id="forms_editor_css_edit" method="post" action="">
    <p>
        <label for="content_css">Liens vers vos css :</label>
        <textarea class="span6" id="content_css" name="content_css" cols="70" rows="3">{$content_css}</textarea>
    </p>
    <div class="mc-info clearfix">
        <p class="span6 alert alert-info">
            <span class="icon-info-sign"></span> Séparer vos liens par une virgule sous cette forme:
            /skin/default/css/bootstrap.css,/skin/default/css/style.css</p>
    </div>
    <p class="input-btn">
        <input type="submit" class="btn btn-primary" value="Envoyer" />
    </p>
</form>