{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                {include file="catalog/section/nav.phtml"}
                    <h1>Edition du produit {$idcatalog}</h1>
                    <ul class="nav nav-tabs clearfix">
                        <li{if !$smarty.get.tab} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&action=edit&edit={$smarty.get.edit}">Texte</a>
                        </li>
                        <li{if $smarty.get.tab eq "image"} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&action=edit&edit={$smarty.get.edit}&tab=image">Image</a>
                        </li>
                    </ul>
                    <div class="mc-message clearfix"></div>
                    {include file="catalog/product/forms/edit.phtml"}
                </div>
            </div>
        </div>
    </div>
</div>
<div id="forms-add" class="hide" title="Ajouter un produit">
    {include file="catalog/product/forms/add.phtml"}
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="catalog/section/js.phtml"}
</body>
</html>