<form id="forms-lang-update" method="post" action="" style="margin-left:10px;">
	<fieldset>
	<table>
		<tr>
			<td><input type="text" name="ucodelang" id="ucodelang" class="inputtext ui-corner-all" value="{$ucodelang}" size="20" /></td>
		</tr>
		<tr>
			<td><input type="text" name="udesclang" id="udesclang" class="inputtext ui-corner-all" value="{$udesclang}" size="20" /></td>
		</tr>
		<tr>
			<td>
				Langue par défaut
				{if $udefault eq '1'}
				<input type="checkbox" id="udefault" name="udefault" checked="checked" value="1" />
				{else}
				<input type="checkbox" id="udefault" name="udefault" value="1" />
				{/if}
			</td>
		</tr>
	</table>			
	</fieldset>
</form>