{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
				<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Editer la langue: {$idlang}</div>
					<div class="dashboard-widget-content">
					{if {admin_level_config config_param=['module'=>'lang']} eq 1}
						<form id="forms-update-lang" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table>
									<tr>
										<td class="label"><label for="iso" class="inlinelabel">ISO *:</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" id="idlang" name="idlang" value="{$idlang}" />
										<input type="text" id="iso" name="iso" class="inputtext ui-corner-all" value="{$iso}" size="3" />
										</td>
									</tr>
									<tr>
										<td class="label"><label for="language" class="inlinelabel">Nom *:</label></td>
									</tr>
									<tr>
										<td><input type="text" id="language" name="language" class="inputtext ui-corner-all" value="{$language}" size="20" /></td>
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
					</div>
				</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-locale"></span>Langues</div>
						<div class="dashboard-widget-content">
						{if $configlang eq 1 AND $perms <= 2}
							<div id="list_lang"></div>
						{else}
							<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
							<span style="float:left;" class="ui-icon ui-icon-alert"></span>
								Vous n'avez pas la permission d'administrer ce module
							</div>
						{/if}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-lightbulb"></span>Statistiques</div>
						<div class="dashboard-content">
							<div id="chart-google-language"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
<div id="update-lang" title="Modifier une langue"></div>
{ajax_notify}
{include file="common/javascript.phtml"}
{script src="/min/?f=framework/js/tools/jquery.jqplot.min.js,framework/js/tools/jqplot-plugins/jqplot.barRenderer.min.js,/framework/js/tools/jqplot-plugins/jqplot.categoryAxisRenderer.min.js,framework/js/tools/jqplot-plugins/jqplot.pointLabels.min.js" type="javascript"}
<script type="text/javascript">
$.getScript('/framework/js/backend/ns/jlanguage.0.2.js',function(){
	if (typeof ns_jlanguage == "undefined") {
	  console.log("ns_jlanguage is not defined");
	}else{
		ns_jlanguage.runEdit();
	}
});
</script>
</body>
</html>