<form id="forms-lang-update" method="post" action="" style="margin-left:10px;">
	<fieldset>
	<table>
		<tr>
			<td><input type="text" name="ucodelang" id="ucodelang" class="inputtext ui-corner-all" value="{$ucodelang}" size="20" /></td>
		</tr>
		<tr>
			<td><input type="text" name="udesclang" id="udesclang" class="inputtext ui-corner-all" value="{$udesclang}" size="20" /></td>
		</tr>
	</table>			
	</fieldset>
</form>