{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-google-optimize"></span>Les outils d'analyse Google</div>
						<div class="dashboard-content">
							<div id="resultgdata"></div>
							<form id="forms-webmaster-tools" method="post" action="" style="margin-left:10px;">
								<fieldset>
									<table>
										<tr>
											<td class="label"><label for="webmaster" class="inlinelabel">Webmaster :</label></td>
										</tr>
										<tr>
											<td><input type="text" id="webmaster" name="webmaster" class="inputtext ui-corner-all" value="{$webmaster}" size="50" /></td>
											<td><input type="submit" value="envoyer" /></td>
										</tr>
									</table>			
								</fieldset>
							</form>
							<form id="forms-analytics-tools" method="post" action="" style="margin-left:10px;">
								<fieldset>
									<table>
										<tr>
											<td class="label"><label for="analytics" class="inlinelabel">Analytics :</label></td>
										</tr>
										<tr>
											<td><input type="text" id="analytics" name="analytics" class="inputtext ui-corner-all" value="{$analytics}" size="50" /></td>
											<td><input type="submit" value="envoyer" /></td>
										</tr>
									</table>			
								</fieldset>
							</form>
							<br />
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-google"></span>Google Tools</div>
						<div class="dashboard-content">
							{widget_googletools}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jgoogletools.0.2.js',function(){
		if (typeof ns_jgoogletools == "undefined") {
		  console.log("ns_jgoogletools is not defined");
		}else{
			ns_jgoogletools.run();
		}
	});
});
</script>
</body>
</html>