{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    {include file="tpl/section/nav.phtml"}
                    <h1>Gestion des thémes</h1>
                    <div id="theming">
                        <ul class="thumbnails">
                            {$themes}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="tpl/section/js.phtml"}
</body>
</html>