{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Dashboard</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-folder-collapsed"></span>Ajouter une catégorie</div>
						<div class="dashboard-widget-content">
						{if $configcatalog eq 1}
						<form id="forms-catalog-category" method="post" action="/admin/index.php?dashboard&amp;catalog&amp;category&amp;post" style="margin-left:10px;">
						<div id="resultcategory"></div>
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="clibelle" class="inlinelabel">Catégorie :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="clibelle" name="clibelle" class="inputtext ui-corner-all" value="" size="20" /></td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{$selectlang}
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
							<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-folder-collapsed"></span>Catégorie</div>
						<div class="dashboard-widget-content">
						{$category_order}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-folder-collapsed"></span><span style="float:left;" class="ui-icon ui-icon-arrowthick-1-e"></span><span style="float:left;" class="ui-icon ui-icon-folder-open"></span>Ajouter une sous-catégorie</div>
						<div class="dashboard-widget-content">
						{if $configcatalog eq 1}
						<form id="forms-catalog-subcategory" method="post" action="/admin/index.php?dashboard&amp;catalog&amp;category&amp;post" style="margin-left:10px;">
						<div id="resultsubcategory"></div>
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="slibelle" class="inlinelabel">Sous Catégorie :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="slibelle" name="slibelle" class="inputtext ui-corner-all" value="" size="20" /></td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="slibelle" class="inlinelabel">Catégorie :</label></td>
								</tr>
								<tr>
									<td>
									{$selectcategory}
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
							<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-folder-collapsed"></span>Sous catégorie</div>
						<div class="dashboard-widget-content">
						{$subcategory_order}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
<div id="update-category" title="Modifier une catégorie"></div>
<div id="update-subcategory" title="Modifier une sous catégorie"></div>
{include file="common/javascript.phtml"}
</body>
</html>