{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane config_param=['level1'=>'catégorie']}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-flash-plus"></span>Ajouter une catégorie rapide</div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'catalog']} eq true}
						<form id="forms-catalog-category" method="post" enctype="multipart/form-data" action="" style="margin-left:10px;">
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="clibelle" class="inlinelabel">Catégorie :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="clibelle" name="clibelle" class="inputtext ui-corner-all" value="" size="20" /></td>
								</tr>
								{$selectlang}
								<tr>
									<td class="label"><label for="img_c">Image :</label></td>
								</tr>
								<tr>
									<td>
									<table>
										<tr>
											<td style="width:250px;">
												<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
										 		<input type="file" id="img_c" name="img_c" value="" />
										 	</td>
									 	</tr>
								 	</table>
									</td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
							<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-locale"></span> Langues Catégories</div>
						<div class="dashboard-widget-content">
							{sidebar_construct config_param=['module'=>'catalog']}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Statistiques</a></div>
						<div class="dashboard-widget-content">
							<div id="chart-google-catalog"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<!--[if lt IE 9]><script language="javascript" type="text/javascript" src="/min/?f=framework/js/tools/excanvas.min.js"></script><![endif]-->
{script src="/min/?f=framework/js/tools/jquery.jqplot.min.js,framework/js/tools/jqplot-plugins/jqplot.barRenderer.min.js,/framework/js/tools/jqplot-plugins/jqplot.categoryAxisRenderer.min.js,framework/js/tools/jqplot-plugins/jqplot.pointLabels.min.js" type="javascript"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/src/jcatalog.0.3.js',function(){
		if (typeof ns_jcatalog_category == "undefined") {
		  console.log("ns_jcatalog_category is not defined");
		}else{
			ns_jcatalog_category.run();
		}
	});
});
</script>
</body>
</html>