{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Edition de sous catégorie</div>
						<div class="dashboard-widget-content">
						{if $configcatalog eq 1}
							<form id="forms-catalog-editsubcategory" method="post" enctype="multipart/form-data"  action="" style="margin-left:10px;">
								<fieldset>
								<table>
									<tr>
										<td>
										<input type="hidden" name="usubcategory" id="usubcategory" value="{$smarty.get.upsubcat}" />
										<input type="text" name="update_subcategory" id="update_subcategory" class="inputtext ui-corner-all" value="{$slibelle}" size="20" />
										</td>
									</tr>
									<tr>
									<td>
									<table>
										<tr>
											<td style="width:250px;">
												<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
										 		<input type="file" id="update_img_s" name="update_img_s" value="" />
										 	</td>
										 	<td>&nbsp;</td>
										 	<td style="width:250px;" class="errorInput"></td>
									 	</tr>
								 	</table>
									</td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
								</table>			
								</fieldset>
								<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
							</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Image de sous catégorie</div>
						<div class="dashboard-widget-content">
							{if $img_s != null}
								<div><img src="{geturl}/upload/catalogimg/subcategory/{$img_s}" /></div>
							{else}
								<p>Aucune image</p>
							{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Organisation des produits</div>
						<div class="dashboard-widget-content">
						{$product_subcategory_order}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
</body>
</html>