{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Modifier un produit</div>
						<div class="dashboard-widget-content">
						{if $configcatalog eq 1}
						<form id="forms-catalog-card-product-edit" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="titlecatalog" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" id="idcatalog" value="{$smarty.get.editproduct}" />
										<input type="text" id="titlecatalog" name="titlecatalog" class="inputtext ui-corner-all" value="{$titlecatalog}" size="50" /></td>
										
									</tr>
									{if $idlang != 0}
									<tr>
										<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
									</tr>
									<tr>
										<td>
										<input type="text" disabled="disabled" readonly="readonly" id="iso" name="iso" class="inputdisabled ui-corner-all" value="{$iso}" size="5" />
										</td>
										
									</tr>
									{/if}
									<tr>
										<td class="label"><label for="price" class="inlinelabel">Prix :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="price" name="price" class="inputtext ui-corner-all" value="{$price}" size="15" /></td>
										
									</tr>
									<tr>
										<td class="label"><label for="desccatalog" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="desccatalog" id="desccatalog" class="fulltext mceEditor ui-corner-all" cols="" rows="">{$desccatalog}</textarea></td>
										
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter le produit dans une catégorie</div>
						<div class="dashboard-widget-content">
							<form id="forms-catalog-product" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table>
									<tr>
										<td class="label"><label for="idclc" class="inlinelabel">Catégorie :</label></td>
									</tr>
									<tr>
										<td>{$selectcategory}</td>
										
									</tr>
									<tr>
										<td class="label"><label for="idcls" class="inlinelabel">Sous catégorie :</label></td>
									</tr>
									<tr>
										<td>
											<select id="idcls" name="idcls">
											<option value="">Sélectionner une catégorie</option>
											</select>
										</td>
									
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
							</form>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-content">
							<div id="load_cat_product"></div>
							<div style="margin:5px;" class="button-link cat-uri-product" title="{$smarty.get.editproduct}">Voir les liens</div>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Lier un produit</div>
						<div class="dashboard-widget-content">
							<form id="forms-catalog-rel-product" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table>
								<tr>
										<td class="label"><label for="idclc" class="inlinelabel">Catégorie :</label></td>
									</tr>
									<tr>
										<td>{$selectcategory}</td>
									</tr>
									<tr>
										<td class="label"><label for="idproduct" class="inlinelabel">Produits :</label></td>
									</tr>
									<tr>
										<td>
											<select id="idproduct" name="idproduct">
											<option value="">Sélectionner un produit</option>
											</select>
										</td>
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
							</form>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-content">
							<div id="load_rel_product"></div>
							<div style="margin:5px;" class="button-link rel-uri-product" title="{$smarty.get.editproduct}">Voir les liens</div>
						</div>
					</div>
				</div>
				{include file="catalog/extends.phtml"}
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/jcatalog.1.1.js',function(){
		load_cat_product();
		load_rel_product();
	});
	dynamical_select_html(
			'#forms-catalog-rel-product',
			'/admin/catalog.php?product&editproduct=1&gethtmlprod',
			['idclc','idproduct']		
	);
	dynamical_select_json(
			'#forms-catalog-product',
			'/admin/catalog.php?product&editproduct=1&getjsonprod',
			['idclc','idcls']		
	);
});
</script>
</body>
</html>