{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Edition de catégorie</a></div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'catalog']} eq true}
							<form id="forms-catalog-editcategory" method="post" action="" style="margin-left:10px;">
								<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="ucategory" class="inlinelabel">Catégorie :</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" name="ucategory" id="ucategory" value="{$smarty.get.upcat}" />
										<input type="text" name="update_category" id="update_category" class="inputtext ui-corner-all" value="{$clibelle}" size="20" />
										</td>
									</tr>
									<tr>
										<td class="label"><label for="c_content" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="c_content" id="c_content" class="fulltext mceEditor ui-corner-all" cols="" rows="">{$c_content}</textarea></td>
									</tr>
								</table>			
								</fieldset>
								<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
							</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Image de catégorie</a></div>
						<div class="dashboard-widget-content">
							<div style="margin:0 2em;">
								<div id="load_img_ucategory">
									<div id="contener_image"></div>
								</div>
							</div>
							<form id="forms-catalog-editcategory-img" method="post" enctype="multipart/form-data" action="" style="margin-bottom:5px;margin-left:10px;">
								<fieldset>
								<table>
									<tr>
										<td class="label"><label for="update_img_c" class="update_img_c">Image :</label></td>
										<td>
										
											<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
										 	<input type="file" id="update_img_c" name="update_img_c" value="" />
										</td>
										<td><input type="submit" value="Envoyer" /></td>
									</tr>
								</table>			
								</fieldset>
							</form>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Organisation des produits</a></div>
						<div class="dashboard-widget-content dashboard-hidden">
							{$product_category_order}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Ajouter une sous-catégorie</a></div>
						<div class="dashboard-widget-content dashboard-hidden">
						<form id="forms-catalog-subcategory" method="post" enctype="multipart/form-data" action="" style="margin-left:10px;">
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="slibelle" class="inlinelabel">Sous Catégorie :</label></td>
								</tr>
								<tr>
									<td>
										<input type="hidden" id="idclc" name="idclc" value="{$smarty.get.upcat}" />
										<input type="text" id="slibelle" name="slibelle" class="inputtext ui-corner-all" value="" size="20" />
									</td>
								</tr>
								<tr>
									<td class="label"><label for="img_s">Image :</label></td>
								</tr>
								<tr>
									<td>
										<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
								 		<input type="file" id="img_s" name="img_s" value="" />
									</td>
								</tr>
								</table>			
							</fieldset>
						<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
						</form>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Organisation des sous catégories</a></div>
						<div class="dashboard-widget-content">
							<div id="list-sub-category"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
<script type="text/javascript">
$(function(){
	/*$.getScript('/framework/js/backend/jcatalog.1.1.js',function(){
		setTimeout(function(){
			load_img_category_catalog();
			load_subcategory();
		},1000);
	});*/
	$.getScript('/framework/js/backend/ns/jcatalog.0.2.min.js',function(){
		if (typeof ns_jcatalog_category == "undefined") {
		  console.log("ns_jcatalog_category is not defined");
		}else{
			ns_jcatalog_category.runEdit();
		}
	});
});
</script>
</body>
</html>