<div id="update-category">
<form id="forms-catalog-category" method="post" action="" style="margin-left:10px;">
	<fieldset>
	<table>
		<tr>
			<td><input type="text" name="clibelle" class="inputtext ui-corner-all" value="" size="20" /></td>
			<td><input type="submit" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></td>
		</tr>
	</table>			
	</fieldset>
</form>
</div>