{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Edition de sous catégorie</div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'catalog']} eq true}
							<form id="forms-catalog-editsubcategory" method="post" action="" style="margin-left:10px;">
								<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="usubcategory" class="inlinelabel">Sous Catégorie :</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" name="usubcategory" id="usubcategory" value="{$smarty.get.upsubcat}" />
										<input type="text" name="update_subcategory" id="update_subcategory" class="inputtext ui-corner-all" value="{$slibelle}" size="20" />
										</td>
									</tr>
									<tr>
										<td class="label"><label for="s_content" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="s_content" id="s_content" class="fulltext mceEditor ui-corner-all" cols="" rows="">{$s_content}</textarea></td>
									</tr>
								</table>			
								</fieldset>
								<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
							</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Image de sous catégorie</div>
						<div class="dashboard-widget-content">
							<div style="margin:0 2em;">
								<div id="load_img_usubcategory">
									<div id="contener_image"></div>
								</div>
							</div>
							<form id="forms-catalog-editsubcategory-img" method="post" enctype="multipart/form-data" action="" style="margin-bottom:5px;margin-left:10px;">
								<fieldset>
								<table>
									<tr>
										<td class="label"><label for="update_img_s" class="update_img_s">Image :</label></td>
										<td>
										
											<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
										 	<input type="file" id="update_img_s" name="update_img_s" value="" />
										</td>
										<td><input type="submit" value="Envoyer" /></td>
									</tr>
								</table>			
								</fieldset>
							</form>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Organisation des produits</div>
						<div class="dashboard-widget-content">
						{$product_subcategory_order}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
<script type="text/javascript">
$(function(){
	$(function(){
		/*$.getScript('/framework/js/backend/jcatalog.1.1.js',function(){
			setTimeout(function(){
				load_img_subcategory_catalog();
			},1000);
		});*/
		$.getScript('/framework/js/backend/ns/jcatalog.0.3.min.js',function(){
			if (typeof ns_jcatalog_subcategory == "undefined") {
			  console.log("ns_jcatalog_subcategory is not defined");
			}else{
				ns_jcatalog_subcategory.runEdit();
			}
		});
	});
});
</script>
</body>
</html>