{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-folder-collapsed"></span>Informations du produit</div>
						<div class="dashboard-widget-content">
						{if $configcatalog eq 1}
						<table>
								<tr>
									<td>Identifiant :</td>
									<td><div id="idproduct">{$idproduct}</div></td>
								</tr>
								<tr>
									<td>Titre :</td>
									<td>{$titlecatalog}</td>
								</tr>
								{if $idlang != 0}
								<tr>
									<td>Langue :</td>
									<td>{$codelang}</td>
								</tr>
								{/if}
							</table>
							{else}
							<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
							<span style="float:left;" class="ui-icon ui-icon-alert"></span>
								Vous n'avez pas la permission d'administrer ce module
							</div>
							{/if}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Ajouter ou modifer une image d'accueil</a></div>
						<div class="dashboard-widget-content">
					<form method="post" action="" enctype="multipart/form-data" id="forms-catalog-image">
						<fieldset>
							<table>
							<tr>
								<td class="label"><label for="imgcatalog">Image :</label></td>
							</tr>
							<tr>
								<td>
									<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
							 		<input type="file" id="imgcatalog" name="imgcatalog" value="" />
							 	</td>
						 	</tr>
						 	<tr>
						 		<td><input type="submit" value="Envoyer" /></td>
						 	</tr>
						</table>
						</fieldset>
						</form>
						</div>
						</div>
						{if $configmicrogalery eq 1}
						<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Ajouter ou modifer une image dans la galerie</a></div>
							<div class="dashboard-widget-content">
								<form method="post" action="" enctype="multipart/form-data" id="forms-catalog-galery">
								<fieldset>
									<table>
									<tr>
										<td class="label"><label for="imggalery">Image :</label></td>
									</tr>
									<tr>
									<td>
										<div id="progressbar2"></div>
									 	<div id="progressText2"></div>
									 </td>
									<tr>
										<td>
											<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
									 		<input type="file" id="imggalery" name="imggalery" value="" />
									 	</td>
								 	</tr>
								 	<tr>
								 		<td><input type="submit" value="Envoyer" /></td>
								 	</tr>
								</table>
								</fieldset>
								</form>
							</div>
						</div>
						<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">La galerie du produit: {$titlecatalog}</a></div>
							<div class="dashboard-widget-content">
								<div id="contener_micro_galery"></div>
							</div>
						</div>
						{else}
						<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plus"></span>Module supplémentaire</div>
							<div class="dashboard-widget-content">
							<p>Commandez notre module de micro galerie pour votre catalogue</p>
							</div>
						</div>
						{/if}
					</div>
					<div class="column">
						<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
							<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-image"></span>Image du produit</div>
							<div class="dashboard-widget-content">
							<table>
								<tr>
									<td>
										<div id="load_img_product">
											<div id="contener_image_product"></div>
										</div>
									</td>
								</tr>
								<tr>
									<td>Largeur: <span id="gwidth"></span></td>
								</tr>
								<tr>
									<td>Hauteur: <span id="gheight"></span></td>
								</tr>
							</table>
							<table>
								<tr>
									<td>
										<div id="load_img_medium">
											<div id="contener_image_medium"></div>
										</div>
									</td>
								</tr>
								<tr>
									<td>Largeur: <span id="pwidth"></span></td>
								</tr>
								<tr>
									<td>Hauteur: <span id="pheight"></span></td>
								</tr>
							</table>
							<table>
								<tr>
									<td>
										<div id="load_img_mini">
											<div id="contener_image_mini"></div>
										</div>
									</td>
								</tr>
								<tr>
									<td>Largeur: <span id="swidth"></span></td>
								</tr>
								<tr>
									<td>Hauteur: <span id="sheight"></span></td>
								</tr>
							</table>
							</div>
						</div>
					</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript"> 
$(function(){
	$.getScript('/framework/js/backend/jcatalog.1.1.js',function(){
		load_img_product_catalog();
		load_micro_galery_catalog();
	});
});
</script>
</body>
</html>