{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Déplacer un produit</div>
					<div class="dashboard-content">
					{if {admin_level_config config_param=['module'=>'catalog'} eq true}
					<form id="move-catalog-product" method="post" action="" style="margin-left:10px;">
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="idproduct" class="inlinelabel">Identifiant :</label></td>
								</tr>
								<tr>
									<td><input type="text" disabled="disabled" id="idproduct" name="idproduct" class="inputtext ui-corner-all" value="{$idproduct}" size="50" /></td>
								</tr>
								<tr>
									<td class="label"><label for="titlecatalog" class="inlinelabel">Titre :</label></td>
								</tr>
								<tr>
									<td><input type="text" disabled="disabled" readonly="readonly" id="titlecatalog" name="titlecatalog" class="inputtext ui-corner-all" value="{$titlecatalog}" size="50" /></td>
								</tr>
								{if $idlang != 0}
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
								</tr>
								<tr>
									<td>
										<input type="text" disabled="disabled" readonly="readonly" id="iso" name="iso" class="inputdisabled ui-corner-all" value="{$iso}" size="5" />
									</td>
								</tr>
								{/if}
								{$selectlang}
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
					</form>
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jcatalog.0.2.js',function(){
		if (typeof ns_jcatalog_product == "undefined") {
		  console.log("ns_jcatalog_product is not defined");
		}else{
			ns_jcatalog_product.runMove();
		}
	});
});
</script>
</body>
</html>