{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter un produit</div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'catalog']} eq true}
						<form id="forms-catalog-card-product" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="titlecatalog" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="titlecatalog" name="titlecatalog" class="inputtext ui-corner-all" value="" size="50" /></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									{$selectlang}
									<tr>
										<td class="label"><label for="price" class="inlinelabel">Prix :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="price" name="price" class="inputtext ui-corner-all" value="" size="15" /></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									<tr>
										<td class="label"><label for="desccatalog" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="desccatalog" id="desccatalog" class="fulltext mceEditor ui-corner-all" cols="" rows=""></textarea></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
					<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Statistiques</div>
						<div class="dashboard-widget-content">
						<table class="clear" style="width:60%;">
							<thead>
								<tr>
									<th>Intitulé</th>
									<th>Eléments</th>
									<th><span style="float:left;" class="ui-icon ui-icon-folder-collapsed"></span></th>
									<th><span style="float:left;" class="ui-icon ui-icon-folder-open"></span></th>
								</tr>
							</thead>
							<tbody>
								<tr class="line">
									<td>Produits visibles</td>
									<td class="nowrap">{$global_product}</td>
									<td class="nowrap"><span style="float:left;" class="ui-icon ui-icon-close"></span></td>
									<td class="nowrap">{$global_product_subfolder}</td>
								</tr>
								<tr class="line">
									<td>Produits liés</td>
									<td class="nowrap">{$global_rel_product}</td>
									<td class="nowrap"><span style="float:left;" class="ui-icon ui-icon-close"></span></td>
									<td class="nowrap"><span style="float:left;" class="ui-icon ui-icon-close"></span></td>
								</tr>
								<tr class="line">
									<td>Catégories</td>
									<td class="nowrap"><span style="float:left;" class="ui-icon ui-icon-close"></span></td>
									<td class="nowrap">{$global_folder}</td>
									<td class="nowrap">{$global_subfolder}</td>
								</tr>
							</tbody>
						</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/src/jcatalog.0.3.js',function(){
		if (typeof ns_jcatalog_product == "undefined") {
		  console.log("ns_jcatalog_product is not defined");
		}else{
			ns_jcatalog_product.runAdd();
		}
	});
});
</script>
</body>
</html>