<footer>
    <div class="navbar navbar-inverse navbar-static-bottom">
        <div class="navbar-inner">
            <div class="container-fluid">
                <p class="navbar-text">&copy; <a href="http://www.magix-cms.com/" class="targetblank">Magix CMS</a> 2008 - 2013
                   {#powered_by#} <a href="http://magix-cjquery.com" class="targetblank">Magix cjQuery</a></p>
            </div>
        </div>
    </div>
</footer>