<form id="forms_cms_add_parent" method="post" action="" style="margin-left:10px;">
	<fieldset>
		<table class="table-tinymce">
			<tr>
				<td class="label"><label for="title_page" class="inlinelabel">Titre :</label></td>
			</tr>
			<tr>
				<td>
					<input type="text" id="title_page" name="title_page" class="inputtext ui-corner-all" value="" size="50" />
					{if $selectlang eq null}
					<input type="hidden" name="idlang" id="idlang" value="{$smarty.get.getlang}" />
					{/if}
				</td>
			</tr>
			{if $selectlang !=null}
				{$selectlang}
			{/if}
			<tr>
				<td class="label"><label for="content_page" class="inlinelabel">Contenu :</label></td>
			</tr>
			<tr>
				<td><textarea name="content_page" id="content_page" class="fulltext mceEditor ui-corner-all" cols="" rows=""></textarea></td>
			</tr>
		</table>			
	</fieldset>
	<div id="showmetas"><span style="float:left;"></span> Voir les métas</div>
		<div id="metascontener">
		<table class="table-tinymce">
			<tr>
				<td class="label"><label for="seo_title_page" class="inlinelabel">Title :</label></td>
			</tr>
			<tr>
				<td>
					<textarea id="seo_title_page" name="seo_title_page" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
				</td>
			</tr>
			<tr>
				<td class="label"><label for="seo_desc_page" class="inlinelabel">Description :</label></td>
			</tr>
			<tr>
				<td>
					<textarea name="seo_desc_page" id="seo_desc_page" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
				</td>
			</tr>
		</table>
		</div>
	<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
</form>