<form action="" method="post" id="forms-add-relatedlang-pages" style="margin-left:10px;"> 
	<fieldset>
		<table>
			{$selectexcludelang}
			<tr>
				<td class="label"><label for="title_p_lang" class="inlinelabel">Page parente dans la langue :</label></td>
			</tr>
			<tr>
				<td>
					<input type="text" id="title_p_lang" name="title_p_lang" class="inputtext ui-corner-all" value="" size="50" />
					<input type="text" id="idlang_p" name="idlang_p" readonly="readonly" class="readonly ui-corner-all" value="" size="5" />
				</td>
			</tr>
		</table>
		<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
	</fieldset>
</form> 