<form id="forms_cms_move_page" method="post" action="" style="margin-left:10px;">
	<fieldset>
		<table class="table-tinymce">
			<tr>
				<td>
				<table>
					<tr>
						<td class="label">
							<label for="idpage" class="inlinelabel">Identifiant :</label>
						</td>
						<td class="label">
							<label for="iso" class="inlinelabel">Langue :</label>
						</td>
					</tr>
					<tr>
						<td>
							<input type="text" name="idpage" id="idpage" class="inputtext ui-corner-all" value="{$idpage}" />
						</td>
						<td>
							<input type="text" disabled="disabled" readonly="readonly" id="iso" class="inputdisabled ui-corner-all" value="{$iso}" size="4" />
						</td>
					</tr>
				</table>
				</td>
			</tr>
			<tr>
				<td class="label"><label for="cmslink" class="inlinelabel">URL :</label></td>
			</tr>
			<tr>
				<td>
					<input type="text" id="cmslink" disabled="disabled" readonly="readonly" class="inputdisabled ui-corner-all" value="" size="60" />
				</td>
			</tr>
			<tr>
				<td class="label"><label for="title_page" class="inlinelabel">Titre :</label></td>
			</tr>
			<tr>
				<td>
					<input type="text" id="title_page" name="title_page" disabled="disabled" readonly="readonly" class="inputdisabled ui-corner-all" value="{$title_page}" size="50" />
				</td>
			</tr>
			{$selectlang}
		</table>			
	</fieldset>
	<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
</form>