{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
<div class="container-narrow">
    {include file="section/top.phtml"}
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li>
                <a href="/install/index.php">Démarrer</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/analysis.php">Analyse</a> <span class="divider">/</span>
            </li>
            <li>
                <span class="active">Configuration</span>
            </li>
        </ul>
        <div class="mc-message clearfix"></div>
        {include file="config/forms/add.phtml"}
        <ul class="pager">
            <li class="previous">
                <a href="/install/analysis.php">&larr; Précédent</a>
            </li>
            <li class="next">
                <a href="/install/database.php">Suivant &rarr;</a>
            </li>
        </ul>
    </div>
    {include file="section/footer.phtml"}
</div>
{include file="section/js.phtml"}
{include file="config/section/js.phtml"}
</body>
</html>