<ol id="breadcrumb" class="breadcrumb">
{if $smarty.server.SCRIPT_NAME != '/index.php'}
    <li>
        <a href="{geturl}/{getlang}/" title="{#show_home#|firststring}">
            {#home#|firststring}
        </a>
        <span class="divider">/</span>
    </li>
        {* # Pages *}
    {if $smarty.server.SCRIPT_NAME == '/cms.php'}
        {if $smarty.get.getidpage_p}
            <li>
                <a href="{geturl}/{$url_page_p}" title="{#show_page#|firststring}: {$name_page_p}">
                    {$name_page_p}
                </a>
                <span class="divider">/</span>
            </li>
        {/if}
        <li>
            {$name_page}
        </li>
    {/if}
        {* # Catalogue *}
    {if $smarty.server.SCRIPT_NAME == '/catalog.php'}
        {if $smarty.get.idclc}
                {* ## Root *}
            <li>
                <a href="{geturl}/{getlang}/{#nav_catalog_uri#}" title="{#show_catalog#|firststring}">
                    {#catalog#|firststring}
                </a>
                <span class="divider">/</span>
            </li>
            {if $smarty.get.idcls OR $smarty.get.idproduct}
                {* ## Catégories *}
                <li>
                    <a href="{geturl}/{$url_cat}/" title="{#show_category#|firststring}}: {$name_cat}">
                        {$name_cat}
                    </a>
                    <span class="divider">/</span>
                </li>
                {if $smarty.get.idcls AND $smarty.get.idproduct}
                    {* ## Sous-catégories *}
                    <li>
                        <a href="{geturl}/{$url_subcat}/" title="{#show_subcategory#|firststring}}: {$name_subcat}">
                            {$name_subcat}
                        </a>
                        <span class="divider">/</span>
                    </li>
                {else}
                    <li>
                        {$name_subcat}
                    </li>
                    {* /sous-catégories *}
                {/if}
                {if $smarty.get.idproduct}
                    {* ## Produits *}
                    <li>
                        {$name_product}
                    </li>
                {/if}
            {else}
                <li>
                    {$name_cat}
                </li>
                {* /Catégories *}
            {/if}
        {else}
            <li>
                {#catalog#|firststring}
            </li>
            {* /root *}
        {/if}
        {**** /catalog ****}
    {/if}
        {* # Actualités *}
    {if $smarty.server.SCRIPT_NAME == '/news.php'}
            <li>
                {if $smarty.get.tag OR $smarty.get.uri_get_news}
                    <a href="{geturl}/{getlang}/{#nav_news_uri#}/" title="{#show_news#|firststring}">
                        {#news#|firststring}
                    </a>
                    <span class="divider">/</span>
                    {else}
                    {#news#|firststring}
                {/if}
            </li>
            {if $smarty.get.uri_get_news}
                <li>
                    {$name_news}
                </li>
            {/if}
            {if $smarty.get.tag}
                <li>
                   {#theme#|firststring}: {$name_tag}
                </li>
            {/if}
    {/if}
        {**** Plugins ****}
    {if $smarty.server.SCRIPT_NAME == '/plugins.php'}
        {if $smarty.get.magixmod == 'contact'}
            <li>
                {#contact_form#|firststring}
            </li>
        {/if}
    {/if}
    {else}
    <li>
        {#home#|firststring}
    </li>
{/if}
</ol>