{script src="/min/?g=publicjs,jimagine" concat=$concat type="javascript"}
<script type="text/javascript">
	var iso = "{getlang}";
    $.nicenotify.notifier = {
        box:"",
        elemclass : '.mc-message'
    };
</script>
{script src="/min/?f=skin/{template}/js/bootstrap.js,skin/{template}/js/plugins/jquery.fancybox.min.js,skin/{template}/js/form.js,skin/{template}/js/global.js" concat=$concat type="javascript"}
{literal}
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
<script type="text/javascript">
	window.___gcfg = {
	   lang: "{/literal}{getlang}{literal}"
	};
	gapi.plusone.render("share-google",{"parsetags": "explicit","size": "large", "count": "true"});
</script>
{/literal}