<div id="primary-sidebar" class="span3">
    {* # Pages *}
    {if $smarty.server.SCRIPT_NAME == '/cms.php' OR $smarty.server.SCRIPT_NAME == '/index.php'}
        {* ## Navigation *}
        {widget_cms_nav
            hierarchy=[
                'select' => 'all',
                'level' => 'all'
            ]
            htmlAttribut=[
                'id_container' => 'secondary-nav',
                'class_container' => 'nav nav-list well',
                'class_current'     => 'active'
            ]
        }
    {/if}
    {* # Catalogue *}
    {if $smarty.server.SCRIPT_NAME == '/catalog.php'}
        {* ## Navigation *}
        {widget_catalog_nav
            dataSelect=[
                'select' => 'all',
                'level'   => ['category' => 'subcategory']
            ]
            htmlPrepend="<li class='nav-header'>{#catalog_navigation#}</li>"
            htmlAttribut=[
                'id_container' => 'secondary-nav',
                'class_container' => 'nav nav-list well',
                'class_current'     => 'active'
            ]
        }
        {* ## Dernier produit *}
        {widget_catalog_display
            dataSelect = [
                'level' => 'last-product',
                'limit' => 1
            ]
            htmlPrepend = "<li class='nav-header'>{#last_products#}</li>"
            htmlStructure = [
                'item' => [
                    'htmlBefore' => '<li class="span3"><div class="thumbnail">'
                ],
                'name' => [
                    'htmlBefore' => '<div class="caption"> <p class="lead">',
                    'htmlAfter' => '</p>'
                ],
                'price' => [
                    'htmlBefore' => '<a class="btn" href="|#url#|">',
                    'htmlAfter' => '</a>'
                ],
                'display' => [1 => ['name', 'img', 'price']]
            ]
        }
    {/if}
    {* # Actualités *}
    {if $smarty.server.SCRIPT_NAME == '/news.php'}
        {* ## Navigation *}
        {widget_news_nav
            htmlAttribut=[
                'id_container' => 'secondary-nav',
                'class_container' => 'nav nav-list well',
                'class_current'     => 'active'
            ]
            htmlPrepend="<li class='nav-header'>{#news_by_theme#}</li>"
        }
        {* ## Dernières actualités *}
        {widget_news_display
            dataSelect=[
                'level' => 'last-news',
                'limit' => 3
            ]
        htmlPrepend = "<li class='nav-header'>{#last_news#}</li>"
        htmlStructure = 'sidebar'
        }
    {/if}
</div>