{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    {include file="config/section/nav.phtml"}
                    <h1>{#imagesize#|ucfirst}</h1>
                    <ul class="nav nav-tabs clearfix">
                        <li{if !$smarty.get.tab} class="active"{/if}>
                            <a href="/admin/config.php?section=imagesize">{#catalog#|ucfirst}</a>
                        </li>
                        <li{if $smarty.get.tab eq "news"} class="active"{/if}>
                            <a href="/admin/config.php?section=imagesize&amp;tab=news">{#news#|ucfirst}</a>
                        </li>
                        <li{if $smarty.get.tab eq "plugins"} class="active"{/if}>
                            <a href="/admin/config.php?section=imagesize&amp;tab=plugins">Plugins</a>
                        </li>
                    </ul>
                    <div class="mc-message clearfix"></div>
                    {include file="config/forms/images.phtml"}
                </div>
            </div>
        </div>
    </div>
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="config/section/js.phtml"}
</body>
</html>