{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
<div class="container-narrow">
    {include file="section/top.phtml"}
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li>
                <a href="/install/index.php">{#start#}</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/analysis.php">{#analysis#}</a> <span class="divider">/</span>
            </li>
            <li>
                <a href="/install/config.php">{#configuration#}</a> <span class="divider">/</span>
            </li>
            <li>
                <span class="active">{#database#}</span>
            </li>
        </ul>
        <div class="mc-message clearfix"></div>
        <div class="mc-info clearfix">
            <div class="span6 alert alert-info">
                <span class="icon-info-sign"></span> {#info_database#}
            </div>
        </div>
        <a href="#" class="btn btn-primary" id="process_db">
            <span class="icon-cog"></span> {#install_table#}
        </a>
        <div id="install_table"></div>
        <ul class="pager">
            <li class="previous">
                <a href="/install/config.php">&larr; {#previous#}</a>
            </li>
            <li class="next">
                <a href="/install/user.php">{#next#} &rarr;</a>
            </li>
        </ul>
    </div>
    {include file="section/footer.phtml"}
</div>
{include file="section/js.phtml"}
{include file="database/section/js.phtml"}
</body>
</html>