{include file="section/editor.phtml"}
{script src="/{baseadmin}/min/?g=tinymce" concat={$concat} type="javascript"}
{script src="/{baseadmin}/min/?g=charts" concat={$concat} type="javascript"}
{script src="/{baseadmin}/min/?f={baseadmin}/template/js/tinymce-config.js,{baseadmin}/template/js/mc_home.js" concat={$concat} type="javascript"}
<script type="text/javascript">
$(function(){
    if (typeof MC_home == "undefined")
    {
        console.log("MC_home is not defined");
    }else{
        if($('#list_home').length != 0){
            MC_home.runList();
        }else if($('#forms_home_edit').length != 0){
            MC_home.runEdit(edit);
        }else{
            MC_home.runCharts();
        }
    }
});
</script>