{script src="/{baseadmin}/min/?g=charts" type="javascript"}
{script src="/{baseadmin}/min/?f={baseadmin}/template/js/mc_home.js" type="javascript"}
<script type="text/javascript">
$(function(){
    if (typeof MC_home == "undefined")
    {
        console.log("MC_home is not defined");
    }else{
        if($('#list_home').length != 0){
            MC_home.runList();
        }else{
            MC_home.runCharts();
        }
    }
});
</script>