<div class="row-fluid">
    <h2>Création des sitemaps</h2>
    <div class="block-row span11">
        <div class="span3">
            <span class="badge">1</span> Sitemap Index
        </div>
        <div class="span8">
            <a href="#" class="btn btn-primary" id="sitemap_index"><span class="icon-sitemap"></span> Création du fichier</a>
        </div>
    </div>
    <div class="block-row span11">
        <div class="span3">
            <span class="badge badge-inverse">2</span> Sitemap URL
        </div>
        <div class="span8">
            <form id="forms_sitemap_url_add" class="form-horizontal form-inline" method="post" action="">
                <p>
                {$select_lang}
                    <input type="submit" class="btn btn-primary" value="Envoyer" />
                </p>
            </form>
        </div>
    </div>
    <div class="block-row span11">
        <div class="span3">
            <span class="badge label-info">3</span> Sitemap Image
        </div>
        <div class="span8">
            <form id="forms_sitemap_images_add" class="form-horizontal form-inline" method="post" action="">
                <p>
                {$select_lang}
                    <input type="submit" class="btn btn-primary" value="Envoyer" />
                </p>
            </form>
        </div>
    </div>
    <h2>Envoi des sitemaps</h2>
    <div class="block-row span11">
        <span class="span7">
            <span class="badge">1</span> Permet de faire un ping à google pour le sitemap
        </span>
        <span class="span1">
            <a href="#" id="pinguer" class="btn btn-small googleping">
                <span class="icon-plus"></span>
            </a>
        </span>
    </div>
    <div class="block-row span11">
        <span class="span7">
            <span class="badge badge-inverse">2</span> Permet de faire un ping à google avec un fichier GZ pour le sitemap
        </span>
        <span class="span1">
            <a href="#" id="pinguer-gz" class="btn btn-small googleping">
                <span class="icon-plus"></span>
            </a>
        </span>
    </div>
</div>