<div class="row-fluid">
    <h2>{#h2_creating_sitemap#|ucfirst}</h2>
    <div class="block-row span11">
        <div class="span3">
            <span class="badge">1</span> Sitemap Index
        </div>
        <div class="span8">
            <a href="#" class="btn btn-primary" id="sitemap_index">
                <span class="icon-sitemap"></span> {#file_creation#|ucfirst}
            </a>
        </div>
    </div>
    <div class="block-row span11">
        <div class="span3">
            <span class="badge badge-inverse">2</span> Sitemap URL
        </div>
        <div class="span8">
            <form id="forms_sitemap_url_add" class="form-horizontal form-inline" method="post" action="">
                <p>
                    {$select_lang}
                    <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
                </p>
            </form>
        </div>
    </div>
    <div class="block-row span11">
        <div class="span3">
            <span class="badge label-info">3</span> Sitemap Image
        </div>
        <div class="span8">
            <form id="forms_sitemap_images_add" class="form-horizontal form-inline" method="post" action="">
                <p>
                    {$select_lang}
                    <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
                </p>
            </form>
        </div>
    </div>
    <h2>{#h2_sending_sitemap#|ucfirst}</h2>
    <div class="block-row span11">
        <span class="span7">
            <span class="badge">1</span> {#span_googleping#}
        </span>
        <span class="span1">
            <a href="#" id="pinguer" class="btn btn-small googleping">
                <span class="icon-plus"></span>
            </a>
        </span>
    </div>
    <div class="block-row span11">
        <span class="span7">
            <span class="badge badge-inverse">2</span> {#span_googleping_gz#}
        </span>
        <span class="span1">
            <a href="#" id="compressed" class="btn btn-small googleping">
                <span class="icon-plus"></span>
            </a>
        </span>
    </div>
</div>