{include file="common/head.phtml"}
<style type="text/css">
table tr td{
	border:none;
}
</style>
<meta name="description" content="Magix CMS&trade; - Login" />
    <title>Magix CMS&trade; - Login</title>
</head>
<body>
<div id="page">
	<div id="log-board">
			<div id="login">
				<div id="loginforms" style="border-width:3px;" class="ui-widget-content ui-corner-all">
				<div style="background:none;border:none;" class="dashboard-header ui-widget-header">
					<img src="/framework/img/logo-login.png" width="200" height="45" alt="Admin magixCMS" />
				</div>
				{$msg}
				<form id="forms-log" method="post" action="">
					<table>
						<tr>
							<td class="label"><label for="acmail" class="inlinelabel">Email :</label></td>
						</tr>
						<tr>
							<td><input type="text" id="acmail" name="acmail" class="text ui-widget-content ui-corner-all" value="" size="30" /></td>
						</tr>
						<tr>
							<td class="label"><label for="acpass" class="inlinelabel">Password :</label></td>
						</tr>
						<tr>
							<td><input type="password" id="acpass" name="acpass" class="text ui-widget-content ui-corner-all" value="" size="30" /></td>
							<td><input type="hidden" id="hashtoken" name="hashtoken" value="{$hashpass}" /></td>
						</tr>
						<tr>
							<td><div style="margin-top:5px;"><input type="submit" name="slogin" class="ui-state-default ui-corner-all" value="Connexion" /></div></td>
						</tr>
					</table>
				</form>
				<div class="dashboard-header ui-widget-header ui-priority-secondary ui-corner-all" style="padding:5px;margin-top:3px;">
					&copy; <a href="http://www.magix-cms.com" class="targetblank strong">Magix CMS</a> 2010 - 2011
				</div>
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>