<form class="forms-config" method="post" action="" id="global-config-lang">
	<fieldset>
		<table>
			<tr>
				<td style="width:150px;">Langue :</td>
				<td style="width:80px;">
					Activer <input type="radio" name="configlang" {if $configlang eq 1}checked="checked"{/if} value="1" />
				</td>
				<td style="width:100px;">
					Désactiver <input type="radio" name="configlang" {if $configlang eq 0}checked="checked"{/if} value="0" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<form class="forms-config" method="post" action="" id="global-config-news">
	<fieldset>
		<table>
			<tr>
				<td style="width:150px;">News :</td>
				<td style="width:80px;">
					Activer <input type="radio" name="confignews" {if $confignews eq 1}checked="checked"{/if} value="1" />
				</td>
				<td style="width:100px;">
					Désactiver <input type="radio" name="confignews" {if $confignews eq 0}checked="checked"{/if} value="0" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<form class="forms-config" method="post" action="" id="global-config-cms">
	<fieldset>
		<table>
			<tr>
				<td style="width:150px;">CMS :</td>
				<td style="width:80px;">
					Activer <input type="radio" name="configcms" {if $configcms eq 1}checked="checked"{/if} value="1" />
				</td>
				<td style="width:100px;">
					Désactiver <input type="radio" name="configcms" {if $configcms eq 0}checked="checked"{/if} value="0" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<form class="forms-config" method="post" action="" id="global-config-catalog">
	<fieldset>
		<table>
			<tr>
				<td style="width:150px;">Catalogue :</td>
				<td style="width:80px;">
					Activer <input type="radio" name="configcatalog" {if $configcatalog eq 1}checked="checked"{/if} value="1" />
				</td>
				<td style="width:100px;">
					Désactiver <input type="radio" name="configcatalog" {if $configcatalog eq 0}checked="checked"{/if} value="0" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>
<form class="forms-config" method="post" action="" id="global-rewritenews">
	<fieldset>
		<table>
			<tr>
				<td style="width:150px;">Réécriture des métas :</td>
				<td style="width:80px;">
					Activer <input type="radio" name="configrmetas" {if $configmetasrewrite eq 1}checked="checked"{/if} value="1" />
				</td>
				<td style="width:100px;">
					Désactiver <input type="radio" name="configrmetas" {if $configmetasrewrite eq 0}checked="checked"{/if} value="0" />
				</td>
			</tr>
		</table>
	</fieldset>
</form>