<p style="margin-left:10px;">Indiquez le nombre de pages maximum ou laissez à 0</p>
<form class="forms-config" method="post" action="" id="limited-cms-module">
	<fieldset>
		<p>
			<label>Nombre de page CMS :</label>
			<input type="hidden" name="idconfig" value="{$idconfigcms}" size="4" />
			<input type="text" name="max_record" class="spin inputtext" value="{$max_record}" size="4" />
			<input type="button" id="snumbCms" name="snumbCms" class="btn-decoration" value="update" />
		</p>
	</fieldset>
</form>