<p>Indiquez le nombre de pages maximum ou laissez à 0</p>
<form class="forms-config" method="post" action="" id="limited-cms-module">
	<fieldset>
		<p>
			<label>Nombre de page CMS :</label>
			<input type="hidden" name="attribute" id="attribute" value="{$attribute}" size="4" />
			<input type="text" name="number" class="spin inputtext" id="cmsnumber" value="{$numbcmspage}" size="4" />
			<input type="button" id="snumbCms" name="snumbCms" class="btn-decoration" value="update" />
		</p>
	</fieldset>
</form>