{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Analyze Configuration</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
		{include file="common/slider.phtml"}
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-process"></span>&nbsp;Analyse la configuration</div>
				<div class="dashboard-content">
					<div class="ui-widget-header ui-corner-all" style="float:right;width:200px;padding:5px;margin-right:20px;">
						<p style="text-align:center;">Tester votre configuration avant d'installer magix cms</p>
						<p style="text-align:center;"><button id="install-config" class="fg-button ui-state-disabled ui-corner-all">Continuer</button></p>
					</div>
					<table class="clear" style="width:500px;">
						<thead>
							<tr>
								<th>Check</th>
								<th>Result</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="maximal">PHP version</td>
								<td class="nowrap"><div id="phpversion"></div></td>
							</tr>
							<tr>
								<td class="maximal">Mbstring</td>
								<td class="nowrap"><div id="mbstr"></div></td>
							</tr>
							<tr>
								<td class="maximal">Iconv</td>
								<td class="nowrap"><div id="iconv"></div></td>
							</tr>
							<tr>
								<td class="maximal">Obstart</td>
								<td class="nowrap"><div id="obst"></div></td>
							</tr>
							<tr>
								<td class="maximal">Simple XML</td>
								<td class="nowrap"><div id="simple"></div></td>
							</tr>
							<tr>
								<td class="maximal">Dom xml</td>
								<td class="nowrap"><div id="dom"></div></td>
							</tr>
							<tr>
								<td class="maximal">SPL classes</td>
								<td class="nowrap"><div id="spl"></div></td>
							</tr>
						</tbody>
					</table>
					<form id="forms-install-check" method="post" action="" style="margin-left:10px;">
						<p><input type="hidden" name="check_exec" value="true" /></p>
						<div style="margin:5px;"><input type="button" id="checking" class="ud-button ui-state-default ui-corner-all" value="Checking" /></div>
					</form>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>