{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Install database</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		<div class="dashboard ui-widget-content ui-corner-all">
		{include file="common/top.phtml"}
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-database"></span><h1>Installation des tables</h1></div>
				<div class="dashboard-content">
					<div class="right-text-infos ui-widget-header ui-corner-all" style="float:right;width:200px;padding:5px;margin-right:20px;">
						<p style="text-align:center;">Une fois les tables installées, un utilisateur doit être configuré</p>
						<p style="text-align:center;">
							<a href="/install/config.php" class="inst-button"><span class="ui-icon ui-icon-seek-first"></span></a>
							<a href="#" id="install-user" class="inst-button"><span class="ui-icon ui-icon-seek-end"></span></a>
						</p>
					</div>
					<div class="center-text-infos">
						<p>Vous voici arrivé à la partie la plus importante de l'installation.</p>
						<p>Votre serveur doit contenir une base de données, le cas échéant, vous devrez en créer une.</p>
						<h2 class="ui-widget-header" style="width:450px;padding:2px;">Informations pratiques</h2>
						<div style="margin:5px 0 5px 0;width:450px;padding:2px;text-align:center;" class="ui-state-highlight ui-corner-all">
							<p>Le serveur MySQL doit être un système client / serveur de version minimum 5 et doit comprendre le moteur <strong>INNODB</strong></p>
						</div>
						<div id="dbinstall"></div>
						<form id="forms-install-database" method="post" action="" style="margin-left:10px;">
							<p><input type="hidden" name="database" value="true" /></p>
							<div style="margin:5px;"><input type="submit" value="Installer les tables" /></div>
						</form>
					</div>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
</body>
</html>