{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Install database</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
		{include file="common/slider.phtml"}
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-organ"></span><h1>Installation des tables</h1></div>
				<div class="dashboard-content">
					<div class="right-text-infos ui-widget-header ui-corner-all" style="float:right;width:200px;padding:5px;margin-right:20px;">
						<p style="text-align:center;">Une fois les tables installées, un utilisateur doit être configuré</p>
						<p style="text-align:center;"><button id="install-user" class="fg-button ui-state-disabled ui-corner-all">Continuer</button></p>
					</div>
					<div class="center-text-infos">
						<p>Vous voici arrivé à la partie la plus importante de l'installation.</p>
						<p>Votre serveur doit contenir une base de données, le cas échéant, vous devrez en créer une.</p>
						<h2>Informations pratiques</h2>
						<p>Le serveur MySQL doit être un système client / serveur de version minimum 5 et doit comprendre le moteur <strong>INNODB</strong></p>
						<div id="dbinstall"></div>
						<form id="forms-install-database" method="post" action="" style="margin-left:10px;">
							<p><input type="hidden" name="database" value="true" /></p>
							<div style="margin:5px;"><input type="submit" value="Installer les tables" /></div>
						</form>
					</div>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
</body>
</html>