{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Fin de l'installation</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
		{include file="common/slider.phtml"}
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span>&nbsp;Fin de l'installation</div>
				<div class="dashboard-content" style="font-size:18px;">
					<p style="margin-left:10px;">L'installation est terminé.</p>
					<p style="margin-left:10px;">Connectez-vous à l'administration de votre site internet.</p>
					<ul style="margin-left:20px;">
					<li style="list-style:square;"><a style="text-decoration:underline;" href="{geturl}/admin/">Administration</a></li>
					<li style="list-style:square;"><a style="text-decoration:underline;" href="{geturl}">Site internet</a></li>
					</ul>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>