{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Install database</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
		{include file="common/slider.phtml"}
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span>&nbsp;Fin de l'installation</div>
				<div class="dashboard-content">
					L'installation est terminé.
					Connectez-vous à l'<a href="{geturl}/admin/">administration</a> de votre site internet.
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>