{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Fin de l'installation</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span><h1>Fin de l'installation</h1></div>
				<div class="dashboard-content">
					<div class="center-text-infos">
					<p>L'installation est terminée.</p>
					<p>N'oubliez pas de supprimer le dossier <strong>install</strong></p>
					<p>Connectez-vous à l'administration de votre site internet.</p>
					<ul>
						<li><a class="targetblank" href="{geturl}/admin/">Administration</a></li>
						<li><a class="targetblank" href="{geturl}">Site internet</a></li>
					</ul>
					</div>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>