{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Install Magix CMS</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-content">
					<div class="center-text-infos">
					<p style="margin-top:10px;text-align:center;">L'installation se fait en plusieurs étapes, suivez pas à pas les indications</p>
					<div style="text-align:center;margin:5px;">
					<button id="install-check" class="inst-button">Install</button>
					<button id="upgrade-check" class="inst-button">Upgrade</button>
					</div>
					</div>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>