{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Upgrade Magix CMS</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
		{include file="common/slider.phtml"}
				<div class="dashboard-content">
					<div class="center-text-infos">
					<p style="margin-top:10px;text-align:center;">La procédure de mise à jour de la base de donnée</p>
					<div style="text-align:center;margin:5px;"><button class="inst-button" id="update-db">Mettre à jour</button></div>
					</div>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>