{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Administrateur du site internet</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
		{include file="common/slider.phtml"}
			<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span><h1>Administrateurs</h1></div>
				<div class="dashboard-content">
					<form id="forms-install-users" method="post" action="/install/adminuser.php?postadm" style="margin-left:10px;">
							<fieldset>
								<table>
									<tr>
										<td class="label"><label for="pseudo" class="inlinelabel">Pseudo :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="pseudo" name="pseudo" class="inputtext ui-corner-all" value="" size="20" /></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									<tr>
										<td class="label"><label for="email" class="inlinelabel">Email :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="email" name="email" class="inputtext ui-corner-all" value="" size="30" /></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									<tr>
										<td class="label"><label for="cryptpass" class="inlinelabel">Mot de passe :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="cryptpass" name="cryptpass" class="inputtext password ui-corner-all" value="" size="20" />
										<button id="randPassword" class="ud-button ui-state-default ui-corner-all">genere</button></td>
										<td class="errorInput"></td>
									 	<td class="status"></td>
									 </tr>
									 <tr>
										<td>
							  				<div class="password-meter">
							  					<div class="password-meter-message">&nbsp;</div>
							  					<div class="password-meter-bg">
								  					<div class="password-meter-bar"></div>
							  					</div>
							  				</div>
										</td>
									</tr>
									<tr>
										<td class="label"><label for="cryptpass_confirm">Confirm :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="cryptpass_confirm" name="cryptpass_confirm" class="inputtext ui-corner-all" value="" size="20" /></td>
										<td class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
						</form>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>