{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Upgrade Magix CMS</title>
</head>
<body>
<div id="page">
	<div id="content">
		<div id="install">
		{include file="common/top.phtml"}
		<div class="dashboard ui-widget-content ui-corner-all">
				<div class="dashboard-content">
					<div class="center-text-infos">
					<p style="text-align:center;">La mise à jour est nécessaire uniquement vers la version ayant reçu des modifications dans la base de données.</p>
					<div style="margin:2px auto 4px auto;padding:5px;width:600px;position:relative;text-align:center;" class="ui-state-highlight ui-corner-all">
					<p>Avant de commencer la mise à jour de votre base de données,
					faites une sauvegarde !</p>
					</div>
					<table class="tableversion ui-widget-content">
						<thead class="ui-widget-header">
							<tr>
								<td>Votre version</td>
								<td class="cell-icon"><span class="ui-icon ui-icon-arrowthick-1-e"></span></td>
								<td>Version Modifié</td>
								<td>Executer</td>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td>Version {$current_version}</td>
								<td><span class="ui-icon ui-icon-arrowthick-1-e"></span></td>
								<td>Version 2.3.43</td>
								<td>
									<form id="forms-update-version" action="" method="post">
										<input type="submit" class="submit" value="Executer" />
									</form>
								</td>
							</tr>
						</tbody>
					</table>
					</div>
				</div>
				{include file="common/footer.phtml"}
			</div>
		</div>
	</div>
</div>
{include file="common/javascript.phtml"}
</body>
</html>