{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Ajouter une news</a></div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'news']} eq 1}
						<form id="forms-news" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="n_title" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="n_title" name="n_title" class="inputtext ui-corner-all" value="" size="50" /></td>
									</tr>
									{$selectlang}
									<tr>
										<td class="label"><label for="n_content" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="n_content" class="fulltext mceEditor ui-corner-all" cols="" rows=""></textarea></td>
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jnews.0.2.js',function(){
		if (typeof ns_jnews == "undefined") {
		  console.log("ns_jnews is not defined");
		}else{
			ns_jnews.runAddNews();
		}
	});
});
</script>
</body>
</html>