{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Dashboard</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Les news</div>
					<div class="dashboard-content">
					{if $rewritenews eq 1 AND $perms eq 1}
						{widget_news limit="true" max=5 getpage=true}
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
					<div class="dashboard-content">
					{if $rewritenews eq 1 AND $perms eq 1}
					{$ptitle}
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter une réecriture des métas</div>
					<div class="dashboard-content">
					{if $rewritenews eq 1 AND $perms eq 1}
					<form id="forms-news" method="post" action="" style="margin-left:10px;">
					{$msg}
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="phrase1" class="inlinelabel">Phrase :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="phrase1" name="phrase1" class="inputtext ui-corner-all" value="{$uphrase1}" size="50" /></td>
								</tr>
								<tr>
									<td class="label"><label for="phrase2" class="inlinelabel">Phrase2 :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="phrase2" name="phrase2" class="inputtext ui-corner-all" value="{$uphrase2}" size="50" /></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Type :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idmetas" name="idmetas" value="{$uidmetas}" />
									<input type="text" disabled="disabled" readonly="readonly" id="umetas" name="umetas" class="inputdisabled ui-corner-all" value="{$umetas}" size="15" />
									</td>
								</tr>
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idlang" name="idlang" value="{$uidlang}" />
									<input type="text" disabled="disabled" readonly="readonly" id="codelang" name="codelang" class="inputdisabled ui-corner-all" value="{$ucodelang}" size="5" />
									</td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" name="snom" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
					</form>
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{include file="common/javascript.phtml"}
<script type="text/javascript" src="/min/?g=editor"></script>
</body>
</html>