{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Edition d'une news</div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'news']} eq true}
						<form id="forms-news-update" method="post" action="" style="margin-left:10px;">
						<div style="margin-right:5px;float:right;">
							<div class="block-preview ui-widget-content ui-corner-all">
								<a class="post-preview" href="#"><img src="/framework/img/preview/zoom_in.png" alt="Preview" /></a>
							</div>
						</div>
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td>
											<div class="radio_contener">
												<input type="radio" id="news_status_on" name="published" {if $published eq 1}checked="checked"{/if} value="1" /><label for="news_status_on">En ligne</label>
												<input type="radio" id="news_status_off" name="published" {if $published eq 0}checked="checked"{/if} value="0" /><label for="news_status_off">Hors ligne</label>
											</div>
										</td>
									</tr>
									<tr>
										<td class="label"><label for="newsurl" class="inlinelabel">Url :</label></td>
									</tr>
									<tr>
										<td>
											<input type="hidden" id="idnews" value="{$smarty.get.edit}" />
											<input type="text" id="newsurl" readonly="readonly" class="inputdisabled ui-corner-all" value="" size="60" />
										</td>
									</tr>
									<tr>
										<td class="label"><label for="n_title" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="n_title" name="n_title" class="inputtext ui-corner-all" value="{$n_title}" size="50" /></td>
									</tr>
									<tr>
										<td>
										<table>
											<tr>
												<td class="label"><label for="iso" class="inlinelabel">Langue :</label></td>
												<td class="label"><label for="n_uri" class="inlinelabel">URL simplifié :</label></td>
												<td></td>
											</tr>
											<tr>
												<td>
													<input type="text" disabled="disabled" readonly="readonly" id="iso" class="inputdisabled ui-corner-all" value="{$iso}" size="4" />
												</td>
												<td>
													<input type="text" id="n_uri" name="n_uri" class="inputdisabled ui-corner-all" value="{$n_uri}" size="51" />
												</td>
												<td>
													<a class="unlocked" title="Editer l'url simplifié" href="#"><span class="lfloat magix-icon magix-icon-lock"></span></a>
												</td>
											</tr>
										</table>
										</td>
									</tr>
									<tr>
										<td class="label"><label for="n_content" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="n_content" id="n_content" class="fulltext mceEditor ui-corner-all" cols="" rows="">{$n_content}</textarea></td>
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-image"></span>Joindre une image</div>
						<div class="dashboard-widget-content">
							<div style="margin:0 2em;">
								<div id="load_news_img">
									<div id="contener_image"></div>
								</div>
							</div>
							<form method="post" action="" enctype="multipart/form-data" id="forms-news-image-update">
								<fieldset>
									<table>
										<tr>
											<td class="label"><label for="n_image">Image :</label></td>
											<td>
												<input type="hidden" name="MAX_FILE_SIZE" value="1048576" />
										 		<input type="file" id="n_image" name="n_image" value="" />
										 	</td>
										 	<td><input type="submit" value="Envoyer" /></td>
									 	</tr>
								 	</table>
								</fieldset>
							</form>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-tag-plus"></span>Ajouter des tags</div>
						<div class="dashboard-widget-content">
							{include file="news/forms/addtagnews.phtml"}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
<div id="confirm_del" style="display:none;">
	<p>Etes-vous sur de vouloir supprimer cet élément ?</p>
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jnews.0.2.min.js',function(){
		if (typeof ns_jnews == "undefined") {
		  console.log("ns_jnews is not defined");
		}else{
			ns_jnews.runEditNews($("#idnews").val());
		}
	});
});
</script>
</body>
</html>