{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Ajouter</div>
					<div class="dashboard-content">
					{if $confignews eq 1}
					<form id="forms-news-update" method="post" action="" style="margin-left:10px;">
					<div style="margin:5px;float:right;">
						<a class="post-preview fg-button ui-state-default fg-button-icon-left ui-corner-all" href="{$view}">Preview</a>
					</div>
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="subject" class="inlinelabel">Url :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idnews" value="{$smarty.get.edit}" />
									<input type="text" disabled="disabled" readonly="readonly" id="url" name="url" class="inputdisabled ui-corner-all" value="{$url}" size="50" /></td>
									<td></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="subject" class="inlinelabel">Titre :</label></td>
								</tr>
								<tr>
									<td><input type="text" id="subject" name="subject" class="inputtext ui-corner-all" value="{$subject}" size="50" /></td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{if $idlang != 0}
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
								</tr>
								<tr>
									<td>
									<input type="hidden" id="idlang" name="idlang" value="{$idlang}" />
									<input type="text" disabled="disabled" readonly="readonly" id="codelang" name="codelang" class="inputdisabled ui-corner-all" value="{$codelang}" size="5" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{/if}
								<tr>
									<td>
									<table>
									<tr>
										<td style="width:100px;" class="label"><label for="publish" class="inlinelabel">Publication :</label></td>
										<td style="width:80px;">
											Activer <input type="radio" name="publish" {if $publish eq 1}checked="checked"{/if} value="1" />
										</td>
										<td>
											Désactiver <input type="radio" name="publish" {if $publish eq 0}checked="checked"{/if} value="0" />
										</td>
									</tr>
									</table>
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="content" class="inlinelabel">Contenu :</label></td>
								</tr>
								<tr>
									<td><textarea name="content" class="fulltext mceEditor ui-corner-all" cols="" rows="">{$content}</textarea></td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" name="snom" class="ud-button ui-state-default ui-corner-all" value="envoyer" /></div>
					</form>
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript" src="/min/?g=editor"></script>
</body>
</html>