{script src="/{baseadmin}/min/?f={baseadmin}/template/js/mc_config.js" type="javascript"}
<script type="text/javascript">
$(function(){
    if (typeof MC_config == "undefined")
    {
        console.log("MC_config is not defined");
    }else{
        {if $smarty.get.tab}
        {if $smarty.get.tab eq 'editor'}
            MC_config.runEditor();
        {elseif $smarty.get.tab eq 'imagesize'}
            MC_config.runImages();
        {/if}
        {else}
            MC_config.runConfig();
        {/if}
    }
});
</script>