<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">Home</a></li>
                    <li><a href="/{baseadmin}/config.php">Paramètres</a></li>
                    <li><a href="/{baseadmin}/config.php?tab=editor">Editeur</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>