<div id="sidebar" class="span3">
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
        {* -- START PAGES -- *}
            <li class="nav-header">Pages</li>
            <li>
                <a href="#home" class="showit{if {script_name} eq "home"} open{/if}">
                    <span class="icon-plus"></span> Page d'accueil
                </a>
                <div class="collapse-item{if {script_name} eq "home"} on{/if}" id="home">
                    <ul>
                        <li>
                            <a href="/{baseadmin}/home.php?action=list"><span class="icon-list-ul"></span> Liste</a>
                        </li>
                        <li>
                            <a href="/{baseadmin}/home.php"><span class="icon-bar-chart"></span> Statistiques</a>
                        </li>
                    </ul>
                </div>
            </li>
            {if $config_cms eq 1}
            <li>
                <a href="#cms" class="showit{if {script_name} eq "cms"} open{/if}">
                    <span class="icon-plus"></span> Pages
                </a>
                <div class="collapse-item{if {script_name} eq "cms"} on{/if}" id="cms">
                    <ul>
                        {foreach $array_lang as $key => $value nocache}
                        <li>
                            <a href="/{baseadmin}/cms.php?getlang={$key}&amp;action=list">
                                <span><img src="/{baseadmin}/template/img/flags/{$value}.png" alt="{$value}" /> {$value|upper}</span>
                            </a>
                        </li>
                        {/foreach}
                        <li class="divider"></li>
                        <li>
                            <a href="/{baseadmin}/cms.php"><span class="icon-bar-chart"></span> Statistiques</a>
                        </li>
                    </ul>
                </div>
            </li>
            {/if}
        {* -- END PAGES -- *}
        </ul>
        {if $config_news eq 1}
        <ul class="nav nav-list">
        {* -- START NEWS -- *}
            <li class="nav-header">Actualités</li>
            <li>
                <a href="#news" class="showit{if {script_name} eq "news"} open{/if}">
                    <span class="icon-plus"></span> Articles
                </a>
                <div class="collapse-item{if {script_name} eq "news"} on{/if}" id="news">
                    <ul>
                        {foreach $array_lang as $key => $value nocache}
                        <li>
                            <a href="/{baseadmin}/news.php?getlang={$key}&amp;action=list">
                                <span><img src="/{baseadmin}/template/img/flags/{$value}.png" alt="{$value}" /> {$value|upper}</span>
                            </a>
                        </li>
                        {/foreach}
                        <li class="divider"></li>
                        <li>
                            <a href="/{baseadmin}/news.php"><span class="icon-bar-chart"></span> Statistiques</a>
                        </li>
                    </ul>
                </div>
            </li>
        {* -- END NEWS -- *}
        </ul>
        {/if}
        {if $config_catalog eq 1}
        <ul class="nav nav-list">
        {* -- START CATALOG -- *}
            <li class="nav-header">Catalogue</li>
            <li>
                <a href="#catalog-category" class="showit{if {script_name} eq "catalog:category"} open{/if}">
                    <span class="icon-plus"></span> Catégories
                </a>
                <div class="collapse-item{if {script_name} eq "catalog:category" OR  {script_name} eq "catalog:subcategory"} on{/if}" id="catalog-category">
                    <ul>
                        {foreach $array_lang as $key => $value nocache}
                        <li>
                            <a href="/{baseadmin}/catalog.php?section=category&amp;getlang={$key}">
                                <span><img src="/{baseadmin}/template/img/flags/{$value}.png" alt="{$value}" /> {$value|upper}</span>
                            </a>
                        </li>
                        {/foreach}
                    </ul>
                </div>
            </li>
            <li>
                <a href="#catalog-product" class="showit{if {script_name} eq "catalog:product"} open{/if}">
                    <span class="icon-plus"></span> Produits
                </a>
                <div class="collapse-item{if {script_name} eq "catalog:product"} on{/if}" id="catalog-product">
                    <ul>
                    {foreach $array_lang as $key => $value nocache}
                        <li>
                            <a href="/{baseadmin}/catalog.php?section=product&amp;getlang={$key}">
                                <span><img src="/{baseadmin}/template/img/flags/{$value}.png" alt="{$value}" /> {$value|upper}</span>
                            </a>
                        </li>
                    {/foreach}
                    </ul>
                </div>
            </li>
        {* -- END CATALOG -- *}
        </ul>
        {/if}
    </div>
    {if $config_plugins eq 1}
    <div class="well sidebar-nav">
        <ul class="nav nav-list">
        {* -- START PLUGINS -- *}
            <li class="nav-header">Plugins</li>
            {widget_plugins_nav}
        {* -- END NEWS -- *}
        </ul>
    </div>
    {/if}
</div>