{doctype type="HTML5"}
<head>
    <meta charset="UTF-8" />
    {headmeta meta="contentType" content="html" charset="utf8"}
    <base href="{geturl}/">
    <meta name="dcterms.language" content="fr" />
    <meta name="dcterms.creator" content="Magix CMS" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {headmeta meta="keywords" content=""}
    {headmeta meta="robots" content="noindex,nofollow"}
    <link rel="icon" type="image/png" href="/framework/img/favicon.png" />
    <!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="/framework/img/favicon.ico" /><![endif]-->
{include file="section/css.phtml"}