{script src="/{baseadmin}/min/?g=adminjs,jimagine" type="javascript"}
<script type="text/javascript">
    var editor_version = "{$smarty.const.VERSION_EDITOR}";
    var baseadmin = "{baseadmin}";
    $(function(){
        // Dialog
        $('#dialog').dialog({
            autoOpen: false,
            width: 600,
            buttons: {
                "Ok": function () {
                    $(this).dialog("close");
                },
                "Cancel": function () {
                    $(this).dialog("close");
                }
            }
        });
        // Dialog Link
        $('#dialog_link').click(function () {
            $('#dialog').dialog('open');
            return false;
        });
    });
</script>