<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="{geturl}/{baseadmin}/">Magix CMS</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    {if {role_admin items='administrator'}}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-cogs"></span> Configuration <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/{baseadmin}/config.php"><span class="icon-cog"></span> Paramètres</a></li>
                            <li><a href="/{baseadmin}/config.php?tab=editor"><span class="icon-list-alt"></span> Editeur wysiwyg</a></li>
                            <li><a href="/{baseadmin}/config.php?tab=imagesize"><span class="icon-picture"></span> Tailles des images</a></li>
                            <li><a href="/{baseadmin}/config.php?tab=cache"><span class="icon-folder-open-alt"></span> Gestion du cache</a></li>
                        </ul>
                    </li>
                    {/if}
                    <li{if {script_name} eq "users"} class="active"{/if}><a href="/{baseadmin}/users.php"><span class="icon-user"></span> Utilisateurs</a></li>
                    {if {role_admin items='administrator'}}
                    <li{if {script_name} eq "theming"} class="active"{/if}><a href="/{baseadmin}/theming.php"><span class="icon-columns"></span> Thèmes</a></li>
                    {/if}
                    <li{if {script_name} eq "lang"} class="active"{/if}><a href="/{baseadmin}/lang.php"><span class="icon-flag"></span> Langues</a></li>
                    {if {role_admin items='administrator'}}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="icon-wrench"></span> Outils <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/{baseadmin}/seo.php"><span class="icon-bolt"></span> SEO</a></li>
                            <li><a href="/{baseadmin}/googletools.php"><span class="icon-google-plus-sign"></span> Google Tools</a></li>
                            <li><a href="/{baseadmin}/sitemap.php"><span class="icon-sitemap"></span> Sitemap</a></li>
                        </ul>
                    </li>
                    {/if}
                </ul>
                <p class="navbar-text pull-right">
                    <a href="{geturl}/admin/dashboard.php?acsclose" class="navbar-link">Logout</a>
                </p>
            </div>
        </div>
    </div>
</div>