<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="brand" href="{geturl}/{baseadmin}/">Magix CMS</a>
            <ul class="nav">
                <li class="active"><a href="#">Home</a></li>
                <li><a href="#">Link</a></li>
                <li><a href="#">Link</a></li>
            </ul>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    <a href="{geturl}/admin/dashboard.php?acsclose" class="navbar-link">Logout</a>
                </p>
            </div>
        </div>
    </div>
</div>