<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">Magix CMS</a>
            <div class="nav-collapse collapse">
                <p class="navbar-text pull-right">
                    <a href="{geturl}/admin/dashboard.php?acsclose" class="navbar-link">Logout</a>
                </p>
                <ul class="nav">
                    <li class="active"><a href="{geturl}/admin/">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>