<div class="row-fluid">
    <h3>Public</h3>
    <div class="block-row span10">
        <span class="span7">
            <span class="badge">1</span> {#block_public_info_cache#}
        </span>
        <span class="span1">
            <a href="#" id="public_caches" class="btn clear-cache">
                <span class="icon-trash"></span>
            </a>
        </span>
    </div>
    <div class="block-row span10">
        <span class="span7">
            <span class="badge badge-inverse">2</span> {#block_public_info_minify#}
        </span>
        <span class="span1">
            <a href="#" id="public_minify" class="btn clear-cache">
                <span class="icon-trash"></span>
            </a>
        </span>
    </div>
    <div class="clearfix"></div>
    <h3>Administration</h3>
    <div class="block-row span10">
        <span class="span7">
            <span class="badge">1</span> {#block_admin_info_cache#}
        </span>
        <span class="span1">
            <a href="#" id="admin_caches" class="btn clear-cache">
                <span class="icon-trash"></span>
            </a>
        </span>
    </div>
    <div class="block-row span10">
        <span class="span7">
            <span class="badge badge-inverse">2</span> {#block_admin_info_minify#}
        </span>
        <span class="span1">
            <a href="#" id="admin_minify" class="btn clear-cache">
                <span class="icon-trash"></span>
            </a>
        </span>
    </div>
</div>