{if $smarty.get.tab eq "image"}
    <form id="forms_catalog_product_image" method="post" action="" enctype="multipart/form-data">
        <p>
            <input type="hidden" name="MAX_FILE_SIZE" value="2048576" />
            <input type="file" id="imgcatalog" name="imgcatalog" value="" />
            <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
        </p>
    </form>
    <div id="load_catalog_product_img">
        <div id="contener_image"></div>
    </div>
{elseif $smarty.get.tab eq "category"}
<form id="forms_catalog_product_category" class="form-inline" method="post" action="">
    <select id="idclc" name="idclc">
        {foreach $array_list_category as $key => $value nocache}
            <option value="{$key}">{$value}</option>
        {/foreach}
    </select>
    <select id="idcls" name="idcls">
        <option value="">{#select_subcategory#|ucfirst}</option>
    </select>
    <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
</form>
<div id="list_product_category"></div>
{elseif $smarty.get.tab eq "product"}
<form id="forms_catalog_product_related" class="form-inline" method="post" action="">
    <div class="input-append">
        <input class="input-xlarge" id="titleproduct" type="text">
        <span class="add-on">
            <span class="icon-search"></span>
        </span>
    </div>
</form>
<div id="list_product_rel"></div>
{elseif $smarty.get.tab eq "galery"}
    <form id="forms_catalog_product_galery" method="post" action="" enctype="multipart/form-data">
        <p>
            <input type="hidden" name="MAX_FILE_SIZE" value="2048576" />
            <input type="file" id="imgcatalog" name="imgcatalog" value="" />
            <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
        </p>
    </form>
    <div id="load_catalog_product_galery"></div>
{else}
    <form id="forms_catalog_product_edit" method="post" action="">
        <p class="pull-left">
            <label for="iso">ISO</label>
            <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
        </p>
        <p class="controls-row offset1 input-append">
            <label for="urlcatalog">{#url_rewriting#|ucfirst}</label>
            <input type="text" class="input-xlarge" id="urlcatalog" name="urlcatalog" readonly="readonly" size="30" value="{$urlcatalog}" />
            <a class="unlocked" href="#">
                <span class="add-on icon-lock"></span>
            </a>
        </p>
        <div class="clearfix"></div>
        <p>
            <label for="titlecatalog">{#label_name_product#|ucfirst} :</label>
            <input type="text" class="input-xlarge" id="titlecatalog" name="titlecatalog" value="{$titlecatalog}" size="50" />
        </p>
        <p>
            <label for="price">{#label_price#|ucfirst} :</label>
            <input type="text" class="input-small" id="price" name="price" value="{$price}" size="10" />
        </p>
        <p>
            <label for="desccatalog" class="inlinelabel">{#label_content#|ucfirst} :</label>
            <textarea name="desccatalog" id="desccatalog" class="mceEditor">{$desccatalog}</textarea>
        </p>
        <p>
            <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
        </p>
    </form>
{/if}