{include file="section/head.phtml"}
{headmeta meta="googleSiteVerification" content="{google_tools tools='webmaster'}"}
{headmeta meta="description" content="{static_metas param='' dynamic=$seoDescr_home}"}
<title>{static_metas param='' dynamic=$seoTitle_home}</title>
{include file="section/css.phtml"}
</head>
<body id="home">
<div id="page" class="container">
{include file="section/header.phtml"}
    <div id="content" class="row">
    {include file="section/sidebar.phtml"}
        <div id="article" class="span9">
            <div id="article-inner" class="span8">
                <h1>{$name_home}</h1>
                {$content_home}
                {widget_cms_display}
            </div>
        </div>
        <div class="clear">&nbsp;</div>
    </div>
{include file="section/footer.phtml"}
</div>
{include file="section/foot.phtml"}
</body>
</html>