{include file="section/head.phtml"}
{headmeta meta="googleSiteVerification" content="{google_tools tools='webmaster'}"}
{nocache}{headmeta meta="description" content="{static_metas param='' dynamic=$seoDescr_home}"}{/nocache}
<title>{nocache}{static_metas param='' dynamic=$seoTitle_home}{/nocache}</title>
{include file="section/css.phtml"}
</head>
<body id="home">
<div id="page" class="container">
{include file="section/header.phtml"}
    <div id="content" class="row">
    {include file="section/sidebar.phtml"}
        <div id="article" class="span9">
            <div id="article-inner" class="span8">
                <h1>{nocache}{$name_home}{/nocache}</h1>
                {nocache}
                {$content_home}
                {widget_cms_display
                    conf = [
                        'level' => 'parent'
                    ]
                }
                {/nocache}
            </div>
        </div>
        <div class="clear">&nbsp;</div>
    </div>
{include file="section/footer.phtml"}
</div>
{include file="section/foot.phtml"}
</body>
</html>