{include file="common/header.phtml" section="prepend"}
<meta name="description" content="{static_metas param={#seo_d_static_plugin_contact#}}" />
    <title>{static_metas param={#seo_t_static_plugin_contact#}}</title>
{include file="common/css.phtml"}
</head>
<body>
<div id="page">
{include file="common/top.phtml"}
<div id="content">
{include file="common/sidebar.phtml"}
	<div id="principal" class="principal">
	<h1>Formulaire de contact</h1>
	<p>Vie privée :  Nous tenons à la protection de votre vie privée. Nous traitons vos données de manière confidentielle et nous vous garantissons que celles-ci ne seront pas transmises à des tiers.</p>
	<p>Attention : Tous les champs marqués * sont obligatoires !</p>
		<form class="forms-profil" method="post" action="" id="profil-nom">
		{$msg}
		<fieldset>
			<table>
				<tr>
					<td class="label"><label for="nom" class="inlinelabel">Nom :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="nom" name="nom" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="prenom" class="inlinelabel">Prenom :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="prenom" name="prenom" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="email" class="inlinelabel">Courriel :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="email" name="email" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="" size="40" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="tel" class="inlinelabel">Téléphone :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="tel" name="tel" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="adresse" class="inlinelabel">Adresse :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="adresse" name="adresse" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="" size="40" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="programme" class="inlinelabel">Je suis intéressé(e) par votre programme :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="programme" name="programme" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="{$smarty.post.moreinfo}" size="40" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="programme" class="inlinelabel">Je suis intéressé(e) par un voyage sur mesure :</label></td>
				</tr>
				<tr>
					<td>
					{$select_category_cms}
					</td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="depart" class="inlinelabel">Départ :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="depart" name="depart" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="duree" class="inlinelabel">Durée :</label></td>
				</tr>
				<tr>
					<td><input type="text" id="duree" name="duree" style="background:white;" class="inputtext ui-widget-content ui-corner-all" value="" size="20" /></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="nbrpersonnes" class="inlinelabel">Nombre de personne(s) :</label></td>
				</tr>
				<tr>
					<td>
					<select name="nbrpersonnes" id="nbrpersonnes" class="select">
						<option value="1">1</option>
						<option value="2">2</option>
						<option value="3">3</option>
						<option value="4">4</option>
						<option value="5">5</option>
						<option value="6">6</option>
						<option value="7">7</option>
						<option value="8">8</option>
						<option value="9">9</option>
						<option value="10">10</option>
						<option value="+10">+10</option>
					</select>
					</td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td class="label"><label for="message" class="inlinelabel">Message :</label></td>
				</tr>
				<tr>
					<td><textarea id="message" name="message" style="background:white;" class="fulltext ui-widget-content ui-corner-all" rows="10" cols="40"></textarea></td>
					<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				<tr>
					<td><input type="submit" name="snom" class="fg-button ui-state-default ui-corner-all" value="envoyer" /></td>
				</tr>
			</table>
		</fieldset>
		</form>
	</div>
</div>
{include file="common/footer.phtml"}
</body>
</html>