{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                {include file="catalog/section/nav.phtml"}
                    <h1>Edition de la catégorie {$idclc}</h1>

                    <ul class="nav nav-tabs clearfix">
                        <li{if !$smarty.get.tab} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&action=edit&edit={$smarty.get.edit}">Texte</a>
                        </li>
                        <li{if $smarty.get.tab eq "image"} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&action=edit&edit={$smarty.get.edit}&tab=image">Image</a>
                        </li>
                        <li{if $smarty.get.tab eq "subcat"} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&action=edit&edit={$smarty.get.edit}&tab=subcat">Sous catégories</a>
                        </li>
                        <li{if $smarty.get.tab eq "product"} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&action=edit&edit={$smarty.get.edit}&tab=product">Produits</a>
                        </li>
                    </ul>
                    <div class="mc-message"></div>
                    {include file="catalog/category/forms/edit.phtml"}
                </div>
            </div>
        </div>
    </div>
</div>
{if $smarty.get.tab eq "subcat"}
<div id="forms-add" class="hide" title="Ajouter une sous catégorie">
    {include file="catalog/subcategory/forms/add.phtml"}
</div>
{else}
<div id="forms-add" class="hide" title="Ajouter une catégorie">
    {include file="catalog/category/forms/add.phtml"}
</div>
{/if}
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="catalog/section/js.phtml"}
</body>
</html>