{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                {include file="catalog/section/nav.phtml"}
                    <h1>{#editing_the_category#|ucfirst} : {$clibelle}</h1>

                    <ul class="nav nav-tabs clearfix">
                        <li{if !$smarty.get.tab} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&amp;action=edit&amp;edit={$smarty.get.edit}">{#text#|ucfirst}</a>
                        </li>
                        <li{if $smarty.get.tab eq "image"} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&amp;action=edit&amp;edit={$smarty.get.edit}&amp;tab=image">Image</a>
                        </li>
                        <li{if $smarty.get.tab eq "subcat"} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&amp;action=edit&amp;edit={$smarty.get.edit}&amp;tab=subcat">{#subcategory#|ucfirst}</a>
                        </li>
                        <li{if $smarty.get.tab eq "product"} class="active"{/if}>
                            <a href="/admin/catalog.php?section={$smarty.get.section}&amp;getlang={$smarty.get.getlang}&amp;action=edit&amp;edit={$smarty.get.edit}&amp;tab=product">{#products#|ucfirst}</a>
                        </li>
                    </ul>
                    <div class="mc-message clearfix"></div>
                    {include file="catalog/category/forms/edit.phtml"}
                </div>
            </div>
        </div>
    </div>
</div>
{if $smarty.get.tab eq "subcat"}
<div id="forms-add" class="hide" title="{#add_a_subcategory#|ucfirst}">
    {include file="catalog/subcategory/forms/add.phtml"}
</div>
{else}
<div id="forms-add" class="hide" title="{#add_a_category#|ucfirst}">
    {include file="catalog/category/forms/add.phtml"}
</div>
{/if}
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="catalog/section/js.phtml"}
</body>
</html>