<form id="forms_user_add" method="post" action="">
    <p class="control-group">
        <input type="text" placeholder="Nom d'utilisateur" class="input-large" id="pseudo" name="pseudo" value="" size="50" />
    </p>
    <p class="control-group">
        <input type="text" placeholder="Email" class="input-large" id="email" name="email" value="" size="50" />
    </p>
    <p class="control-group">
    {$role_select}
    </p>
    <p class="control-group">
        <input type="password" placeholder="Mot de passe" class="input-large" id="cryptpass" name="cryptpass" value="" size="50" />
    </p>
    <p class="control-group">
        <input type="password" placeholder="Confirmer le mot de passe" class="input-large" id="cryptpass_confirm" name="cryptpass_confirm" value="" size="50" />
    </p>
</form>