<div class="row-fluid">
    <div class="span4">
        <h3>Données utilisateur</h3>
        <form id="forms_user_data_edit" method="post" action="">
            <p class="control-group">
                <input type="text" placeholder="Nom d'utilisateur" class="input-large" id="pseudo" name="pseudo" value="{$pseudo}" size="50" />
            </p>
            <p class="control-group">
                <input type="text" placeholder="Email" class="input-large" id="email" name="email" value="{$email}" size="50" />
            </p>
            <p class="control-group">
                {$role_select}
            </p>
            <p>
                <input type="submit" class="btn" />
            </p>
        </form>
    </div>
    <div class="span5">
        <h3>Changement de mot de passe</h3>
        <form id="forms_user_password_edit" method="post" action="">
            <p class="control-group">
                <input type="password" placeholder="Mot de passe" class="input-large" id="cryptpass" name="cryptpass" value="" size="50" />
            </p>
            <p class="control-group">
                <input type="password" placeholder="Confirmer le mot de passe" class="input-large" id="cryptpass_confirm" name="cryptpass_confirm" value="" size="50" />
            </p>
            <p>
                <input type="submit" class="btn" />
            </p>
        </form>
    </div>
</div>