{if $editor eq "tinymce"}
	{if $configcatalog eq 1}
	<script type="text/javascript">
		var catalog_tinymce_plugin = ",productsearch";
		var catalog_tinymce_button = ",productsearch";
	</script>
	{else}
	<script type="text/javascript">
		var catalog_tinymce_plugin = "";
		var catalog_tinymce_button = "";
	</script>
	{/if}
	{if $manager_setting eq 'imagemanager'}
	<script type="text/javascript">
		var manager_tinymce_plugin = ",imagemanager";
		var manager_tinymce_button = ",insertimage";
		var tinymce_call_back = "";
	</script>
	{elseif $manager_setting eq 'pdw_file_browser'}
	<script type="text/javascript">
		var manager_tinymce_plugin = "";
		var manager_tinymce_button = "";
		var tinymce_call_back = "filebrowser";
	</script>
	{/if}
	{if $tinymce_filemanager eq 1}
	<script type="text/javascript">
		var filemanager_tinymce_plugin = ",filemanager";
		var filemanager_tinymce_button = ",insertfile";
	</script>
	{else}
	<script type="text/javascript">
		var filemanager_tinymce_plugin = "";
		var filemanager_tinymce_button = "";
	</script>
	{/if}
<script type="text/javascript" src="/min/?f=framework/js/backend/tinymce-config.js"></script>
{elseif $editor eq "ckeditor"}
{if $manager_setting eq 'pdw_file_browser'}
	<script type="text/javascript">
		var manager_filebrowserBrowseUrl = '/framework/js/ckeditor/plugins/pdw_file_browser/index.php?editor=ckeditor';
		var manager_filebrowserImageBrowseUrl = '/framework/js/ckeditor/plugins/pdw_file_browser/index.php?editor=ckeditor&filter=image';
	</script>
{/if}
<script type="text/javascript" src="/framework/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/min/?f=framework/js/backend/ckeditor-config.js"></script>
{/if}