<div id="dialog" style="display:none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	Etes-vous sur de vouloir supprimer cet élément ?</p>
	<div class="reqdialog"></div>
</div>
<div id="window-box"></div>
<div id="footer" class="lfoot ui-widget ui-widget-content">
&copy; <a href="http://www.logiciel-referencement-professionnel.com/" class="targetblank strong">Magix CMS</a> 2009 - 2010<br />
propulsé par <a href="http://magix-cjquery.com" class="targetblank strong">Magix cjQuery</a> partenaire officiel de 
<a href="http://www.web-solution-way.be" class="targetblank strong">Web Solution Way</a> spécialiste en <a href="http://www.web-solution-way.be/referencement_de_site.html" class="targetblank strong">référencement de site</a>
</div> 
{* {notify_dir_header} *}