{doctype type="XHTML1_STRICT"}
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr">
  <head>
    {headmeta meta="contentType" content="html" charset="utf8"}
    {headmeta meta="contentStyleType" content="css"}
    {headmeta meta="contentLanguage" content="fr"}
    {headmeta meta="DC.Language" content="fr"}
    {headmeta meta="DC.Creator" content="web-solution-way.be"}
    {headmeta meta="generator" content="Magix CMS"}
    {headmeta meta="keywords" content=""}
    {headmeta meta="robots" content="noindex,nofollow"}
	<link rel="icon" type="image/png" href="/framework/img/favicon.png" />
	<!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="/framework/img/favicon.ico" /><![endif]-->
	{include file="common/styles.phtml"}