<div id="topmicrobar">
	<ul class="topbar-tools">
		<li class="topbutton ui-widget-content ui-corner-all"><a href="{geturl}/admin/dashboard.php?acsclose"><span style="float:left;" class="magix-icon magix-icon-shutdown" title="Quit Magix CMS"></span></a></li>
		<li class="topbutton ui-widget-content ui-corner-all"><a class="targetblank" href="http://documentation.logiciel-referencement-professionnel.com/"><span style="float:left;" class="magix-icon magix-icon-help" title="Aide Magix CMS"></span></a></li>
	</ul>
</div>