{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Ajouter une page CMS</a></div>
						<div class="dashboard-widget-content">
						{if $configcms eq 1}
						<form id="forms-cms-page" method="post" action="" style="margin-left:10px;">
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="subjectpage" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="subjectpage" name="subjectpage" class="inputtext ui-corner-all" value="" size="50" /></td>
									</tr>
									{$selectlang}
									<tr>
										<td class="label"><label for="idcategory" class="inlinelabel">Catégorie :</label></td>
									</tr>
									<tr>
										<td>
											<select id="idcategory" name="idcategory">
												<option value="">Aucune catégorie</option>
											</select>
										</td>
									</tr>
									<tr>
										<td class="label"><label for="contentpage" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="contentpage" id="contentpage" class="fulltext mceEditor ui-corner-all" cols="" rows=""></textarea></td>
									</tr>
								</table>			
							</fieldset>
							<div id="showmetas" class="fg-button ui-state-default fg-button-icon-left ui-corner-all"><span style="float:left;"></span> Voir les métas</div>
								<div id="metas">
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="metatitle" class="inlinelabel">Title :</label></td>
									</tr>
									<tr>
										<td>
											<textarea id="metatitle" name="metatitle" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
											<div id="charactersLeftT" class="wrap">120</div>
										</td>
									</tr>
									<tr>
										<td class="label"><label for="metadescription" class="inlinelabel">Description :</label></td>
									</tr>
									<tr>
										<td>
										<textarea name="metadescription" id="metadescription" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2"></textarea>
										<div id="charactersLeftD" class="wrap">180</div>
										</td>
									</tr>
								</table>
								</div>
							<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Chercher une page CMS</a></div>
						<div class="dashboard-widget-content">
						{include file="cms/search.phtml"}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/jcms.1.1.js');
	dynamical_select_json(
		'#forms-cms-page',
		'/admin/cms.php?add&json=true',
		['idlang','idcategory']
	);
});
</script>
</body>
</html>