{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Edition d'une page</div>
						<div class="dashboard-widget-content">
						{if $configcms eq 1}
						<form id="forms-cms-updatepage" method="post" action="" style="margin-left:10px;">
						<div style="margin:5px;float:right;">
							<a class="post-preview fg-button ui-state-default fg-button-icon-left ui-corner-all" href="{$view}">Preview</a>
						</div>
							<fieldset>
								<table class="table-tinymce">
									<tr>
										<td class="label"><label for="subjectpage" class="inlinelabel">Titre :</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" id="idpage" value="{$smarty.get.editcms}" />
										<input type="text" id="subjectpage" name="subjectpage" class="inputtext ui-corner-all" value="{$subjectpage}" size="50" /></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									{if $idlang != 0}
									<tr>
										<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" id="idlang" name="idlang" value="{$idlang}" />
										<input type="text" disabled="disabled" readonly="readonly" id="codelang" name="codelang" class="inputdisabled ui-corner-all" value="{$codelang}" size="5" />
										</td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									{else}
									<tr>
										<input type="hidden" id="idlang" name="idlang" value="{$idlang}" />
									</tr>
									{/if}
									{if $idcategory != 0}
									<tr>
										<td class="label"><label for="idlang" class="inlinelabel">Catégorie :</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" id="idcategory" name="idcategory" value="{$idcategory}" />
										<input type="text" disabled="disabled" readonly="readonly" id="category" name="category" class="inputdisabled ui-corner-all" value="{$category}" size="25" />
										</td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									{/if}
									<tr>
										<td class="label"><label for="contentpage" class="inlinelabel">Contenu :</label></td>
									</tr>
									<tr>
										<td><textarea name="contentpage" id="contentpage" class="fulltext mceEditor ui-corner-all" cols="" rows="">{$contentpage}</textarea></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
								</table>			
							</fieldset>
							<div id="showmetas" class="fg-button ui-state-default fg-button-icon-left ui-corner-all"><span style="float:left;"></span> Voir les métas</div>
								<div id="metas">
								<table>
									<tr>
										<td class="label"><label for="metatitle" class="inlinelabel">Title :</label></td>
									</tr>
									<tr>
										<td>
											<textarea id="metatitle" name="metatitle" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2">{$metatitle}</textarea>
											<div id="charactersLeftT" class="wrap">120</div>
										</td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
									<tr>
										<td class="label"><label for="metadescription" class="inlinelabel">Description :</label></td>
									</tr>
									<tr>
										<td>
											<textarea name="metadescription" id="metadescription" class="ui-input ui-widget-content ui-corner-all" cols="70" rows="2">{$metadescription}</textarea>
											<div id="charactersLeftD" class="wrap">180</div>
										</td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="status"></td>
									</tr>
								</table>
								</div>
							<div style="margin:5px;"><input type="submit" /></div>
						</form>
						{else}
							<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
							<span style="float:left;" class="ui-icon ui-icon-alert"></span>
								Vous n'avez pas la permission d'administrer ce module
							</div>
							{/if}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
</body>
</html>