{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">CMS</a></div>
						<div class="dashboard-widget-content">
						{if {admin_level_config config_param=['module'=>'cms']} eq 1}
							{widget_cms limit="true" max=20 getpage=true}
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
							<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Chercher une page CMS</a></div>
						<div class="dashboard-widget-content">
						{include file="cms/search.phtml"}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/jcms.1.1.js');
});
</script>
</body>
</html>