{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane config_param=['level1'=>'langue','level2'=>'parent']}</ul></div>
				</div>
				{if {admin_level_config config_param=['module'=>'cms']} eq 1}
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-flash-plus"></span>Ajouter une page parente rapide</div>
						<div class="dashboard-widget-content">
							{include file="cms/forms/add_page_p.phtml"}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span class="lfloat magix-icon magix-icon-magnifier"></span> Chercher une page CMS</div>
						<div class="dashboard-widget-content">
						{include file="cms/forms/search.phtml"}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="magix-icon magix-icon-locale"></span> Langues CMS</div>
						<div class="dashboard-widget-content">
							{$list_language}
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><a href="#" class="dashboard-open">Statistiques</a></div>
						<div class="dashboard-widget-content">
							<div id="chart-google-page"></div>
						</div>
					</div>
				</div>
				{else}
				<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
					Vous n'avez pas la permission d'administrer ce module
				</div>
				{/if}
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
{include file="common/editor.phtml"}
{script src="/min/?f=framework/js/tools/jquery.jqplot.min.js,framework/js/tools/jqplot-plugins/jqplot.barRenderer.min.js,/framework/js/tools/jqplot-plugins/jqplot.categoryAxisRenderer.min.js,framework/js/tools/jqplot-plugins/jqplot.pointLabels.min.js" type="javascript"}
{literal}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/ns/jcms.0.2.js',function(){
		if (typeof ns_jcms == "undefined") {
		  console.log("ns_jcms is not defined");
		}else{
			ns_jcms.run();
		}
	});
});
</script>
{/literal}
</body>
</html>