{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Déplacer une page CMS</div>
					<div class="dashboard-content">
					{if $configcms eq 1}
					<form id="move-cms-page" method="post" action="" style="margin-left:10px;">
						<fieldset>
							<table>
								<tr>
									<td class="label"><label for="idpage" class="inlinelabel">Identifiant :</label></td>
								</tr>
								<tr>
									<td><input type="text" disabled="disabled" readonly="readonly" id="idpage" name="idpage" class="inputtext ui-corner-all" value="{$idpage}" size="50" /></td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								<tr>
									<td class="label"><label for="titlecatalog" class="inlinelabel">Titre :</label></td>
								</tr>
								<tr>
									<td><input type="text" disabled="disabled" readonly="readonly" id="subjectpage" name="subjectpage" class="inputtext ui-corner-all" value="{$subjectpage}" size="50" /></td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{if $idcategory != 0}
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Catégorie :</label></td>
								</tr>
								<tr>
									<td>
									<input type="text" disabled="disabled" readonly="readonly" id="category" name="category" class="inputdisabled ui-corner-all" value="{$category}" size="25" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{/if}
								{if $idlang != 0}
								<tr>
									<td class="label"><label for="idlang" class="inlinelabel">Langue :</label></td>
								</tr>
								<tr>
									<td>
									<input type="text" disabled="disabled" readonly="readonly" id="codelang" name="codelang" class="inputdisabled ui-corner-all" value="{$codelang}" size="5" />
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
								{/if}
								{$selectlang}
								<tr>
									<td class="label"><label for="idcategory" class="inlinelabel">Catégorie :</label></td>
								</tr>
								<tr>
									<td>
										<select id="idcategory" name="idcategory">
											<option value="">Aucune catégorie</option>
										</select>
									</td>
									<td style="width:150px;" class="errorInput"></td>
								</tr>
								<tr>
									<td class="status"></td>
								</tr>
							</table>			
						</fieldset>
						<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
					</form>
					{else}
					<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
					<span style="float:left;" class="ui-icon ui-icon-alert"></span>
						Vous n'avez pas la permission d'administrer ce module
					</div>
					{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	dynamical_select_json(
		'#move-cms-page',
		'/admin/cms.php?add&json=true',
		['idlang','idcategory']		
	);
});
</script>
</body>
</html>