{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>Dashboard</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-folder-collapsed"></span>Construction de menu</div>
						<div class="dashboard-widget-content">
						{if $configcms eq 1}
						{$navconstruct}
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
				<div class="column">
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-bookmark"></span>Ordre du menu</div>
						<div class="dashboard-widget-content">
						{if $configcms eq 1}
						<ul id="sortable">
						{$navorder}
						</ul>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission d'administrer ce module
						</div>
						{/if}
						</div>
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{include file="common/javascript.phtml"}
{magixmin}
{literal}
<script type="text/javascript">
$(document).ready(function(){
	$('#sortable li').hover(
			function() { $(this).addClass('ui-state-hover'); },
			function() { $(this).removeClass('ui-state-hover'); }
	);
	$("#sortable").sortable({
		axis: "y",
		cursor: "move",
		update : function () {
			serial = $('#sortable').sortable('serialize');
			$.ajax({
				url: "{/literal}{geturl}{literal}/admin/dashboard/cms/navigation/",
				type: "post",
				data: serial,
				error: function(){
					alert("theres an error with AJAX");
				}
			});
		}
	});
	$("#sortable").disableSelection();
	$(".forms-cms-navigation").each(function(el){
		var id = $(this).attr("id");
		$("#"+id+" :radio").click(function(){
			$("#"+id).ajaxSubmit({
				url:"{/literal}{geturl}/admin/dashboard/cms/navigation/{literal}",
				type:"post"
			});
		});
	});
});
</script>
{/literal}
{/magixmin}
</body>
</html>