<div id="clearcache-dialog" style="display:none;">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>
	Etes-vous sur de vouloir effectuer cette action ?</p>
	<div class="ui-widget-header ui-corner-all" style="margin-top:3px;padding:3px;min-height:32px;">
		<span style="float:left;" class="notify-32-icon notify-32-icon-light-bulb"></span>
		<p style="margin-top:5px;">N'oubliez pas de recharger votre site internet</p>
	</div>
</div>
<script type="text/javascript" src="/plugins/{$pluginName}/js/admin.js"></script>