{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
<div class="container-narrow">
    {include file="section/top.phtml"}
    <div class="container-fluid">
        <ul class="breadcrumb">
            <li>
                <a href="#">Démarrer</a> <span class="divider">/</span>
            </li>
            <li>
                <span class="active">Analyse</span>
            </li>
        </ul>
        <div id="list_checking"></div>
        <div id="list_chmod"></div>
        <ul class="pager">
            <li class="previous">
                <a href="/install/index.php">&larr; Précédent</a>
            </li>
            <li class="next">
                <a href="/install/config.php">Suivant &rarr;</a>
            </li>
        </ul>
    </div>
    {include file="section/footer.phtml"}
</div>
{include file="section/js.phtml"}
{include file="analysis/section/js.phtml"}
</body>
</html>