<form id="forms_news_edit" method="post" action="">
    <p>
        En ligne <input type="radio" name="published" value="1"{if $published eq 1} checked="checked"{/if} />
        Hors ligne <input type="radio" name="published" value="0"{if $published eq 0} checked="checked"{/if} />
    </p>
    <p>
        <label for="newslink">URL</label>
        <input type="text" class="input-xxlarge" id="newslink" readonly="readonly" size="50" value="" />
    </p>
    <p class="pull-left">
        <label for="iso">ISO</label>
        <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
    </p>
    <p class="controls-row offset1 input-append">
        <label for="n_uri">URL Simplifié</label>
        <input type="text" class="input-xlarge" id="n_uri" name="n_uri" readonly="readonly" size="30" value="{$n_uri}" />
        <a class="unlocked" href="#">
            <span class="add-on icon-lock"></span>
        </a>
    </p>
    <p>
        <label for="n_title">Titre :</label>
        <input type="text" class="input-xlarge" id="n_title" name="n_title" value="{$n_title}" size="50" />
    </p>
    <p>
        <label for="n_content" class="inlinelabel">Contenu :</label>
        <textarea name="n_content" id="n_content" class="mceEditor">{$n_content}</textarea>
    </p>
    <p>
        <input type="submit" class="btn btn-primary" value="Envoyer" />
    </p>
</form>