{if $smarty.get.tab eq "image"}
<form id="forms_news_edit_image" method="post" action="" enctype="multipart/form-data">
    <p>
        <label for="n_image">Image :</label>
        <input type="hidden" name="MAX_FILE_SIZE" value="2048576" />
        <input type="file" id="n_image" name="n_image" value="" />
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>
<div id="load_news_img">
    <div id="contener_image"></div>
</div>
{elseif $smarty.get.tab eq "tags"}
<p>
    <label for="name_tag">Tags</label>
    <input type="text" class="input-xxlarge" id="name_tag" class="tags" value="{$tags}" />
</p>
{else}
<form id="forms_news_edit" method="post" action="">
    <p>
        {#online#|ucfirst} <input type="radio" name="published" value="1"{if $published eq 1} checked="checked"{/if} />
        {#offline#|ucfirst} <input type="radio" name="published" value="0"{if $published eq 0} checked="checked"{/if} />
    </p>
    <p>
        <label for="newslink">URL</label>
        <input type="text" class="input-xxlarge" id="newslink" readonly="readonly" size="50" value="" />
    </p>
    <p class="pull-left">
        <label for="iso">ISO</label>
        <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
    </p>
    <p class="controls-row offset1 input-append">
        <label for="n_uri">{#url_rewriting#|ucfirst}</label>
        <input type="text" class="input-xlarge" id="n_uri" name="n_uri" readonly="readonly" size="30" value="{$n_uri}" />
        <a class="unlocked" href="#">
            <span class="add-on icon-lock"></span>
        </a>
    </p>
    <div class="clearfix"></div>
    <p>
        <label for="n_title">{#label_title#|ucfirst} :</label>
        <input type="text" class="input-xlarge" id="n_title" name="n_title" value="{$n_title}" size="50" />
    </p>
    <p>
        <label for="n_content" class="inlinelabel">{#label_content#|ucfirst} :</label>
        <textarea name="n_content" id="n_content" class="mceEditor">{$n_content}</textarea>
    </p>
    <p>
        <input type="submit" class="btn btn-primary" value="{#send#|ucfirst}" />
    </p>
</form>
{/if}