{doctype type="XHTML1_STRICT"}
<html xmlns="http://www.w3.org/1999/xhtml" lang="fr" xml:lang="fr">
  <head>
    {headmeta meta="contentType" content="html" charset="utf8"}
    {headmeta meta="contentStyleType" content="css"}
    {headmeta meta="contentLanguage" content="fr"}
    <meta name="DC.Language" content="fr" />
    <meta name="DC.Creator" content="web-solution-way.be" />
    {headmeta meta="keywords" content=""}
    {headmeta meta="robots" content="noindex,nofollow"}
	<link rel="SHORTCUT ICON" href="" />
	{include file="common/styles.phtml"}