<div id="slider" class="ui-widget-content ui-corner-all">
	<img src="/install/img/slider/slider01.jpg" width="750" height="235" title="Une documentation simple" alt="" />
	<img src="/install/img/slider/slider02.jpg" width="750" height="235" title="Notre communauté de contributeurs" alt="" />
	<img src="/install/img/slider/slider03.jpg" width="750" height="235" title="Créer vos propres templates" alt="" />
</div>