<form id="forms_catalog_category_edit" method="post" action="">
    <p>
        <label for="categorylink">URL</label>
        <input type="text" class="input-xxlarge" id="categorylink" readonly="readonly" size="50" value="" />
    </p>
    <p class="pull-left">
        <label for="iso">ISO</label>
        <input type="text" class="input-mini" id="iso" disabled="disabled" readonly="readonly" size="3" value="{$iso|upper}" />
    </p>
    <p class="controls-row offset1 input-append">
        <label for="pathclibelle">URL Simplifié</label>
        <input type="text" class="input-xlarge" id="pathclibelle" name="pathclibelle" readonly="readonly" size="30" value="{$pathclibelle}" />
        <a class="unlocked" href="#">
            <span class="add-on icon-lock"></span>
        </a>
    </p>
    <p>
        <label for="clibelle">Titre :</label>
        <input type="text" class="input-xlarge" id="clibelle" name="clibelle" value="{$clibelle}" size="50" />
    </p>
    <p>
        <label for="content_c" class="inlinelabel">Contenu :</label>
        <textarea name="content_c" id="content_c" class="mceEditor">{$content_c}</textarea>
    </p>
    <p>
        <input type="submit" class="btn btn-primary" value="Envoyer" />
    </p>
</form>