	<div class="block bg-light w4-16 lfloat">
		<p class="title">
			<a href="{geturl}/{getlang}/{#topmenu_catalog_uri#}/">{#topmenu_catalog_t#|firststring}</a>
		</p>
		{widget_catalog_sidebar_category}
	</div>
	<div class="block w2-16 lfloat last">
		<p class="title">Partager</p>
	  	{widget_social_network 
	  		config_param=[
	  		'news'=>[{#topmenu_news_t#},$n_title],
	  		'cms'=>[$title_page],
	  		'catalog'=>[{#topmenu_catalog_t#},$clibelle,$slibelle,$titlecatalog],
	  		'plugins'=>['contact'=>{#pn_contact_forms#}]
	  		] 
	  		size="special" 
	  		default=$subject}
	</div>
	<div class="clear"></div>
	<div class="block bg-light w4-16 lfloat">
		<p class="title">Voir aussi</p>
		 {widget_cms_sidebar_page} 
	</div>
	<div class="clear"></div>
	<div class="block w6-16 bg-light last">
	<p class="title">Dernière news</p>
	{widget_news_last 
		contentlength="125" 
		delimiter="..." 
		ui=false 
		newsall="Voir les news"
		css_param=[
			'class_elem'=>'child',
			'class_img'=>'rfloat img'
		]
		tag=""
	}
	</div>
	<div class="block w6-16 bg-light last">
	 	{widget_load_catalog_category_last_products 
	 		css_param=[ 
				'class_container'=>'ch1-2 ch-light',
				'class_elem'=>'child',
				'class_img'=>'img'
			] 
	 		category=["fr"=>"1"] 
	 		limit_products="4" 
	 		size="mini" 
	 		tposition="bottom" 
	 		col="2" 
	 		price=false 
	 		description=true 
	 		contentlength="124"
	 	}	
	</div>
	<div class="clear"></div>