	<p class="title bg light">
		<a href="{geturl}/{getlang}/{#topmenu_catalog_uri#}/">{#topmenu_catalog_t#|firststring}</a>
	</p>
	<div class="bg-top w5-16 light"></div>
	<div class="bg-repeat bg dark w5-16 light">
		{widget_catalog_sidebar_category}
	</div>
	<div class="bg-bottom w5-16 light"></div>

	<div class="block w5-16 bg dark last">
		<p class="title align">Vous voulez un site sympa ?</p>
		<a class="button w4-16 light align" href="{geturl}/{getlang}/{#topmenu_contact_uri#}"><span>Contactez nous</span></a>
	</div>
	<div class="block bg w5-16 last">
		<p class="title">Partager</p>
  	{widget_social_network size="medium" default=$subject config_param=['news'=>[{#topmenu_news_t#},$n_title],'cms'=>[$title_page],'catalog'=>[{#topmenu_catalog_t#},$clibelle,$slibelle,$titlecatalog],'plugins'=>['contact'=>{#pn_contact_forms#}]]}
	</div>
	<div class="block w5-16 bg last">
	 	{widget_load_catalog_category_last_products size="medium" tposition="bottom" category=["fr"=>"1"] limit_products="4" col="2" price=false description=true contentlength="124"}	
	</div>
	<div>
		<p class="title">Voir aussi</p>
		 {widget_cms_sidebar_page} 
	</div>
	<div class="clear"></div>