<div id="footer" class="full">
	<div class="bg-2 full">
		<div class="container">
			<div class="block">
			<p class="align" style="color: #FFFFFF">Theme par default de <a style="color: #FFFFFF" href="http://www.magix-cms.com" title="Site de magix cms">Magix CMS</a></p>
			</div>
			<p class="bg dark credit align">
		     	{#powered_by#}
		    	<a class="targetblank" href="http://www.magix-cms.com/">Magix CMS</a>		
			</p>
		</div>
	</div>
</div>
{* {notify_dir_header} *}
{ajax_notify}
{include file="common/javascript.phtml"}