	<div id="pieddepage">
	<p>Thème par défaut de <a class="targetblank" href="http://www.magix-cms.com/">Magix CMS</a></p>
	</div>
</div>
<div id="barfixed">
	<div id="breadcrum">
		<ul>
	     {ariane title="My website"}
	    </ul>
	     <div class="micro-footer">
	    	<a class="targetblank" href="http://www.magix-cms.com/">Magix CMS</a>
    	</div>
    </div>
</div>
{notify_dir_header}
{include file="common/javascript.phtml"}