	<div id="pieddepage">
	<p>Thème par défaut de <a class="targetblank" href="http://www.logiciel-referencement-professionnel.com/">Magix CMS</a></p>
	</div>
</div>
<div id="barfixed">
	<div id="breadcrum">
		<ul>
	     {ariane title="Cms"}
	    </ul>
	     <div class="micro-footer">
	    	<a href="http://www.web-solution-way.be/creation-de-site-internet.html">Création de site</a> <a href="http://www.web-solution-way.be">Web Solution Way</a>
    	</div>
    </div>
</div>
{notify_header}
{include file="common/javascript.phtml"}