<div id="headmenu">
	<div>
		<ul>
			<li><a href="{geturl}/{getlang}">{#topmenu_home_t#|firststring}</a></li>
			<li><a href="{geturl}/{getlang}{#topmenu_catalog_uri#}">{#topmenu_catalog_t#|firststring}</a></li>
			<li><a href="{geturl}/{getlang}{#topmenu_news_uri#}">{#topmenu_news_t#|firststring}</a></li>
			<li><a href="{geturl}/{getlang}{#topmenu_contact_uri#}">{#topmenu_contact_t#|firststring}</a></li>
		</ul>
	</div>
</div>