{config_load file="local`$smarty.get.strLangue`.conf" scope="global"}{doctype type="XHTML1_STRICT"}
<html xmlns="http://www.w3.org/1999/xhtml" lang="{sessionlang}" xml:lang="mis">
  <head>
    {headmeta meta="contentType" content="html" charset="utf8"}
    {headmeta meta="contentStyleType" content="css"}
    {headmeta meta="contentLanguage" content="fr,en,nl"}
    <meta name="DC.Language" content="{$smarty.session.strLangue}" />
    <meta name="DC.Creator" content="magix-cms.com" />
    {headmeta meta="keywords" content=""}
    {headmeta meta="robots" content="index,follow,all"}
    {headmeta meta="revisitAfter" int="3" delay="days"}
{if {module type="news"} eq true}{headlink rel="rss" href="{geturl}/rss.xml"}{/if}
	<link rel="icon" type="image/png" href="{geturl}/skin/{template}/img/favicon.png" />
	<!--[if IE]><link rel="shortcut icon" type="image/x-icon" href="{geturl}/skin/{template}/img/favicon.ico" /><![endif]-->