{script src="/min/?g=publicjs" type="javascript"}
{script src="/min/?f=skin/{template}/js/lib/plugins/jquery.treeview.js,skin/{template}/js/lib/globalforms-1.0.0.js,skin/{template}/js/lib/globaljs-1.0.js" type="javascript"}
{google_tools tools='analytics'}
{literal}
<script type="text/javascript" src="http://apis.google.com/js/plusone.js">
	{lang: "{/literal}{getlang}{literal}"}
</script>
<script type="text/javascript">
	gapi.plusone.render("googlebtn",{"parsetags": "explicit","size": "medium", "count": "true"});
</script>
{/literal}