{script src="/min/?g=publicjs,jimagine" type="javascript"}
<script type="text/javascript">
	var iso = "{getlang}";
</script>
{script src="/min/?f=skin/{template}/js/lib/plugins/jquery.treeview.js,skin/{template}/js/lib/globalforms-1.0.0.js,skin/{template}/js/lib/globaljs-1.0.js" type="javascript"}
{literal}
<script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
<script type="text/javascript">
	window.___gcfg = {
	   lang: "{/literal}{getlang}{literal}"
	};
	gapi.plusone.render("googlebtn",{"parsetags": "explicit","size": "medium", "count": "true"});
</script>
{/literal}