	<div id="header" class="full">
		<div class="container">
			{widget_lang_prelude config_param=['icons'=>false]}
			<div id="logo" class="block w6-16 lfloat">
				<a href="/" title="Magix CMS: le CMS dédié au référencement">
					<img src="/skin/{template}/img/logo-magix_cms.png" title="Magix CMS: le CMS dédié au référencement" alt="Logo Magix CMS" />
				</a>
			</div>
			{include file="common/topmenu.phtml"}
		</div>
	</div>
