{* {widget_hmenu parentcss="l1" ulid="topmenu"} *}
<ul id="topmenu" class="block w10-16 lfloat last list float h-nav">
	<li>
		<a href="{geturl}/{getlang}/">
			{#topmenu_home_t#|firststring}
		</a>
	</li>
	<li>
		<a href="{geturl}/{getlang}/{#topmenu_catalog_uri#}/">
			{#topmenu_catalog_t#|firststring}
		</a>
	</li>
	<li>
		<a href="{geturl}/{getlang}/{#topmenu_news_uri#}/">
			{#topmenu_news_t#|firststring}
		</a>
	</li>
	<li>
		<a href="{geturl}/{getlang}/{#topmenu_contact_uri#}/">
			{#topmenu_contact_t#|firststring}
		</a>
		<ul>
			<li>sdqdqs</li>
		</ul>
	</li>
</ul>
<div class="clear"></div>
