{* {widget_hmenu parentcss="l1" ulid="topmenu"} *}
<ul id="topmenu" class="nav-horizontal">
	<li class="l1"><a href="{geturl}/{getlang}/">{#topmenu_home_t#|firststring}</a></li>
	<li class="l1"><a href="{geturl}/{getlang}/{#topmenu_catalog_uri#}/">{#topmenu_catalog_t#|firststring}</a></li>
	<li class="l1"><a href="{geturl}/{getlang}/{#topmenu_news_uri#}/">{#topmenu_news_t#|firststring}</a></li>
	<li class="l1">
		<a href="{geturl}/{getlang}/{#topmenu_contact_uri#}/">{#topmenu_contact_t#|firststring}</a>
		<ul>
			<li><a href="#" title="test">test</a></li>
			<li><a href="#" title="test">test</a></li>
			<li><a href="#" title="test">test</a></li>
		</ul>
	</li>
</ul>
<div class="clear"></div>
