{include file="section/head.phtml"}
<title>Test</title>
</head>
<body class="module-dashboard">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    <h2>Ajouter une page rapide</h2>
                    {include file="cms/forms/add_page_p.phtml"}
                </div>
            </div>
        </div>
    </div>
{include file="section/footer.phtml"}
</div>
{include file="section/js.phtml"}
{include file="cms/section/js.phtml"}
</body>
</html>