{include file="cplugin/layout_up.phtml"}
<div class="dashboard ui-widget-content ui-corner-all">
<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Voyage {$pluginName}</div>
	<div class="dashboard-content">
	{$pager}
	<div class="fg-button ui-state-default ui-corner-all" style="margin:5px;width:135px;"><a href="{$pluginUrl}&amp;add">Ajouter</a></div>
	</div>
</div>
{include file="cplugin/layout_down.phtml"}