{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
<div class="container-started">
    <div class="jumbotron">
        <h1>{#h1_home#}</h1>
        <p class="lead">
            {#p_lead_home#}
        </p>
        <a class="btn btn-large btn-success" href="/install/analysis.php">
            {#start#}
        </a>
    </div>
</div>
{include file="section/js.phtml"}
{include file="home/section/js.phtml"}
</body>
</html>