{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
{include file="section/top.phtml"}
<div class="container">
    <div class="row-fluid">
        <div class="span12">
            <div class="row-fluid">
                <div class="span12">
                    <h1>Installation de Magix CMS</h1>
                </div>
            </div>
        </div>
    </div>
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="home/section/js.phtml"}
</body>
</html>