{include file="section/head.phtml"}
<title>Magix CMS | Install</title>
</head>
<body class="install">
<div class="container-started">
    <div class="jumbotron">
        <h1>Installation de Magix CMS</h1>
        <p class="lead">
            Vous êtes prêt démarrer l'installation,
            une série de test sera effectuée pour la prise en charge de Magix CMS
        </p>
        <a class="btn btn-large btn-success" href="/install/analysis.php">
            Démarrer
        </a>
    </div>
</div>
{include file="section/js.phtml"}
{include file="home/section/js.phtml"}
</body>
</html>