<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">{#catalog#|ucfirst}</a></li>
                    <li{if !$smarty.get.section} class="active" {/if}><a href="/{baseadmin}/catalog.php">{#statistics#|ucfirst}</a></li>
                    {if $smarty.get.getlang}
                    <li{if $smarty.get.section eq 'category'} class="active" {/if}><a href="/{baseadmin}/catalog.php?section=category&amp;getlang={$smarty.get.getlang}">{#categories#|ucfirst}</a></li>
                    <li{if $smarty.get.section eq 'product'} class="active" {/if}><a href="/{baseadmin}/catalog.php?section=product&amp;getlang={$smarty.get.getlang}">{#products#|ucfirst}</a></li>
                    {/if}
                </ul>
                <form action="" class="navbar-search pull-right">
                    {if $smarty.get.section eq 'category'}
                    <input type="text" id="name_category" name="name_category" placeholder="Search" class="search-query">
                    {elseif $smarty.get.section eq 'product'}
                    <input type="text" id="name_product" name="name_product" placeholder="Search" class="search-query">
                    {/if}
                </form>
            </div>
        </div>
    </div>
</div>