<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">Catalogue</a></li>
                    <li><a href="/{baseadmin}/catalog.php">Statistiques</a></li>
                </ul>
                <form action="" class="navbar-search pull-right">
                    <input type="text" id="title_search" name="title_search" placeholder="Search" class="search-query">
                </form>
            </div>
        </div>
    </div>
</div>