<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">Catalogue</a></li>
                    <li{if !$smarty.get.section} class="active" {/if}><a href="/{baseadmin}/catalog.php">Statistiques</a></li>
                    {if $smarty.get.getlang}
                    <li{if $smarty.get.section eq 'category'} class="active" {/if}><a href="/{baseadmin}/catalog.php?section=category&amp;getlang={$smarty.get.getlang}">Catégories</a></li>
                    <li{if $smarty.get.section eq 'product'} class="active" {/if}><a href="/{baseadmin}/catalog.php?section=product&amp;getlang={$smarty.get.getlang}">Produits</a></li>
                    {/if}
                </ul>
                <form action="" class="navbar-search pull-right">
                    <input type="text" id="title_search" name="title_search" placeholder="Search" class="search-query">
                </form>
            </div>
        </div>
    </div>
</div>