{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="column">
				<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-gear"></span>Version</div>
						<div class="dashboard-widget-content">
							<table class="clear">
								<tr class="line">
									<td><span style="float:left;margin:0 2px 0 15px;" class="magix-icon magix-icon-info"></span><div id="version"></div></td>
								</tr>
							</table>
							<table style="margin:0 0 5px 0;padding:0;font-size:11px;border:none;">
								<tbody>
								<tr>
								<td style="padding:0 5px 0 5px;border:none;"><div style="width:105px;padding:5px;margin:0;" class="ui-state-default ui-corner-all">
									<span style="float:left;" class="magix-icon magix-icon-lightbulb"></span>&nbsp;<a style="text-decoration:underline;" class="targetblank strong" href="http://documentation.logiciel-referencement-professionnel.com">Documentation</a></div>
								</td>
								<td style="padding:0 5px 0 5px;border:none;">
									<div style="width:50px;padding:5px;margin:0;" class="ui-state-default ui-corner-all">
										<span style="float:left;" class="magix-icon magix-icon-tools"></span>&nbsp;<a style="text-decoration:underline;" class="targetblank strong" href="http://formation.logiciel-referencement-professionnel.com">API</a>
									</div>
								</td>
								<td style="padding:0 5px 0 5px;border:none;">
									<div style="width:130px;padding:5px;margin:0;" class="ui-state-default ui-corner-all">
										<span style="float:left;" class="magix-icon magix-icon-plugin"></span>&nbsp;<a style="text-decoration:underline;" class="targetblank strong" href="http://www.cms-php.be">Plugins disponibles</a>
									</div>
								</td>
								</tr>
								</tbody>
							</table>
						</div>
					</div>
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span>Utilisateurs</div>
						<div class="dashboard-widget-content">
							{widget_online_members}
						</div>
					</div>
					{if $configcms eq 1}
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document"></span>Dernières pages CMS ajoutées</div>
						<div class="dashboard-widget-content">
							{widget_cms limit="true" max="5" viewuser="false"}
						</div>
					</div>
					{/if}
				</div>
				<div class="column">
				{if $configcatalog eq 1}
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-cart"></span>Derniers articles ajoutés dans le catalogue</div>
						<div class="dashboard-widget-content">
							{widget_catalog limit="true" max="5" sort="product" viewuser="false"}
						</div>
					</div>
				{/if}
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-home"></span>La page d'accueil</div>
						<div class="dashboard-widget-content">
							{widget_home viewuser="false"}
						</div>
					</div>
				{if $confignews eq 1}
					<div class="dashboard-widget ui-widget ui-widget-content ui-helper-clearfix ui-corner-all">
						<div class="dashboard-widget-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-document-b"></span>Les news</div>
						<div class="dashboard-widget-content">
							{widget_news limit="true" max="5" viewuser="false"}
						</div>
					</div>
				{/if}
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
<div id="dialog_delete" style="display:none;">
	<p>Etes-vous sur de vouloir supprimer cet élément ?</p>
</div>
<div id="confirm_published" title="Publication d'une news" class="hide">
	<p style="font-size:14px;">
		Voulez-vous changer le status cette page ?
	</p>
</div>
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	/*jm_constant.define("lang","fr");
	if(jm_constant.defined("lang") == false){
	console.log("Constant is not defined");
	}else{
		console.log(jm_constant.get("lang"));
	}
	*/
	$.getScript('/framework/js/backend/ns/jdashboard.0.2.min.js',function(){
		if (typeof ns_jdashboard == "undefined") {
		  log("ns_jdashboard is not defined");
		}else{
			ns_jdashboard.run();
		}
	});
});
</script>
</body>
</html> 