<form id="forms_plugins_translation" method="post" action="">
{foreach $array_config_file as $key => $value nocache}
    <div class="controls controls-row">
        <input type="text" class="span3" name="config_var[]" value="{$key}" readonly="readonly" size="50" />
        <input type="text" class="span5" name="config_value[]" value="{$value}" size="50" />
    </div>
{/foreach}
    <p>
        <input type="submit" class="btn btn-primary" />
    </p>
</form>