{include file="common/head.phtml"}
<meta name="description" content="" />
    <title>{widget_titlepage}</title>
</head>
<body>
<div id="page">
	{include file="common/top.phtml"}
		<div id="content">
			{include file="common/sidebar.phtml"}
			<div id="main">
				<div id="mainbar" class="ui-widget-header ui-corner-all">
					<div class="username ui-widget-content ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-person"></span> {widget_session_identifier}</div>
					{include file="common/topmicrobar.phtml"}
					<div class="fariane"><ul>{admin_ariane}</ul></div>
				</div>
				<div class="dashboard ui-widget-content ui-corner-all">
					<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-refresh"></span>Mise à jour utilisateur</div>
					<div class="dashboard-content">
					{if $current_perm <= $user_perms}
						<form id="forms-users-update" method="post" action="" style="margin-left:10px;">
						{$msg}
							<fieldset>
								<table>
									<tr>
										<td class="label"><label for="pseudo" class="inlinelabel">Pseudo :</label></td>
									</tr>
									<tr>
										<td>
										<input type="hidden" id="iduser" value="{$smarty.get.edit}" />
										<input type="text" id="pseudo" name="pseudo" class="inputtext ui-corner-all" value="{$pseudo}" size="20" /></td>
									</tr>
									<tr>
										<td class="label"><label for="email" class="inlinelabel">Email :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="email" name="email" class="inputtext ui-corner-all" value="{$email}" size="30" /></td>
										<td style="width:150px;" class="errorInput"></td>
									</tr>
									<tr>
										<td class="label"><label for="cryptpass" class="inlinelabel">Mot de passe :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="cryptpass" name="cryptpass" class="inputtext password ui-corner-all" value="" size="20" />
										<button id="randPassword" class="btnwrench">genere</button></td>
									 </tr>
									 <tr>
										<td>
							  				<div class="password-meter">
							  					<div class="password-meter-message">&nbsp;</div>
							  					<div class="password-meter-bg">
								  					<div class="password-meter-bar"></div>
							  					</div>
							  				</div>
										</td>
									</tr>
									<tr>
										<td class="label"><label for="cryptpass_confirm">Confirm :</label></td>
									</tr>
									<tr>
										<td><input type="text" id="cryptpass_confirm" name="cryptpass_confirm" class="inputtext ui-corner-all" value="" size="20" /></td>
									</tr>
									<tr>
										<td class="label"><label for="perms" class="inlinelabel">Permission :</label></td>
									</tr>
									<tr>
										<td>
										<select id="perms" class="select" name="perms">
										{if $perms eq 1}
											<option value="1" selected="selected">Seo Agency</option>
											<option value="2">Web Agency</option>
											<option value="3">User admin</option>
											<option value="4">User</option>
										{elseif $perms eq 2}
											<option value="2" selected="selected">Web Agency</option>
											<option value="3">User admin</option>
											<option value="4">User</option>
										{elseif $perms eq 3}
											<option value="3" selected="selected">User admin</option>
											<option value="4">User</option>
										{elseif $perms eq 4}
											<option value="4">User</option>
										{/if}
										</select>
										</td>
									</tr>
								</table>			
							</fieldset>
							<div style="margin:5px;"><input type="submit" value="envoyer" /></div>
						</form>
						{else}
						<div style="margin:5px;padding:5px;" class="ui-state-error ui-corner-all">
						<span style="float:left;" class="ui-icon ui-icon-alert"></span>
							Vous n'avez pas la permission de modifier cet utilisateur
						</div>
						{/if}
					</div>
				</div>
			</div>
		</div>
	{include file="common/footer.phtml"}
</div>
{ajax_notify}
{include file="common/javascript.phtml"}
<script type="text/javascript">
$(function(){
	$.getScript('/framework/js/backend/juserAdmin.1.0.js');
});
</script>
</body>
</html>