<form id="forms-users" method="post" action="" style="margin-left:10px;">
	<fieldset>
		<table>
			<tr>
				<td class="label"><label for="pseudo" class="inlinelabel">Pseudo :</label></td>
			</tr>
			<tr>
				<td><input type="text" id="pseudo" name="pseudo" class="inputtext ui-corner-all" value="" size="20" /></td>
			</tr>
			<tr>
				<td class="label"><label for="email" class="inlinelabel">Email :</label></td>
			</tr>
			<tr>
				<td><input type="text" id="email" name="email" class="inputtext ui-corner-all" value="" size="30" /></td>
			</tr>
			<tr>
				<td class="label"><label for="cryptpass" class="inlinelabel">Mot de passe :</label></td>
			</tr>
			<tr>
				<td><input type="text" id="cryptpass" name="cryptpass" class="inputtext password ui-corner-all" value="" size="20" />
				<button id="randPassword" class="btnwrench">genere</button></td>
			 </tr>
			 <tr>
				<td>
	  				<div class="password-meter">
	  					<div class="password-meter-message">&nbsp;</div>
	  					<div class="password-meter-bg">
		  					<div class="password-meter-bar"></div>
	  					</div>
	  				</div>
				</td>
			</tr>
			<tr>
				<td class="label"><label for="cryptpass_confirm">Confirm :</label></td>
			</tr>
			<tr>
				<td><input type="text" id="cryptpass_confirm" name="cryptpass_confirm" class="inputtext ui-corner-all" value="" size="20" /></td>
			</tr>
			<tr>
			<td class="label"><label for="perms" class="inlinelabel">Permission :</label></td>
			</tr>
			<tr>
				<td>
				<select id="perms" class="select" name="perms">
				{if $perms eq 1}
					<option value="1">Seo Agency</option>
					<option value="2" selected="selected">Web Agency</option>
					<option value="3">User admin</option>
					<option value="4">User</option>
				{elseif $perms eq 2}
					<option value="2">Web Agency</option>
					<option value="3" selected="selected">User admin</option>
					<option value="4">User</option>
				{elseif $perms eq 3}
					<option value="3">User admin</option>
					<option value="4" selected="selected">User</option>
				{/if}
				</select>
				</td>
				<td style="width:150px;" class="errorInput"></td>
			</tr>
		</table>			
	</fieldset>
	<div style="margin:5px;"><input type="submit" value="Envoyer" /></div>
</form>