<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <div class="nav-collapse collapse navbar-responsive-collapse">
                <ul class="nav">
                    <li><a class="brand" href="#">Seo</a></li>
                    <li><a href="/{baseadmin}/seo.php">Statistiques</a></li>
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#">Langues <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                        {foreach $array_lang as $key => $value nocache}
                            <li>
                                <a href="/{baseadmin}/seo.php?getlang={$key}&amp;action=list">
                                    <span><img src="/{baseadmin}/template/img/flags/{$value}.png" alt="{$value}" /> {$value|upper}</span>
                                </a>
                            </li>
                        {/foreach}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>