<p>
    <a href="#metas" class="btn showit">
        <span class="icon-plus"></span> Ajouter une réécriture
    </a>
</p>
<div class="collapse-item" id="metas">
    <form id="forms_seo_add" method="post" action="">
        <p>
            {$select_attribute}
        </p>
        <p>
            {$select_level}
        </p>
        <p>
            {$select_metas}
        </p>
        <p>
            <textarea id="strrewrite" name="strrewrite" class="span8" rows="2"></textarea>
        </p>
        <ul class="inline">
            <li>
                <a href="#" id="add-category" class="btn btn-link"><span class="icon-plus"></span> Catégorie</a>
            </li>
            <li>
                <a href="#" id="add-subcategory" class="btn btn-link"><span class="icon-plus"></span> Sous Catégorie</a>
            </li>
            <li>
                <a href="#" id="add-product" class="btn btn-link"><span class="icon-plus"></span> Produits</a>
            </li>
        </ul>
        <p>
            <input type="submit" class="btn btn-primary" value="Envoyer" />
        </p>
    </form>
</div>