{include file="section/head.phtml"}
<title>Magix CMS | Admin</title>
</head>
<body class="module-cms">
{include file="section/top.phtml"}
<div class="container-fluid">
    <div class="row-fluid">
    {include file="section/colleft.phtml"}
        <div class="span9">
            <div class="row-fluid">
                <div class="span12">
                    {include file="news/section/nav.phtml"}
                    <h1>Liste des actualités</h1>
                    <p>
                        <a class="btn btn-primary" href="#" id="open-add">
                            <span class="icon-plus"></span> Ajouter une page
                        </a>
                    </p>
                    <div class="mc-message clearfix"></div>
                    <div id="list_news"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="forms-add" class="hide" title="Ajouter une nouvelle page">
{*{include file="news/forms/add.phtml"}*}
</div>
{include file="section/footer.phtml"}
{include file="section/js.phtml"}
{include file="news/section/js.phtml"}
</body>
</html>