<div class="dashboard ui-widget-content ui-corner-all">
	<div class="dashboard-header ui-widget-header ui-corner-all"><span style="float:left;" class="ui-icon ui-icon-plusthick"></span>Extension du produit</div>
	<div class="dashboard-content">
		<form id="forms-catalog-sold" method="post" action="" style="margin-left:10px;">
			<fieldset>
				<table>
				<tr>
					<td class="label"><label for="idcatalog" class="inlinelabel">Cette article est vendu :</label></td>
				</tr>
					<tr>
						<td>
						<p><input type="hidden" id="idcatalog" name="idcatalog" value="{$smarty.get.editproduct}" /></p>
						<p><input type="checkbox" id="sold" name="sold" value="1" /></p>
						</td>
						<td style="width:150px;" class="errorInput"></td>
				</tr>
				<tr>
					<td class="status"></td>
				</tr>
				</table>
			</fieldset>
		</form>
	</div>
</div>